# Generated by Django 5.2.7 on 2026-07-20 14:54

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('unit_type', models.CharField(choices=[('department', 'Отдел'), ('division', 'Управление'), ('group', 'Группа')], db_default='department', default='department', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Работает'), ('inactive', 'Неактивен'), ('terminated', 'Уволен')], db_default='active', default='active', max_length=20)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_default=False, default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='hr.employee'),
        ),
        migrations.CreateModel(
            name='LevelThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('level_number', models.IntegerField(unique=True)),
                ('weight_from', models.IntegerField()),
                ('weight_to', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('weight_from__lte', models.F('weight_to'))), name='ck_threshold_range'), models.CheckConstraint(condition=models.Q(('level_number__gte', 1)), name='ck_threshold_level_positive')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('title', models.CharField(max_length=255, unique=True)),
                ('grade', models.IntegerField(db_default=1, default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('weight', models.IntegerField(db_default=100, default=100, unique=True)),
                ('level', models.IntegerField(db_default=2, db_index=True, default=2)),
                ('is_system', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.position'),
        ),
    ]
