# Generated by Django 5.2.7 on 2026-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Работает'), ('inactive', 'Неактивен'), ('terminated', 'Уволен'), ('suspended', 'Приостановлен'), ('pending', 'На согласовании'), ('rejected', 'Отклонён')], db_default='active', default='active', max_length=20),
        ),
    ]
