# Generated by Django 5.2.7 on 2026-07-21 05:32

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionWeightAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_weight', models.IntegerField(blank=True, null=True)),
                ('new_weight', models.IntegerField(blank=True, null=True)),
                ('old_level', models.IntegerField(blank=True, null=True)),
                ('new_level', models.IntegerField(blank=True, null=True)),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('reason', models.CharField(blank=True, max_length=64, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_audits', to='hr.position')),
            ],
            options={
                'indexes': [models.Index(fields=['position', 'changed_at'], name='hr_position_positio_9cfe6d_idx')],
            },
        ),
    ]
