# Generated by Django 5.2.7 on 2026-07-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_positionweightaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionweightaudit',
            name='position',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='weight_audits', to='hr.position'),
        ),
    ]
