# Generated by Django 5.2.7 on 2026-07-21 07:23

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('relation_type', models.CharField(choices=[('direct', 'Прямое'), ('functional', 'Функциональное'), ('project', 'Проектное')], db_default='direct', default='direct', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('subordinate_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior_relations', to='hr.position')),
                ('superior_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_relations', to='hr.position')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('superior_position', 'subordinate_position', 'relation_type'), name='uq_reporting_relation'), models.CheckConstraint(condition=models.Q(('superior_position', models.F('subordinate_position')), _negated=True), name='ck_no_self_relation'), models.CheckConstraint(condition=models.Q(('relation_type__in', ['direct', 'functional', 'project'])), name='ck_relation_type')],
            },
        ),
    ]
