# Generated by Django 5.2.7 on 2026-07-21 09:58

import apps.hr.models
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_reportingrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('requirements', models.TextField(blank=True, db_default='', default='')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта'), ('on_hold', 'Приостановлена')], db_default='open', default='open', max_length=20)),
                ('opened_at', models.DateField(db_default=apps.hr.models._CurrentDate())),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('assigned_recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vacancies', to='hr.employee')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='hr.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='hr.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.CharField(max_length=255)),
                ('candidate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('resume_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('reviewed', 'Рассмотрен'), ('interview', 'Собеседование'), ('offer', 'Оффер'), ('rejected', 'Отклонён'), ('hired', 'Принят')], db_default='new', default='new', max_length=30)),
                ('applied_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('notes', models.TextField(blank=True, null=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
