# Generated by Django 5.2.7 on 2026-07-21 14:25

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_vacancy_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('event_type', models.CharField(choices=[('hired', 'Принят'), ('dismissed', 'Уволен'), ('transfer', 'Перевод'), ('promotion', 'Повышение'), ('demotion', 'Понижение'), ('other', 'Другое')], db_default='other', db_index=True, default='other', max_length=20)),
                ('event_date', models.DateField(db_index=True)),
                ('order_number', models.CharField(db_default='', default='', max_length=64)),
                ('comment', models.TextField(db_default='', default='')),
                ('created_by', models.IntegerField(blank=True, db_index=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_history', to='hr.employee')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_history_from', to='hr.department')),
                ('from_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_history_from_position', to='hr.position')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_history_to', to='hr.department')),
                ('to_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_history_to_position', to='hr.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffingPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('headcount', models.DecimalField(db_default=1, decimal_places=2, default=1, max_digits=5)),
                ('salary', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_lines', to='hr.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_lines', to='hr.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.IntegerField(db_default=0, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='hr.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'date', 'start_time'), name='uq_employee_time_entry')],
            },
        ),
    ]
