# Generated by Django 5.2.7 on 2026-07-21 15:18

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_personnelhistory_staffingposition_timeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('day', models.DateField(unique=True)),
                ('day_type', models.CharField(max_length=16)),
                ('norm_hours', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=4)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('name', models.CharField(max_length=100)),
                ('slots', models.JSONField(db_default=[], default=list)),
                ('holidays_off', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(db_default=False, default=False)),
                ('days', models.JSONField(db_default={}, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('anchor_date', models.DateField()),
                ('employee', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignment', to='hr.employee')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='hr.shiftpattern')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeWeekTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('employee', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='week_template_assignment', to='hr.employee')),
                ('week_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='hr.weektemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDayOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('day', models.DateField()),
                ('day_type', models.CharField(max_length=16)),
                ('norm_hours', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=4)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_overrides', to='hr.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'day'), name='uq_hr_emp_day_override')],
            },
        ),
    ]
