# Generated by Django 5.2.7 on 2026-07-21 16:09

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_calendarday_shiftpattern_weektemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('data', models.JSONField(db_default={}, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(db_default='application/octet-stream', default='application/octet-stream', max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hr.employee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to='hr.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocumentBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(db_index=True)),
                ('doc_type', models.CharField(db_index=True, max_length=50)),
                ('data', models.JSONField(db_default={}, default=dict)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['employee_id', 'doc_type'], name='hr_employee_employe_3b93e3_idx')],
            },
        ),
    ]
