# Generated by Django 5.2.7 on 2026-07-21 19:25

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employeegroups_document_employeedocumentblob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('suspended', 'Приостановлен'), ('closed', 'Закрыт')], db_default='active', default='active', max_length=20)),
                ('head_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_pmos', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PMODepartment',
            fields=[
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('stakeholder', 'Стейкхолдер'), ('support', 'Поддержка')], db_default='owner', default='owner', max_length=20)),
                ('pk', models.CompositePrimaryKey('pmo', 'department', blank=True, editable=False, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmo_departments', to='hr.department')),
                ('pmo', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='pmo_departments', to='hr.pmo')),
            ],
        ),
        migrations.CreateModel(
            name='PMOMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('permanent', 'Постоянное'), ('assigned', 'Назначенное'), ('consulting', 'Консультационное')], db_default='permanent', default='permanent', max_length=20)),
                ('position_in_pmo', models.CharField(blank=True, max_length=200, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('allocation_percent', models.SmallIntegerField(db_default=100, default=100)),
                ('is_primary', models.BooleanField(db_default=False, default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmo_memberships', to='hr.employee')),
                ('pmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hr.pmo')),
            ],
        ),
        migrations.CreateModel(
            name='PMOPosition',
            fields=[
                ('is_required', models.BooleanField(db_default=False, default=False)),
                ('headcount', models.IntegerField(db_default=1, default=1)),
                ('pk', models.CompositePrimaryKey('pmo', 'position', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pmo', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='pmo_positions', to='hr.pmo')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmo_positions', to='hr.position')),
            ],
        ),
        migrations.AddIndex(
            model_name='pmo',
            index=models.Index(fields=['status'], name='ix_hr_pmos_status'),
        ),
        migrations.AddConstraint(
            model_name='pmo',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'closed'])), name='ck_pmo_status'),
        ),
        migrations.AddConstraint(
            model_name='pmodepartment',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'stakeholder', 'support'])), name='ck_pmo_dept_role'),
        ),
        migrations.AddConstraint(
            model_name='pmomember',
            constraint=models.CheckConstraint(condition=models.Q(('membership_type__in', ['permanent', 'assigned', 'consulting'])), name='ck_pmo_member_type'),
        ),
        migrations.AddConstraint(
            model_name='pmomember',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_percent__gte', 0), ('allocation_percent__lte', 100)), name='ck_pmo_member_allocation_pct'),
        ),
        migrations.AddConstraint(
            model_name='pmomember',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__isnull', True), ('to_date__gte', models.F('from_date')), _connector='OR'), name='ck_pmo_member_dates'),
        ),
        migrations.AddConstraint(
            model_name='pmomember',
            constraint=models.UniqueConstraint(condition=models.Q(('to_date__isnull', True)), fields=('pmo', 'employee'), name='ux_hr_pmo_members_open_employee'),
        ),
        migrations.AddConstraint(
            model_name='pmomember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('to_date__isnull', True)), fields=('pmo',), name='ux_hr_pmo_members_open_primary'),
        ),
    ]
