# Generated by Django 5.2.7 on 2026-07-21 20:03

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_pmo_pmodepartment_pmomember_pmoposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=64, null=True)),
                ('passport_data', models.TextField(blank=True, null=True)),
                ('inn', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('sro_permit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sro_permit_expiry', models.DateField(blank=True, null=True)),
                ('safety_cert_number', models.CharField(blank=True, max_length=100, null=True)),
                ('safety_cert_expiry', models.DateField(blank=True, null=True)),
                ('employee', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='hr.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
