# Generated by Django 5.2.7 on 2026-07-21 20:21

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_employeecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFileFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('name', models.CharField(max_length=255)),
                ('created_by_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='hr.department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('media_file_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=512)),
                ('file_url', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField(db_default=0, default=0)),
                ('mime_type', models.CharField(db_default='application/octet-stream', default='application/octet-stream', max_length=255)),
                ('uploaded_by_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(db_default='', default='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hr.department')),
                ('file_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='hr.departmentfilefolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareableLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_by_user_id', models.IntegerField(db_index=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('viewer_label', models.CharField(blank=True, max_length=64, null=True)),
                ('watermark_text', models.CharField(blank=True, max_length=128, null=True)),
                ('max_level', models.IntegerField(db_default=3, default=3)),
                ('default_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], db_default='ru', default='ru', max_length=2)),
                ('visible_units', models.JSONField(blank=True, null=True)),
                ('link_type', models.CharField(choices=[('one_time', 'Одноразовая'), ('time_limited', 'Ограничена по времени'), ('permanent_with_expiry', 'Постоянная с истечением')], db_default='one_time', default='one_time', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True, db_index=True, default=True)),
                ('target_type', models.CharField(choices=[('org', 'Оргструктура'), ('employee', 'Карточка сотрудника')], db_default='org', default='org', max_length=16)),
                ('target_employee_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('link_type__in', ['one_time', 'time_limited', 'permanent_with_expiry'])), name='ck_link_type'), models.CheckConstraint(condition=models.Q(('max_level__gte', 1)), name='ck_link_max_level'), models.CheckConstraint(condition=models.Q(('default_language__in', ['ru', 'en'])), name='ck_share_link_default_language'), models.CheckConstraint(condition=models.Q(('target_type__in', ['org', 'employee'])), name='ck_share_link_target_type'), models.CheckConstraint(condition=models.Q(models.Q(('target_employee_id__isnull', True), ('target_type', 'org')), models.Q(('target_employee_id__isnull', False), ('target_type', 'employee')), _connector='OR'), name='ck_share_link_target_consistency')],
            },
        ),
        migrations.CreateModel(
            name='ShareLinkAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('open', 'Открыта'), ('denied_revoked', 'Отказ: отозвана'), ('denied_expired', 'Отказ: истекла'), ('denied_used', 'Отказ: уже использована'), ('denied_unknown', 'Отказ: неизвестный токен'), ('revoked', 'Отозвана'), ('created', 'Создана')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=64, null=True)),
                ('link', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='hr.shareablelink')),
            ],
        ),
        migrations.AddConstraint(
            model_name='departmentfilefolder',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='uq_hr_department_file_folders_department_name'),
        ),
        migrations.AddIndex(
            model_name='sharelinkaudit',
            index=models.Index(fields=['link', 'occurred_at'], name='hr_sharelin_link_id_879d79_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharelinkaudit',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['open', 'denied_revoked', 'denied_expired', 'denied_used', 'denied_unknown', 'revoked', 'created'])), name='ck_share_link_audit_action'),
        ),
    ]
