# Generated by Django 5.2.7 on 2026-08-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_departmentfilefolder_departmentfile_shareablelink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Отклик на вакансию', 'verbose_name_plural': 'Отклики на вакансии'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Запись аудита', 'verbose_name_plural': 'Журнал аудита'},
        ),
        migrations.AlterModelOptions(
            name='calendarday',
            options={'verbose_name': 'День календаря', 'verbose_name_plural': 'Производственный календарь'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='departmentfile',
            options={'verbose_name': 'Файл отдела', 'verbose_name_plural': 'Файлы отделов'},
        ),
        migrations.AlterModelOptions(
            name='departmentfilefolder',
            options={'verbose_name': 'Папка файлов отдела', 'verbose_name_plural': 'Папки файлов отделов'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeecard',
            options={'verbose_name': 'Карточка сотрудника', 'verbose_name_plural': 'Карточки сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeedayoverride',
            options={'verbose_name': 'Исключение по дню', 'verbose_name_plural': 'Исключения по дням'},
        ),
        migrations.AlterModelOptions(
            name='employeedocumentblob',
            options={'verbose_name': 'Файл документа сотрудника', 'verbose_name_plural': 'Файлы документов сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeegroups',
            options={'verbose_name': 'Группа сотрудников', 'verbose_name_plural': 'Группы сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeeshiftassignment',
            options={'verbose_name': 'Назначение смены', 'verbose_name_plural': 'Назначения смен'},
        ),
        migrations.AlterModelOptions(
            name='employeeweektemplate',
            options={'verbose_name': 'Шаблон недели сотрудника', 'verbose_name_plural': 'Шаблоны недели сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='levelthreshold',
            options={'verbose_name': 'Уровень должностей', 'verbose_name_plural': 'Уровни должностей'},
        ),
        migrations.AlterModelOptions(
            name='orgsettings',
            options={'verbose_name': 'Настройка оргструктуры', 'verbose_name_plural': 'Настройки оргструктуры'},
        ),
        migrations.AlterModelOptions(
            name='personnelhistory',
            options={'verbose_name': 'Кадровое событие', 'verbose_name_plural': 'Кадровая история'},
        ),
        migrations.AlterModelOptions(
            name='pmo',
            options={'verbose_name': 'Проектный офис', 'verbose_name_plural': 'Проектные офисы'},
        ),
        migrations.AlterModelOptions(
            name='pmodepartment',
            options={'verbose_name': 'Отдел проектного офиса', 'verbose_name_plural': 'Отделы проектного офиса'},
        ),
        migrations.AlterModelOptions(
            name='pmomember',
            options={'verbose_name': 'Участник проектного офиса', 'verbose_name_plural': 'Участники проектных офисов'},
        ),
        migrations.AlterModelOptions(
            name='pmoposition',
            options={'verbose_name': 'Должность проектного офиса', 'verbose_name_plural': 'Должности проектного офиса'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='positionweightaudit',
            options={'verbose_name': 'Изменение веса должности', 'verbose_name_plural': 'История весов должностей'},
        ),
        migrations.AlterModelOptions(
            name='reportingrelation',
            options={'verbose_name': 'Подчинение', 'verbose_name_plural': 'Подчинения'},
        ),
        migrations.AlterModelOptions(
            name='shareablelink',
            options={'verbose_name': 'Публичная ссылка', 'verbose_name_plural': 'Публичные ссылки'},
        ),
        migrations.AlterModelOptions(
            name='sharelinkaudit',
            options={'verbose_name': 'Обращение по ссылке', 'verbose_name_plural': 'Журнал публичных ссылок'},
        ),
        migrations.AlterModelOptions(
            name='shiftpattern',
            options={'verbose_name': 'Шаблон смены', 'verbose_name_plural': 'Шаблоны смен'},
        ),
        migrations.AlterModelOptions(
            name='staffingposition',
            options={'verbose_name': 'Штатная единица', 'verbose_name_plural': 'Штатное расписание'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'Отметка времени', 'verbose_name_plural': 'Учёт времени'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='weektemplate',
            options={'verbose_name': 'Шаблон недели', 'verbose_name_plural': 'Шаблоны недели'},
        ),
    ]
