# Generated by Django 5.2.7 on 2026-08-18 06:35

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_remove_employeecard_certs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReportingOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('relation_type', models.CharField(choices=[('direct', 'Прямое'), ('functional', 'Функциональное'), ('project', 'Проектное')], db_default='direct', default='direct', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('subordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior_overrides', to='hr.employee')),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_overrides', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Подчинение сотрудника',
                'verbose_name_plural': 'Подчинения сотрудников',
                'constraints': [models.UniqueConstraint(fields=('superior', 'subordinate', 'relation_type'), name='uq_employee_reporting_override'), models.CheckConstraint(condition=models.Q(('superior', models.F('subordinate')), _negated=True), name='ck_no_self_employee_override'), models.CheckConstraint(condition=models.Q(('relation_type__in', ['direct', 'functional', 'project'])), name='ck_employee_override_relation_type'), models.UniqueConstraint(condition=models.Q(('relation_type', 'direct')), fields=('subordinate',), name='ux_employee_override_one_direct_superior')],
            },
        ),
    ]
