# Generated by Django 5.2.7 on 2026-08-24 19:44

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_employeereportingoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityApprover',
            fields=[
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Подтверждающий изменения профиля',
                'verbose_name_plural': 'Подтверждающий изменения профиля',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ck_identity_approver_singleton')],
            },
        ),
        migrations.CreateModel(
            name='IdentityChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('applied', 'Применена'), ('rejected', 'Отклонена')], db_default='pending', default='pending', max_length=16)),
                ('source', models.CharField(choices=[('hr_form', 'Правка в карточке'), ('nightly', 'Найдено ночной сверкой')], db_default='hr_form', default='hr_form', max_length=16)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('decided_by', models.IntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_requests', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Заявка на изменение профиля',
                'verbose_name_plural': 'Заявки на изменение профиля',
            },
        ),
        migrations.CreateModel(
            name='IdentityChangeRequestField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('field', models.CharField(max_length=32)),
                ('proposed_value', models.TextField(blank=True, null=True)),
                ('account_value_at_request', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('apply', 'Применить'), ('reject', 'Отклонить')], max_length=8, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='hr.identitychangerequest')),
            ],
            options={
                'verbose_name': 'Поле заявки на изменение профиля',
                'verbose_name_plural': 'Поля заявок на изменение профиля',
            },
        ),
        migrations.AddConstraint(
            model_name='identitychangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('employee',), name='uq_identity_request_one_pending_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='identitychangerequestfield',
            constraint=models.UniqueConstraint(fields=('request', 'field'), name='uq_identity_request_field'),
        ),
    ]
