"""Expand-шаг: два поля должности для внешней иерархии.

``hr`` — тенантная аппка, её таблицы живут в схемах компаний, поэтому эта
миграция НЕ применяется стартом контейнера (он зовёт ``migrate_shared``).
Схемы компаний доводит ``manage.py migrate_companies`` отдельным шагом
выкатки.

Шаг чисто аддитивный: два столбца с ``db_default``, существующие строки
получают значения без переписывания таблицы, старый код продолжает работать
не зная о них. Разрушающего парного шага у этого изменения нет и не
планируется.

``Position`` входит в ``HOLDING_MODELS``, поэтому сводные представления схемы
``holding`` обязаны быть пересобраны после прогона — это делает сам
``migrate_companies`` (сносит до, собирает после). Пока компании не
догонят друг друга, сводки холдинга не собираются: это известная цена
expand'а по тенантной аппке, см. docs/multi-company-tenancy-design.md §8.
"""

# Generated by Django 5.2.7 on 2026-09-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_sync_identity_dispatch_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='external_hierarchy',
            field=models.CharField(choices=[('inherit', 'Участвует'), ('none', 'Не участвует')], db_default='inherit', default='inherit', max_length=16),
        ),
        migrations.AddField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
