"""Expand-шаг: признак «должность обслуживает дочерние компании».

``hr`` — тенантная аппка, её таблицы живут в схемах компаний, поэтому эта
миграция НЕ применяется стартом контейнера (он зовёт ``migrate_shared``).
Схемы компаний доводит ``manage.py migrate_companies`` отдельным шагом
выкатки.

Шаг чисто аддитивный: один столбец с ``db_default``, существующие строки
получают значение без переписывания таблицы, старый код продолжает работать
не зная о нём. Разрушающего парного шага у этого изменения нет и не
планируется.

``Position`` входит в ``HOLDING_MODELS``, поэтому сводные представления схемы
``holding`` обязаны быть пересобраны после прогона — это делает сам
``migrate_companies`` (сносит до, собирает после). Пока компании не
догонят друг друга, сводки холдинга не собираются: это известная цена
expand'а по тенантной аппке, см. docs/multi-company-tenancy-design.md §8.
"""

# Generated by Django 5.2.7 on 2026-09-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_position_external_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='serves_subsidiaries',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
