"""Expand-шаг без DDL: новое значение choices у ``Department.unit_type``.

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``.
Postgres-ограничения на столбце нет, поэтому шаг сводится к записи в
``django_migrations`` каждой схемы; старый код значение просто не видит.
"""

# Generated by Django 5.2.7 on 2026-09-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_position_serves_subsidiaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='unit_type',
            field=models.CharField(choices=[('department', 'Отдел'), ('division', 'Управление'), ('group', 'Группа'), ('directorate', 'Дирекция')], db_default='department', default='department', max_length=20),
        ),
    ]
