"""Expand-шаг: таблица матрицы замещения (HR-FRM-006), блок E.

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``
отдельным шагом выкатки.

Шаг чисто аддитивный — новая таблица, ни одного существующего столбца не
трогает. ``Substitution`` НЕ входит в ``HOLDING_MODELS`` (``apps/hr/holding.py``):
сводное чтение матрицы замещения по всей группе никем не заказано, а
включение модели в сводки стоит пересборки представлений на каждой выкатке.
"""

# Generated by Django 5.2.7 on 2026-09-16 07:36

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_seed_level_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('primary', 'Основной'), ('reserve', 'Резервный')], db_default='primary', default='primary', max_length=16)),
                ('basis', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='hr.position')),
                ('substitute_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes_in', to='hr.position')),
            ],
            options={
                'verbose_name': 'Замещение',
                'verbose_name_plural': 'Матрица замещения',
                'constraints': [models.CheckConstraint(condition=models.Q(('position', models.F('substitute_position')), _negated=True), name='ck_no_self_substitution'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='ck_substitution_range'), models.CheckConstraint(condition=models.Q(('kind__in', ['primary', 'reserve'])), name='ck_substitution_kind'), models.UniqueConstraint(fields=('position', 'kind', 'valid_from'), name='uq_substitution_start')],
            },
        ),
    ]
