"""Expand-шаг: переименование ограничения дат замещения под конвенцию сторожа.

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``
отдельным шагом выкатки.

``0025`` назвала ограничение ``ck_substitution_range`` — по смыслу верно, но
``apps/core/tests/test_invariants.py::test_date_pairs_table_matches_the_database_constraints``
находит новые пары дат ИМЕННО по маске ``ck_*dates`` (см. четыре уже
существующих: ``ck_site_block_dates``, ``ck_roadmap_planned_dates``,
``ck_engagement_dates``, ``ck_requirement_dates``, ``ck_task_dates`` —
докстринг ``htqweb/date_rules.py``), и ``..._range`` под неё не попадала —
пара ``valid_from``/``valid_to`` была не защищена сторожем. Править ``0025``
на месте нельзя: она уже накатана на dev-схему холдинга, а
``migrate_companies`` откатов не делает — поэтому переименование отдельным
шагом, ``RemoveConstraint`` + ``AddConstraint`` с тем же условием.

Шаг чисто аддитивный по сути (переименование, не смена условия), но
формально DDL: `RemoveConstraint`/`AddConstraint`. Разрушающего парного шага
нет и не планируется.
"""

# Generated by Django 5.2.7 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_substitution'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='substitution',
            name='ck_substitution_range',
        ),
        migrations.AddConstraint(
            model_name='substitution',
            constraint=models.CheckConstraint(
                condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'),
                name='ck_substitution_dates',
            ),
        ),
    ]
