"""Expand-шаг: состояние согласования у строки штатного расписания (блок G).

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``
отдельным шагом выкатки.

Шаг чисто аддитивный: один столбец с ``db_default``, существующие строки
получают «черновик» без переписывания таблицы. ``StaffingPosition`` НЕ
входит в ``HOLDING_MODELS`` — сводное чтение заявок по группе не заказано.
"""

# Generated by Django 5.2.7 on 2026-09-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_rename_substitution_dates_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffingposition',
            name='approval_state',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования'),
        ),
    ]
