"""Expand-шаг: кадровый приказ — строки 5, 6, 7 матрицы HR-FRM-004 (блок G).

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``
отдельным шагом выкатки.

Новая таблица целиком, без затрагивания существующих — чисто аддитивный
шаг. ``PersonnelOrder`` НЕ входит в ``HOLDING_MODELS`` — сводное чтение
приказов по группе не заказано. ``target_company_slug`` — обычная строковая
колонка, не FK: компании живут в схеме ``public``, кадры — в схеме
компании, межаппных FK в платформе нет.
"""

# Generated by Django 5.2.7 on 2026-09-16 16:21

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_staffingposition_approval_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('kind', models.CharField(choices=[('hire', 'Приём'), ('dismiss', 'Увольнение'), ('transfer', 'Перевод')], db_default='hire', db_index=True, default='hire', max_length=16)),
                ('candidate_name', models.CharField(db_default='', default='', max_length=255)),
                ('target_company_slug', models.CharField(blank=True, db_index=True, max_length=63, null=True)),
                ('effective_date', models.DateField()),
                ('salary', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=12)),
                ('basis', models.CharField(db_default='', default='', max_length=255)),
                ('comment', models.TextField(db_default='', default='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel_orders', to='hr.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_orders', to='hr.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel_orders', to='hr.position')),
            ],
            options={
                'verbose_name': 'Кадровый приказ',
                'verbose_name_plural': 'Кадровые приказы',
                'constraints': [models.CheckConstraint(condition=models.Q(('employee__isnull', False), models.Q(('candidate_name', ''), _negated=True), _connector='OR'), name='ck_personnel_order_subject')],
            },
        ),
    ]
