"""Expand-шаг: премия и дисциплинарное взыскание — строки 8, 9 матрицы
HR-FRM-004 (блок G).

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``
отдельным шагом выкатки.

Две новые таблицы целиком, без затрагивания существующих — чисто аддитивный
шаг. Ни ``Bonus``, ни ``Reprimand`` не входят в ``HOLDING_MODELS`` — сводное
чтение по группе не заказано ни для того, ни для другого.
``ck_bonus_amount_positive`` — единственное ограничение блока G на уровне
БД: «премия на 0 ₸» — ошибка ввода, а не решение, и ловить её нужно раньше,
чем дисциплина согласующего.
"""

# Generated by Django 5.2.7 on 2026-09-16 16:31

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_personnelorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reprimand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('severity', models.CharField(choices=[('remark', 'Замечание'), ('reprimand', 'Выговор'), ('severe', 'Строгий выговор')], db_default='remark', db_index=True, default='remark', max_length=16)),
                ('event_date', models.DateField()),
                ('reason', models.TextField()),
                ('basis', models.CharField(db_default='', default='', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprimands', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Дисциплинарное взыскание',
                'verbose_name_plural': 'Дисциплинарные взыскания',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('kind', models.CharField(choices=[('kpi', 'По KPI'), ('one_time', 'Разовая'), ('annual', 'Годовая')], db_default='one_time', default='one_time', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(db_default='', default='', max_length=32)),
                ('basis', models.CharField(db_default='', default='', max_length=255)),
                ('comment', models.TextField(db_default='', default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Премия',
                'verbose_name_plural': 'Премии',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_bonus_amount_positive')],
            },
        ),
    ]
