"""Expand-шаг: заявление на отпуск и командировка — строки 10б, 10в матрицы
HR-FRM-004 (блок G, задача 4).

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``
отдельным шагом выкатки.

Две новые таблицы целиком, без затрагивания существующих — чисто аддитивный
шаг. Ни ``LeaveRequest``, ни ``BusinessTrip`` не входят в ``HOLDING_MODELS``
— сводное чтение по группе не заказано ни для того, ни для другого.

Обе модели используют одну и ту же пару дат ``date_from``/``date_to``
(платформенное правило — ``htqweb/date_rules.py::DATE_PAIRS``), поэтому оба
ограничения — ``ck_leaverequest_dates`` и ``ck_businesstrip_dates`` — той же
формы, что и у остальных пар дат в платформе: конец не раньше начала.
"""

# Generated by Django 5.2.7 on 2026-09-16 16:45

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_bonus_reprimand'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('destination', models.CharField(max_length=255)),
                ('country', models.CharField(db_default='', default='', max_length=2)),
                ('purpose', models.CharField(db_default='', default='', max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('estimated_cost', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=12)),
                ('basis', models.CharField(db_default='', default='', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trips', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Командировка',
                'verbose_name_plural': 'Командировки',
                'constraints': [models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='ck_businesstrip_dates')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('kind', models.CharField(choices=[('annual', 'Ежегодный оплачиваемый'), ('unpaid', 'Без содержания'), ('sick', 'По болезни'), ('study', 'Учебный'), ('parental', 'По уходу за ребёнком')], db_default='annual', db_index=True, default='annual', max_length=16)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('basis', models.CharField(db_default='', default='', max_length=255)),
                ('comment', models.TextField(db_default='', default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Заявление на отпуск',
                'verbose_name_plural': 'Заявления на отпуск',
                'constraints': [models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='ck_leaverequest_dates')],
            },
        ),
    ]
