"""Expand-шаг: годовой график отпусков — строка 10, часть а матрицы
HR-FRM-004 (блок G, задача 5).

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``
отдельным шагом выкатки.

Две новые таблицы целиком, без затрагивания существующих — чисто аддитивный
шаг. Согласуется ``VacationSchedule`` целиком (контейнер), а не отдельная
строка ``VacationScheduleLine`` — поэтому ``SIGNOFF_SUBJECT_TYPE`` и
регистрация в signoff есть только у графика, строка обычная ``HrBase``.

Строка использует ту же пару дат ``date_from``/``date_to`` (платформенное
правило — ``htqweb/date_rules.py::DATE_PAIRS``, строка уже занята задачей 4),
поэтому ограничение той же формы, что и у остальных пар дат в платформе:
``ck_vacationscheduleline_dates`` — конец не раньше начала.

Ни ``VacationSchedule``, ни ``VacationScheduleLine`` не входят в
``HOLDING_MODELS`` — сводное чтение по группе не заказано.
"""

# Generated by Django 5.2.7 on 2026-09-16 17:50

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_leaverequest_businesstrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('year', models.IntegerField(unique=True)),
                ('basis', models.CharField(db_default='', default='', max_length=255)),
                ('comment', models.TextField(db_default='', default='')),
            ],
            options={
                'verbose_name': 'График отпусков',
                'verbose_name_plural': 'Графики отпусков',
            },
        ),
        migrations.CreateModel(
            name='VacationScheduleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacation_schedule_lines', to='hr.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.vacationschedule')),
            ],
            options={
                'verbose_name': 'Строка графика отпусков',
                'verbose_name_plural': 'Строки графика отпусков',
                'constraints': [models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='ck_vacationscheduleline_dates')],
            },
        ),
    ]
