"""Expand-шаг: локальные нормативные акты и должностные инструкции —
строки 3, 4 матрицы HR-FRM-004 (блок G, задача 6).

``hr`` — тенантная аппка: миграция НЕ применяется стартом контейнера
(``migrate_shared``), схемы компаний доводит ``manage.py migrate_companies``
отдельным шагом выкатки.

Две новые таблицы целиком, без затрагивания существующих — чисто аддитивный
шаг. Обе модели версионируемые и без пары дат (``effective_from`` — одна
дата, не пара ``date_from``/``date_to``, поэтому ``htqweb/date_rules.py``
здесь не затрагивается). Уникальность версии — в паре с предметом, а не сама
по себе: ``uq_policy_version`` на (``kind``, ``version``) у акта,
``uq_job_description_version`` на (``position``, ``version``) у инструкции —
тот же номер версии у другого вида акта / другой должности законен.

Ни ``Policy``, ни ``JobDescription`` не входят в ``HOLDING_MODELS`` — сводное
чтение по группе не заказано (как и у остальных предметов блока G).
"""

# Generated by Django 5.2.7 on 2026-09-16 18:02

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_vacationschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('kind', models.CharField(choices=[('regulation', 'Положение'), ('policy', 'Политика'), ('instruction', 'Инструкция'), ('order', 'Приказ')], db_default='policy', default='policy', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=32)),
                ('effective_from', models.DateField()),
                ('file_key', models.CharField(db_default='', default='', max_length=500)),
                ('comment', models.TextField(db_default='', default='')),
            ],
            options={
                'verbose_name': 'Локальный нормативный акт',
                'verbose_name_plural': 'Локальные нормативные акты',
                'constraints': [models.UniqueConstraint(fields=('kind', 'version'), name='uq_policy_version')],
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('version', models.CharField(max_length=32)),
                ('effective_from', models.DateField()),
                ('body', models.TextField(db_default='', default='')),
                ('file_key', models.CharField(db_default='', default='', max_length=500)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to='hr.position')),
            ],
            options={
                'verbose_name': 'Должностная инструкция',
                'verbose_name_plural': 'Должностные инструкции',
                'constraints': [models.UniqueConstraint(fields=('position', 'version'), name='uq_job_description_version')],
            },
        ),
    ]
