"""Expand-шаг: заявка на изменение оргструктуры — строка 1 матрицы
HR-FRM-004 (блок G, задача 7, последний из десяти предметов).

Одна таблица целиком, без затрагивания существующих — чисто аддитивный шаг.
``department`` — nullable ``SET_NULL`` (как ``PersonnelOrder.employee``):
удаление подразделения не должно уносить заявку, а «создать подразделение»
подразделения ещё не имеет. Утверждение этого предмета ничего не применяет
к дереву оргструктуры (решение 6 плана блока G) — в ``approval_hooks`` для
него нет ``on_approved``, изменение вносит кадровик руками.

``OrgChangeRequest`` не входит в ``HOLDING_MODELS`` — сводное чтение по
группе не заказано (как и у остальных предметов блока G).
"""

# Generated by Django 5.2.7 on 2026-09-16 18:12

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0032_policy_jobdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('kind', models.CharField(choices=[('create_unit', 'Создать подразделение'), ('rename_unit', 'Переименовать подразделение'), ('move_unit', 'Перенести подразделение'), ('close_unit', 'Закрыть подразделение'), ('create_position', 'Ввести должность'), ('close_position', 'Сократить должность'), ('other', 'Другое')], db_default='other', default='other', max_length=20)),
                ('description', models.TextField()),
                ('headcount_delta', models.IntegerField(db_default=0, default=0)),
                ('effective_date', models.DateField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_change_requests', to='hr.department')),
            ],
            options={
                'verbose_name': 'Заявка на изменение оргструктуры',
                'verbose_name_plural': 'Заявки на изменение оргструктуры',
            },
        ),
    ]
