# Generated by Django 5.2.7 on 2026-09-16 20:41

"""Расширение ``PersonnelHistory.order_number`` с 64 до 255.

Expand в чистом виде: varchar(64) → varchar(255) Postgres делает правкой
каталога, без переписывания таблицы и без долгой блокировки, старые строки
остаются валидными, читатели поля не ломаются.

Зачем: утверждённый кадровый приказ (блок G, единственный автоматический
эффект) пишет в эту колонку своё основание — ``PersonnelOrder.basis``,
объявленное как 255. На обычном тексте вида «Приказ Генерального директора
№ 123-К от 01.10.2026 «О приёме на работу»» запись падала ``DataError``, а
поскольку колбэк идёт ВНУТРИ транзакции движка согласования, вместе с ней
откатывалось решение согласующего: приказ становилось невозможно утвердить
вовсе, а пользователь видел 500.

Колонка тенантная — применяется через ``migrate_companies``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_orgchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelhistory',
            name='order_number',
            field=models.CharField(db_default='', default='', max_length=255),
        ),
    ]
