# Generated by Django 5.2.7 on 2026-09-16 21:05

"""Связь записи кадровой истории с приказом, который её породил.

Expand: nullable-колонка со своим уникальным индексом, старые строки
остаются с NULL и не трогаются (``OneToOne`` с ``null=True`` в Postgres
допускает сколько угодно NULL — единственность требуется только от
заполненных).

Зачем: утверждённый кадровый приказ пишет историю (единственный
автоматический эффект блока G), и утвердить один и тот же приказ можно
дважды — согласующий возвращает завершённый процесс на доработку, приказ
правят и отправляют заново. Раньше колбэк искал прежнюю запись по данным
события, поэтому правка даты или должности оставляла УСТАРЕВШУЮ запись
рядом с новой. Эта связь делает «одна запись истории на приказ» правилом
БД, а не договорённостью колбэка.

Тенантная аппка — применяется через ``migrate_companies``.
"""

import django.db.models.deletion

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_personnelhistory_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelhistory',
            name='source_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entry', to='hr.personnelorder'),
        ),
    ]
