# Generated by Django 5.2.7 on 2026-09-17 05:53

"""Читатели сводных представлений холдинга для домена hr (блок H).

Четыре ``CreateModel`` с ``managed=False`` НЕ выполняют DDL: они лишь
записывают состояние миграций для ``HoldingEmployee``/``HoldingDepartment``/
``HoldingPosition``/``HoldingStaffingPosition`` (apps/hr/holding_models.py),
чтобы ``makemigrations --check`` оставался чист. Физические таблицы под
именами ``hr_employee``/``hr_department``/``hr_position``/
``hr_staffingposition`` в схеме ``holding`` создаёт (и пересобирает)
``apps.companies.services.holding_views``, а не эта миграция.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0035_personnelhistory_source_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hr_department',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoldingEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=63)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('department_id', models.IntegerField(null=True)),
                ('position_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'hr_employee',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoldingPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=63)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'hr_position',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoldingStaffingPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=63)),
                ('headcount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'hr_staffingposition',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
