# Generated by Django 5.2.7 on 2026-09-17 06:26

"""Записать base_manager_name="objects" в состояние миграций (блок H).

Round 1 ревью добавил ``base_manager_name = "objects"`` в
``HoldingRow.Meta`` (apps/hr/holding_models.py): без него Django заводит
``Model._base_manager`` как голый ``models.Manager()``, которым пользуются
``refresh_from_db()`` и related-дескрипторы, — и он обходил бы
``HoldingManager.get_queryset()``, то есть весь сторож контекста холдинга,
ради которого эта задача существует.

``base_manager_name`` — отслеживаемая опция ``Meta`` (``ALTER_OPTION_KEYS``
в ``django/db/migrations/operations/models.py``), поэтому её смена требует
отдельной миграции, даже когда модель ``managed=False``. Четыре
``AlterModelOptions`` ниже, как и ``CreateModel`` в 0036, НЕ выполняют DDL
вовсе — физические объекты этих моделей создаёт и пересобирает
``apps.companies.services.holding_views``, а не Django. Миграция нужна
ровно затем, чтобы ``makemigrations --check`` оставался чист.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0036_holding_readers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holdingdepartment',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='holdingemployee',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='holdingposition',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='holdingstaffingposition',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
    ]
