# Generated by Django 5.2.7 on 2026-09-26 17:51
"""Временный исполнитель должности на период (мастер-план БЗО, B1.1, D-22).

Новая таблица — expand-шаг без правки существующих; в схемы компаний
доводится ``manage.py migrate_companies`` (старт контейнера зовёт только
``migrate_shared``).
"""

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0037_holding_readers_base_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActingAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('basis', models.CharField(max_length=255)),
                ('assigned_by_id', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acting_assignments', to='hr.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acting_assignments', to='hr.position')),
            ],
            options={
                'verbose_name': 'Временный исполнитель должности',
                'verbose_name_plural': 'Временные исполнители должностей',
                'ordering': ['-date_from', '-id'],
                'indexes': [models.Index(fields=['position', 'date_from', 'date_to'], name='ix_acting_position_period')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='ck_acting_assignment_dates')],
            },
        ),
    ]
