# Generated by Django 5.2.7 on 2026-08-18 04:49

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_by_name', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('peak_participants', models.PositiveIntegerField(db_default=0, default=0)),
                ('recording_state', models.CharField(choices=[('none', 'Не велась'), ('recording', 'Идёт запись'), ('processing', 'Обработка'), ('ready', 'Готова'), ('failed', 'Ошибка'), ('purged', 'Удалена по сроку')], db_default='none', default='none', max_length=16)),
                ('transcript_state', models.CharField(choices=[('pending', 'Ожидает распознавания'), ('processing', 'Распознаётся'), ('ready', 'Готов'), ('failed', 'Ошибка'), ('skipped', 'Пропущен')], db_default='pending', default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, db_default='', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['expires_at', 'recording_state'], name='conf_session_retention_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('room_id',), name='conference_one_open_session_per_room')],
            },
        ),
        migrations.CreateModel(
            name='ConferenceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('peer_id', models.CharField(max_length=64)),
                ('is_guest', models.BooleanField(db_default=False, default=False)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('joined_offset_ms', models.PositiveIntegerField(db_default=0, default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='conference.conferencesession')),
            ],
            options={
                'verbose_name': 'Участник конференции',
                'verbose_name_plural': 'Участники конференции',
                'ordering': ('joined_at',),
            },
        ),
        migrations.CreateModel(
            name='ConferenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('join', 'Вошёл'), ('leave', 'Вышел'), ('camera_on', 'Включил камеру'), ('camera_off', 'Выключил камеру'), ('chat', 'Сообщение в чате'), ('recording_started', 'Запись начата'), ('recording_stopped', 'Запись остановлена')], max_length=24)),
                ('at_ms', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='conference.conferenceparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conference.conferencesession')),
            ],
            options={
                'verbose_name': 'Событие конференции',
                'verbose_name_plural': 'События конференции',
                'ordering': ('at_ms', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConferenceTranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=255)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='conference.conferenceparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='conference.conferencesession')),
            ],
            options={
                'verbose_name': 'Реплика протокола',
                'verbose_name_plural': 'Протокол',
                'ordering': ('start_ms', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConferenceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('composed', 'Сведённая запись'), ('peer_audio', 'Аудиодорожка участника'), ('peer_video', 'Видеодорожка участника'), ('poster', 'Кадр-заставка')], max_length=16)),
                ('storage_path', models.CharField(max_length=1024)),
                ('size', models.BigIntegerField(db_default=0, default=0)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('mime', models.CharField(db_default='video/mp4', default='video/mp4', max_length=100)),
                ('started_offset_ms', models.PositiveIntegerField(db_default=0, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='conference.conferenceparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='conference.conferencesession')),
            ],
            options={
                'verbose_name': 'Файл записи',
                'verbose_name_plural': 'Файлы записей',
                'ordering': ('kind', 'started_offset_ms'),
                'indexes': [models.Index(fields=['session', 'kind'], name='conf_recording_kind_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='conferenceparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'peer_id'), name='conference_participant_unique_peer'),
        ),
        migrations.AddIndex(
            model_name='conferenceevent',
            index=models.Index(fields=['session', 'at_ms'], name='conf_event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencetranscriptsegment',
            index=models.Index(fields=['session', 'start_ms'], name='conf_segment_time_idx'),
        ),
    ]
