# Generated by Django 5.2.7 on 2026-08-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesession',
            name='calendar_event_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
