import React from 'react';

export const lazyPages = {
  NotFound: React.lazy(() => import('@/pages/NotFound')),
  RequireAuth: React.lazy(() => import('@/components/RequireAuth')),
  BottomNav: React.lazy(() => import('@/components/BottomNav').then((module) => ({ default: module.BottomNav }))),
  Toaster: React.lazy(() => import('@/components/ui/toaster').then((module) => ({ default: module.Toaster }))),
  Sonner: React.lazy(() => import('@/components/ui/sonner').then((module) => ({ default: module.Toaster }))),

  Projects: React.lazy(() => import('@/pages/Projects')),
  Services: React.lazy(() => import('@/pages/Services')),
  Contacts: React.lazy(() => import('@/pages/Contacts')),
  News: React.lazy(() => import('@/pages/News')),
  NewsDetail: React.lazy(() => import('@/pages/NewsDetail')),
  Login: React.lazy(() => import('@/pages/Login')),
  Register: React.lazy(() => import('@/pages/Register')),
  MyProfile: React.lazy(() => import('@/pages/MyProfile')),
  MyEmployeeCard: React.lazy(() => import('@/pages/MyEmployeeCard')),
  Settings: React.lazy(() => import('@/pages/Settings')),
  Messenger: React.lazy(() => import('@/features/messenger/MessengerPage')),
  NotificationsHistory: React.lazy(() => import('@/pages/NotificationsHistory')),

  ContractsOverview: React.lazy(() => import('@/pages/contracts/ContractsOverview')),
  ContractsBudgetList: React.lazy(() => import('@/pages/contracts/BudgetList')),
  ContractsBudgetCreate: React.lazy(() => import('@/pages/contracts/BudgetCreate')),
  ContractsBudgetDetail: React.lazy(() => import('@/pages/contracts/BudgetDetail')),
  ContractsCounterpartyList: React.lazy(() => import('@/pages/contracts/CounterpartyList')),
  ContractsCounterpartyCreate: React.lazy(() => import('@/pages/contracts/CounterpartyCreate')),
  ContractsCounterpartyDetail: React.lazy(() => import('@/pages/contracts/CounterpartyDetail')),
  ContractsAgreementList: React.lazy(() => import('@/pages/contracts/AgreementList')),
  ContractsAgreementCreate: React.lazy(() => import('@/pages/contracts/AgreementCreate')),
  ContractsAgreementDetail: React.lazy(() => import('@/pages/contracts/AgreementDetail')),

  // Универсальное согласование (apps.signoff). Не путать с Requests* —
  // те страницы обслуживают apps.approvals, другой домен.
  SignoffInbox: React.lazy(() => import('@/pages/signoff/SignoffInbox')),
  SignoffProcessList: React.lazy(() => import('@/pages/signoff/ProcessList')),
  SignoffProcessDetail: React.lazy(() => import('@/pages/signoff/ProcessDetail')),
  SignoffRouteList: React.lazy(() => import('@/pages/signoff/RouteList')),
  SignoffRouteEditor: React.lazy(() => import('@/pages/signoff/RouteEditor')),

  AdminNews: React.lazy(() => import('@/pages/AdminNews')),
  AdminContacts: React.lazy(() => import('@/pages/AdminContacts')),
  HRProjects: React.lazy(() => import('@/pages/hr/HRProjects')),
  AdminUsers: React.lazy(() => import('@/pages/AdminUsers')),
  AdminRegistrations: React.lazy(() => import('@/pages/AdminRegistrations')),
  AdminChats: React.lazy(() => import('@/pages/AdminChats')),
  AdminMailboxes: React.lazy(() => import('@/pages/AdminMailboxes')),
  AdminInfrastructure: React.lazy(() => import('@/pages/AdminInfrastructure')),

  HREmployees: React.lazy(() => import('@/pages/hr/HREmployees')),
  HREmployeeCard: React.lazy(() => import('@/pages/hr/HREmployeeCard')),
  HRDepartments: React.lazy(() => import('@/pages/hr/HRDepartments')),
  HRTimeTracking: React.lazy(() => import('@/pages/hr/HRTimeTracking')),
  HRRecruitment: React.lazy(() => import('@/pages/hr/HRRecruitment')),
  HRDocuments: React.lazy(() => import('@/pages/hr/HRDocuments')),
  HRLogs: React.lazy(() => import('@/pages/hr/HRLogs')),
  HRHistory: React.lazy(() => import('@/pages/hr/HRHistory')),
  HRArchive: React.lazy(() => import('@/pages/hr/HRArchive')),
  HRAccounts: React.lazy(() => import('@/pages/hr/HRAccounts')),
  HRRoadmap: React.lazy(() => import('@/pages/hr/HRRoadmap')),
  HRRoadmapDetail: React.lazy(() => import('@/pages/hr/HRRoadmapDetail')),
  HRDailyReports: React.lazy(() => import('@/pages/hr/HRDailyReports')),
  HRProjectStaffReports: React.lazy(() => import('@/pages/hr/HRProjectStaffReports')),
  HRProjectPlanFact: React.lazy(() => import('@/pages/hr/HRProjectPlanFact')),
  HRReports: React.lazy(() => import('@/pages/hr/HRReports')),
  HRResourceSchedule: React.lazy(() => import('@/pages/hr/HRResourceSchedule')),
  HREquipment: React.lazy(() => import('@/pages/hr/HREquipment')),
  HRSites: React.lazy(() => import('@/pages/hr/HRSites')),
  HRContractors: React.lazy(() => import('@/pages/hr/HRContractors')),
  HROrgChart: React.lazy(() => import('@/pages/hr/HROrgChart')),
  HRPMO: React.lazy(() => import('@/pages/hr/HRPMO')),
  HRShareLinks: React.lazy(() => import('@/pages/hr/HRShareLinks')),
  HRPositions: React.lazy(() => import('@/pages/hr/HRPositions')),
  HRAccessLevels: React.lazy(() => import('@/pages/hr/HRAccessLevels')),
  // Standalone-обёртки (HRLayout вокруг голого фрагмента-вкладки) — по
  // прямому URL эти страницы раньше открывались без шапки и навигации,
  // см. src/pages/hr/recruitmentStandalone.tsx.
  HRVacancies: React.lazy(() => import('@/pages/hr/recruitmentStandalone').then(m => ({ default: m.HRVacanciesPage }))),
  HRApplications: React.lazy(() => import('@/pages/hr/recruitmentStandalone').then(m => ({ default: m.HRApplicationsPage }))),
  HROffers: React.lazy(() => import('@/pages/hr/recruitmentStandalone').then(m => ({ default: m.HROffersPage }))),
  PublicOrgView: React.lazy(() => import('@/pages/public/PublicOrgView')),
  PublicEmployeeView: React.lazy(() => import('@/pages/public/PublicEmployeeView')),
  HRCalendar: React.lazy(() => import('@/pages/Calendar')),
  HRProductionCalendar: React.lazy(() => import('@/pages/hr/HRProductionCalendar')),
  HRStaffing: React.lazy(() => import('@/pages/hr/HRStaffing')),
  DepartmentFiles: React.lazy(() => import('@/pages/DepartmentFiles')),
  ConferencePage: React.lazy(() => import('@/pages/ConferencePage')),
  ConferenceJoin: React.lazy(() => import('@/pages/ConferenceJoin')),
  ConferenceHistory: React.lazy(() => import('@/pages/conference/ConferenceHistory')),
  ConferenceSessionDetail: React.lazy(
    () => import('@/pages/conference/ConferenceSessionDetail'),
  ),

  TaskRouter: React.lazy(() => import('@/components/tasks/TaskRouter').then((module) => ({ default: module.TaskRouter }))),
  TaskDetailRouter: React.lazy(() => import('@/components/tasks/TaskDetailRouter').then((module) => ({ default: module.TaskDetailRouter }))),

  EmailInbox: React.lazy(() => import('@/pages/Email/EmailPage')),
  OAuthCallbackPage: React.lazy(() => import('@/pages/Email/OAuthCallbackPage')),

  RequestsPage: React.lazy(() => import('@/features/requests/pages/RequestsPage')),
  RequestDetailPage: React.lazy(() => import('@/features/requests/pages/RequestDetailPage')),
  NewRequestPage: React.lazy(() => import('@/features/requests/pages/NewRequestPage')),
  RequestsProjectsPage: React.lazy(() => import('@/features/requests/pages/ProjectsPage')),
  RequestsTemplatesPage: React.lazy(() => import('@/features/requests/pages/TemplatesPage')),
  RequestsTemplateEditorPage: React.lazy(() => import('@/features/requests/pages/TemplateEditorPage')),
  RequestsStatsPage: React.lazy(() => import('@/features/requests/pages/StatsPage')),
  RequestsMyStatsPage: React.lazy(() => import('@/features/requests/pages/MyStatsPage')),
  RequestsReferencePage: React.lazy(() => import('@/features/requests/pages/ReferenceSourcesPage')),
  RequestsDataPage: React.lazy(() => import('@/features/requests/pages/DataManagementPage')),
};
