import React from 'react';

export const lazyPages = {
  NotFound: React.lazy(() => import('@/pages/NotFound')),
  RequireAuth: React.lazy(() => import('@/components/RequireAuth')),
  BottomNav: React.lazy(() => import('@/components/BottomNav').then((module) => ({ default: module.BottomNav }))),
  Toaster: React.lazy(() => import('@/components/ui/toaster').then((module) => ({ default: module.Toaster }))),
  Sonner: React.lazy(() => import('@/components/ui/sonner').then((module) => ({ default: module.Toaster }))),

  Projects: React.lazy(() => import('@/pages/Projects')),
  Services: React.lazy(() => import('@/pages/Services')),
  DesignPreview: React.lazy(() => import('@/pages/DesignPreview')),
  Contacts: React.lazy(() => import('@/pages/Contacts')),
  News: React.lazy(() => import('@/pages/News')),
  NewsDetail: React.lazy(() => import('@/pages/NewsDetail')),
  Login: React.lazy(() => import('@/pages/Login')),
  Register: React.lazy(() => import('@/pages/Register')),
  MyProfile: React.lazy(() => import('@/pages/MyProfile')),
  Settings: React.lazy(() => import('@/pages/Settings')),
  Messenger: React.lazy(() => import('@/features/messenger/MessengerPage')),
  NotificationsHistory: React.lazy(() => import('@/pages/NotificationsHistory')),

  ContractsOverview: React.lazy(() => import('@/pages/contracts/ContractsOverview')),
  ContractsBudgetList: React.lazy(() => import('@/pages/contracts/BudgetList')),
  ContractsBudgetCreate: React.lazy(() => import('@/pages/contracts/BudgetCreate')),
  ContractsCounterpartyList: React.lazy(() => import('@/pages/contracts/CounterpartyList')),
  ContractsCounterpartyCreate: React.lazy(() => import('@/pages/contracts/CounterpartyCreate')),
  ContractsAgreementList: React.lazy(() => import('@/pages/contracts/AgreementList')),
  ContractsAgreementCreate: React.lazy(() => import('@/pages/contracts/AgreementCreate')),

  AdminNews: React.lazy(() => import('@/pages/AdminNews')),
  AdminContacts: React.lazy(() => import('@/pages/AdminContacts')),
  AdminProjects: React.lazy(() => import('@/pages/AdminProjects')),
  AdminUsers: React.lazy(() => import('@/pages/AdminUsers')),
  AdminRegistrations: React.lazy(() => import('@/pages/AdminRegistrations')),
  AdminChats: React.lazy(() => import('@/pages/AdminChats')),
  AdminMailboxes: React.lazy(() => import('@/pages/AdminMailboxes')),
  AdminInfrastructure: React.lazy(() => import('@/pages/AdminInfrastructure')),

  HREmployees: React.lazy(() => import('@/pages/hr/HREmployees')),
  HREmployeeCard: React.lazy(() => import('@/pages/hr/HREmployeeCard')),
  HRDepartments: React.lazy(() => import('@/pages/hr/HRDepartments')),
  HRTimeTracking: React.lazy(() => import('@/pages/hr/HRTimeTracking')),
  HRRecruitment: React.lazy(() => import('@/pages/hr/HRRecruitment')),
  HRDocuments: React.lazy(() => import('@/pages/hr/HRDocuments')),
  HRLogs: React.lazy(() => import('@/pages/hr/HRLogs')),
  HRHistory: React.lazy(() => import('@/pages/hr/HRHistory')),
  HRArchive: React.lazy(() => import('@/pages/hr/HRArchive')),
  HRAccounts: React.lazy(() => import('@/pages/hr/HRAccounts')),
  HRRoadmap: React.lazy(() => import('@/pages/hr/HRRoadmap')),
  HRReports: React.lazy(() => import('@/pages/hr/HRReports')),
  HRResourceSchedule: React.lazy(() => import('@/pages/hr/HRResourceSchedule')),
  HREquipment: React.lazy(() => import('@/pages/hr/HREquipment')),
  HROrgChart: React.lazy(() => import('@/pages/hr/HROrgChart')),
  HRPMO: React.lazy(() => import('@/pages/hr/HRPMO')),
  HRShareLinks: React.lazy(() => import('@/pages/hr/HRShareLinks')),
  HRPositions: React.lazy(() => import('@/pages/hr/HRPositions')),
  HRLevelsAdmin: React.lazy(() => import('@/pages/hr/HRLevelsAdmin')),
  HRAccessLevels: React.lazy(() => import('@/pages/hr/HRAccessLevels')),
  HRVacancies: React.lazy(() => import('@/pages/hr/HRVacancies')),
  HRApplications: React.lazy(() => import('@/pages/hr/HRApplications')),
  HROffers: React.lazy(() => import('@/pages/hr/HROffers')),
  PublicOrgView: React.lazy(() => import('@/pages/public/PublicOrgView')),
  PublicEmployeeView: React.lazy(() => import('@/pages/public/PublicEmployeeView')),
  HRCalendar: React.lazy(() => import('@/pages/Calendar')),
  HRProductionCalendar: React.lazy(() => import('@/pages/hr/HRProductionCalendar')),
  HRStaffing: React.lazy(() => import('@/pages/hr/HRStaffing')),
  DepartmentFiles: React.lazy(() => import('@/pages/DepartmentFiles')),
  ConferencePage: React.lazy(() => import('@/pages/ConferencePage')),

  TaskRouter: React.lazy(() => import('@/components/tasks/TaskRouter').then((module) => ({ default: module.TaskRouter }))),
  TaskDetailRouter: React.lazy(() => import('@/components/tasks/TaskDetailRouter').then((module) => ({ default: module.TaskDetailRouter }))),

  EmailInbox: React.lazy(() => import('@/pages/Email/EmailPage')),
  OAuthCallbackPage: React.lazy(() => import('@/pages/Email/OAuthCallbackPage')),

  RequestsPage: React.lazy(() => import('@/features/requests/pages/RequestsPage')),
  RequestDetailPage: React.lazy(() => import('@/features/requests/pages/RequestDetailPage')),
  NewRequestPage: React.lazy(() => import('@/features/requests/pages/NewRequestPage')),
  RequestsProjectsPage: React.lazy(() => import('@/features/requests/pages/ProjectsPage')),
  RequestsTemplatesPage: React.lazy(() => import('@/features/requests/pages/TemplatesPage')),
  RequestsTemplateEditorPage: React.lazy(() => import('@/features/requests/pages/TemplateEditorPage')),
  RequestsStatsPage: React.lazy(() => import('@/features/requests/pages/StatsPage')),
  RequestsMyStatsPage: React.lazy(() => import('@/features/requests/pages/MyStatsPage')),
  RequestsReferencePage: React.lazy(() => import('@/features/requests/pages/ReferenceSourcesPage')),
  RequestsDataPage: React.lazy(() => import('@/features/requests/pages/DataManagementPage')),
};
