# Generated by Django 5.2.7 on 2026-09-26 19:34

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('project', 'Проект'), ('company_overhead', 'Общие расходы компании')], db_default='project', default='project', max_length=24)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт'), ('archived', 'Архив')], db_default='active', default='active', max_length=16)),
                ('country_code', models.CharField(max_length=2)),
                ('manager_user_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_counterparty_id', models.CharField(blank=True, default='', max_length=64)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('ext_1c_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.project')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
                'constraints': [models.UniqueConstraint(fields=('project', 'user_id'), name='uq_project_member')],
            },
        ),
    ]
