# Generated by Django 5.2.7 on 2026-10-05 19:22

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_ext_1c_lower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('default_part', models.CharField(choices=[('office', 'Офис'), ('site', 'Объект')], db_default='office', default='office', max_length=8)),
                ('sort_order', models.IntegerField(db_default=0, default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Проектная роль',
                'verbose_name_plural': 'Проектные роли',
                'ordering': ('level', 'sort_order', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 4)), name='ck_project_role_level')],
            },
        ),
        migrations.CreateModel(
            name='ProjectSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part', models.CharField(choices=[('office', 'Офис'), ('site', 'Объект')], max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('planned_headcount', models.PositiveSmallIntegerField(db_default=1, default=1)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='project.projectslot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='project.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='project.projectrole')),
            ],
            options={
                'verbose_name': 'Место в структуре проекта',
                'verbose_name_plural': 'Места в структуре проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(db_index=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='project.projectslot')),
            ],
            options={
                'verbose_name': 'Назначение на проекте',
                'verbose_name_plural': 'Назначения на проекте',
            },
        ),
        migrations.AddConstraint(
            model_name='projectslot',
            constraint=models.CheckConstraint(condition=models.Q(('planned_headcount__gte', 1)), name='ck_project_slot_planned'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__isnull', True), ('date_to__gte', models.F('date_from')), _connector='OR'), name='ck_project_assignment_dates'),
        ),
    ]
