# Generated by Django 5.2.7 on 2026-09-26 16:32
"""Файловая подсистема ТЗ §21: справочник «Типы файлов», ``file_object`` и
журнал файловых операций.

Строк справочника здесь нет: их заводит каждый владелец своей миграцией —
подсистема не знает ни одного владельца. Ключ владельца — строка
(``owner_id``, мастер-план БЗО D-05: документы модуля адресуются UUID).
"""

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('formats', models.JSONField(default=list)),
                ('max_mb', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(db_default=0, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Тип файла',
                'verbose_name_plural': 'Типы файлов',
                'ordering': ['owner_type', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('owner_type', models.CharField(max_length=64)),
                ('owner_id', models.CharField(max_length=64)),
                ('event', models.CharField(max_length=32)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('file_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Событие файла',
                'verbose_name_plural': 'Журнал файлов',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner_type', 'owner_id', 'company_slug', 'created_at'], name='ix_file_event_owner')],
            },
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('owner_type', models.CharField(max_length=64)),
                ('owner_id', models.CharField(max_length=64)),
                ('document_id', models.UUIDField(db_index=True)),
                ('version_no', models.PositiveIntegerField()),
                ('is_replaced', models.BooleanField(db_default=False, default=False)),
                ('name', models.CharField(max_length=512)),
                ('mime', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('media_file_id', models.CharField(max_length=64, unique=True)),
                ('uploaded_by_id', models.IntegerField(db_index=True)),
                ('uploaded_by_name', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('uploaded_by_department_id', models.IntegerField(blank=True, null=True)),
                ('uploaded_by_department_name', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('idempotency_key', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_id', models.IntegerField(blank=True, null=True)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.fileobject')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.filetype')),
            ],
            options={
                'verbose_name': 'Файл объекта',
                'verbose_name_plural': 'Файлы объектов',
                'indexes': [models.Index(fields=['owner_type', 'owner_id', 'company_slug'], name='ix_file_object_owner')],
                'constraints': [models.UniqueConstraint(fields=('document_id', 'version_no'), name='uq_file_object_version'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company_slug', 'owner_type', 'owner_id', 'idempotency_key'), name='uq_file_object_idempotency')],
            },
        ),
    ]
