# Generated by Django 5.2.7 on 2026-09-26 20:27

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('bell', models.BooleanField(db_default=True, default=True)),
                ('email', models.BooleanField(db_default=True, default=True)),
                ('telegram', models.BooleanField(db_default=False, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('chat_id', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('link_code', models.CharField(blank=True, db_default='', default='', max_length=32)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.IntegerField(db_index=True)),
                ('company_slug', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('event', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, db_default='', default='')),
                ('url', models.CharField(blank=True, db_default='', default='', max_length=512)),
                ('target_type', models.CharField(blank=True, db_default='', default='', max_length=32)),
                ('target_id', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_avatar_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_read', models.BooleanField(db_default=False, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'indexes': [models.Index(fields=['recipient_id', 'company_slug', 'is_read', '-created_at'], name='ix_notif_feed')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('telegram', 'Telegram')], max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Не доставлено'), ('skipped', 'Пропущено')], db_default='pending', default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('last_error', models.TextField(blank=True, db_default='', default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notification', 'channel'), name='uq_notif_delivery_channel')],
            },
        ),
    ]
