#!/usr/bin/env python
"""Machine comparison of the `cms` schema: alembic (cms-service) vs Django.

Task 1.9 (Phase 1 DoD): prove that on a fresh database, the ported Django
migrations (backend/apps/cms/migrations/) build a `cms` schema equivalent to
the one built by the FastAPI cms-service's own alembic chain
(services/cms/alembic/) — nothing dropped: no missing tables, columns,
indexes, constraints, or enums.

This script does NOT run any migrations itself. It only *compares* two
already-migrated reference databases:

  - htqweb_alembic_ref  — built by `alembic upgrade head` (cms-service image)
  - htqweb_django_ref   — built by `manage.py migrate` (Django backend)

See the Task 1.9 report (.superpowers/sdd/task-1.9-report.md) for the exact
commands used to build both. Both databases live in the same Postgres
container (htqweb1-db-1) and are reachable from the host on localhost:55432
(the docker-published port for that container — see
docker-compose.test.yml). Do not point this at the real `htqweb` database.

Usage:
    backend/.venv/Scripts/python backend/scripts/compare_schemas.py

    # Phase 2, e.g. schema `auth` (user-service), against its own pair of
    # alembic-ref / django-ref databases — no source edit required:
    SCHEMA=auth ALEMBIC_REF_DB=htqweb_alembic_ref_auth \
    DJANGO_REF_DB=htqweb_django_ref_auth \
    ALEMBIC_VERSION_TABLE=alembic_version \
        backend/.venv/Scripts/python backend/scripts/compare_schemas.py

Env overrides (all optional):
    DB_HOST, DB_PORT, DB_USER, DB_PASSWORD  — connection params (same for
                                               both reference DBs)
    ALEMBIC_REF_DB        (default: htqweb_alembic_ref)
    DJANGO_REF_DB         (default: htqweb_django_ref)
    SCHEMA                (default: cms)
    ALEMBIC_VERSION_TABLE — name of alembic's own bookkeeping table living
                             inside SCHEMA, excluded from the table-set
                             comparison (see point 6 below). Defaults to
                             "alembic_version_cms" when SCHEMA=cms (cms-
                             service's actual table name — it passes an
                             explicit `version_table=` to alembic, see
                             services/cms/alembic/env.py), else to the bare
                             alembic default "alembic_version" — which is
                             what user-service actually produces: its
                             services/user/alembic/env.py sets only
                             `version_table_schema=settings.db_schema` and
                             never overrides `version_table`, so its
                             bookkeeping table is `auth.alembic_version`,
                             NOT "alembic_version_user". The naming is not a
                             clean `alembic_version_<schema>` pattern across
                             services, so callers targeting a schema/service
                             with yet another convention should set this
                             explicitly rather than rely on the default.

Exit code: 0 if no *real* schema difference is found (after normalizing the
documented "expected diffs" below), 1 otherwise.

─── Expected / normalized diffs (NOT failures) ──────────────────────────────
These are accepted per the Task 1.1 ledger and the Task 1.9 brief, and this
script normalizes them away before comparing rather than special-casing the
output:

  1. Autoincrementing integer PK: Django's `AutoField`/`BigAutoField` compiles
     to `GENERATED BY DEFAULT AS IDENTITY`, alembic/SQLAlchemy's `Integer,
     primary_key=True` compiles to `SERIAL` (`nextval(...)` default). Both are
     normalized to the token AUTOINCREMENT.
  2. `created_at`/`updated_at` "now" default: Django's `db_default=Now()`
     compiles to `statement_timestamp()`; alembic's `server_default=func.now()`
     compiles to `now()`. Both are normalized to the token NOW.
  3. Column ordinal position: columns are compared as a name-keyed set, never
     by position.
  4. Index / constraint NAMES: compared by structural signature (columns,
     uniqueness, method / constraint type / FK target+ON DELETE rule) — a
     name mismatch on an otherwise-identical index/constraint is reported as
     informational, not a failure.
  5. Django's own service tables (django_migrations, django_content_type,
     auth_*, django_q_*, sessions, admin, core_service_status, ...) — these
     live in schema `public`, not `cms`, so scoping the comparison to schema
     `cms` already excludes them. Verified, not assumed (see report).
  6. The alembic version-bookkeeping table (`alembic_version_cms` for this
     cms run) — it lives inside schema `cms` (unlike Django's
     `django_migrations`, which Django puts in `public`), so it must be
     explicitly excluded here. Analogous to #5. The table name is derived
     from SCHEMA / ALEMBIC_VERSION_TABLE, not hardcoded — see the env-vars
     section above.

Everything else — a missing/extra table or column, a differing data type,
nullability, default, missing/extra index, missing unique/FK, wrong
`ON DELETE` rule, or an enum label/order mismatch — is a REAL difference and
fails the script.
"""

from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass, field

import psycopg
from psycopg.rows import dict_row

SCHEMA = os.environ.get("SCHEMA", "cms")

DB_HOST = os.environ.get("DB_HOST", "localhost")
DB_PORT = os.environ.get("DB_PORT", "55432")
DB_USER = os.environ.get("DB_USER", "htqweb")
DB_PASSWORD = os.environ.get("DB_PASSWORD", "change-me")

ALEMBIC_REF_DB = os.environ.get("ALEMBIC_REF_DB", "htqweb_alembic_ref")
DJANGO_REF_DB = os.environ.get("DJANGO_REF_DB", "htqweb_django_ref")

# Alembic's own bookkeeping-table name, inside SCHEMA. NOT a clean
# `alembic_version_<schema>` pattern across services — verified by reading
# each service's alembic/env.py (see the "ALEMBIC_VERSION_TABLE" entry in the
# module docstring for details): cms-service passes an explicit
# `version_table="alembic_version_cms"`; user-service passes no
# `version_table` override at all, so it gets alembic's bare default
# "alembic_version" (in schema `auth`). Default here covers both of those
# verified cases; anything else must be set explicitly via env.
ALEMBIC_VERSION_TABLE = os.environ.get(
    "ALEMBIC_VERSION_TABLE",
    "alembic_version_cms" if SCHEMA == "cms" else "alembic_version",
)

# Tables that exist by construction on only one side and are explicitly
# excluded from comparison (see module docstring, points 5-6). Django's own
# service tables aren't here because they live outside schema `cms` — they
# never even reach the table-set comparison.
ALEMBIC_ONLY_EXPECTED_TABLES = {ALEMBIC_VERSION_TABLE}
DJANGO_ONLY_EXPECTED_TABLES: set[str] = set()


# ─────────────────────────────────────────────────────────────────────────
# Data access
# ─────────────────────────────────────────────────────────────────────────


def connect(dbname: str) -> psycopg.Connection:
    return psycopg.connect(
        host=DB_HOST,
        port=DB_PORT,
        dbname=dbname,
        user=DB_USER,
        password=DB_PASSWORD,
        row_factory=dict_row,
    )


def fetch_tables(conn: psycopg.Connection, schema: str) -> set[str]:
    cur = conn.execute(
        """
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = %s AND table_type = 'BASE TABLE'
        """,
        (schema,),
    )
    return {row["table_name"] for row in cur.fetchall()}


def fetch_columns(conn: psycopg.Connection, schema: str, table: str) -> dict[str, dict]:
    cur = conn.execute(
        """
        SELECT column_name, data_type, udt_name, is_nullable, column_default,
               character_maximum_length, is_identity, identity_generation
        FROM information_schema.columns
        WHERE table_schema = %s AND table_name = %s
        """,
        (schema, table),
    )
    return {row["column_name"]: row for row in cur.fetchall()}


def fetch_indexes(conn: psycopg.Connection, schema: str, table: str) -> dict[str, str]:
    cur = conn.execute(
        """
        SELECT indexname, indexdef FROM pg_indexes
        WHERE schemaname = %s AND tablename = %s
        """,
        (schema, table),
    )
    return {row["indexname"]: row["indexdef"] for row in cur.fetchall()}


_INDEXDEF_RE = re.compile(
    r"CREATE (?P<unique>UNIQUE )?INDEX .* USING (?P<method>\w+) \((?P<cols>.*)\)$"
)


def index_signature(indexdef: str) -> tuple:
    """Structural signature of an index, ignoring its (possibly
    autogenerated) name: uniqueness, access method, and column/expression
    list. Falls back to the raw, name-stripped indexdef if the regex
    doesn't match (e.g. partial/expression indexes with extra clauses)."""
    m = _INDEXDEF_RE.search(indexdef)
    if not m:
        return ("RAW", indexdef)
    cols = tuple(c.strip() for c in m.group("cols").split(","))
    return (bool(m.group("unique")), m.group("method"), cols)


def fetch_constraints(conn: psycopg.Connection, schema: str, table: str) -> dict[str, dict]:
    cur = conn.execute(
        """
        SELECT con.conname, con.contype,
               array_agg(att.attname ORDER BY u.ord) AS columns,
               con.confdeltype,
               ref_ns.nspname AS ref_schema, ref_cls.relname AS ref_table,
               (SELECT array_agg(a2.attname ORDER BY u2.ord)
                  FROM unnest(con.confkey) WITH ORDINALITY AS u2(attnum, ord)
                  JOIN pg_attribute a2
                    ON a2.attrelid = con.confrelid AND a2.attnum = u2.attnum
               ) AS ref_columns
        FROM pg_constraint con
        JOIN pg_class cls ON cls.oid = con.conrelid
        JOIN pg_namespace ns ON ns.oid = cls.relnamespace
        JOIN unnest(con.conkey) WITH ORDINALITY AS u(attnum, ord) ON true
        JOIN pg_attribute att
          ON att.attrelid = con.conrelid AND att.attnum = u.attnum
        LEFT JOIN pg_class ref_cls ON ref_cls.oid = con.confrelid
        LEFT JOIN pg_namespace ref_ns ON ref_ns.oid = ref_cls.relnamespace
        WHERE ns.nspname = %s AND cls.relname = %s
        GROUP BY con.oid, con.conname, con.contype, con.confdeltype,
                 ref_ns.nspname, ref_cls.relname
        """,
        (schema, table),
    )
    return {row["conname"]: row for row in cur.fetchall()}


def constraint_signature(row: dict) -> tuple:
    """Structural signature of a constraint, ignoring its (possibly
    autogenerated) name: type, column list, and — for FKs — target
    table/columns and ON DELETE rule."""
    return (
        row["contype"],
        tuple(row["columns"]),
        row["ref_schema"],
        row["ref_table"],
        tuple(row["ref_columns"]) if row["ref_columns"] else None,
        row["confdeltype"] if row["contype"] == "f" else None,
    )


CONFDELTYPE_LABEL = {
    "a": "NO ACTION",
    "r": "RESTRICT",
    "c": "CASCADE",
    "n": "SET NULL",
    "d": "SET DEFAULT",
    " ": "n/a",
}


def fetch_enums(conn: psycopg.Connection, schema: str) -> dict[str, list[str]]:
    cur = conn.execute(
        """
        SELECT t.typname, e.enumlabel
        FROM pg_type t
        JOIN pg_enum e ON t.oid = e.enumtypid
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = %s
        ORDER BY t.typname, e.enumsortorder
        """,
        (schema,),
    )
    enums: dict[str, list[str]] = {}
    for row in cur.fetchall():
        enums.setdefault(row["typname"], []).append(row["enumlabel"])
    return enums


# ─────────────────────────────────────────────────────────────────────────
# Normalization
# ─────────────────────────────────────────────────────────────────────────

_NEXTVAL_RE = re.compile(r"^nextval\(")


def normalize_default(col: dict) -> str | None:
    if col["is_identity"] == "YES":
        return "AUTOINCREMENT"
    default = col["column_default"]
    if default and _NEXTVAL_RE.match(default):
        return "AUTOINCREMENT"
    if default in ("now()", "statement_timestamp()"):
        return "NOW"
    return default


def normalized_column(col: dict) -> tuple:
    return (
        col["data_type"],
        col["udt_name"],
        col["is_nullable"],
        normalize_default(col),
        col["character_maximum_length"],
    )


# ─────────────────────────────────────────────────────────────────────────
# Diff bookkeeping
# ─────────────────────────────────────────────────────────────────────────


@dataclass
class Report:
    real_diffs: list[str] = field(default_factory=list)
    expected_diffs: list[str] = field(default_factory=list)

    def real(self, msg: str) -> None:
        self.real_diffs.append(msg)
        print(f"  [REAL DIFF]     {msg}")

    def expected(self, msg: str) -> None:
        self.expected_diffs.append(msg)
        print(f"  [expected/ok]   {msg}")

    def info(self, msg: str) -> None:
        print(f"  [info]          {msg}")


# ─────────────────────────────────────────────────────────────────────────
# Comparison
# ─────────────────────────────────────────────────────────────────────────


def compare(a_conn: psycopg.Connection, d_conn: psycopg.Connection, report: Report) -> None:
    print(f"=== Comparing schema `{SCHEMA}`: alembic ({ALEMBIC_REF_DB}) vs Django ({DJANGO_REF_DB}) ===\n")

    a_tables_raw = fetch_tables(a_conn, SCHEMA)
    d_tables_raw = fetch_tables(d_conn, SCHEMA)

    print("--- Tables ---")
    a_extra = a_tables_raw - d_tables_raw
    d_extra = d_tables_raw - a_tables_raw
    for t in sorted(a_extra):
        if t in ALEMBIC_ONLY_EXPECTED_TABLES:
            report.expected(f"table `{t}` exists only on alembic side (alembic's own migration-bookkeeping table, ALEMBIC_VERSION_TABLE)")
        else:
            report.real(f"table `{t}` exists in alembic ref but is MISSING from Django migrations")
    for t in sorted(d_extra):
        if t in DJANGO_ONLY_EXPECTED_TABLES:
            report.expected(f"table `{t}` exists only on Django side (expected)")
        else:
            report.real(f"table `{t}` exists in Django ref but is MISSING from alembic (unexpected extra table)")

    common_tables = sorted((a_tables_raw & d_tables_raw) - ALEMBIC_ONLY_EXPECTED_TABLES - DJANGO_ONLY_EXPECTED_TABLES)
    report.info(f"{len(common_tables)} tables compared in both: {', '.join(common_tables)}")

    for table in common_tables:
        print(f"\n--- Table `{table}` : columns ---")
        a_cols = fetch_columns(a_conn, SCHEMA, table)
        d_cols = fetch_columns(d_conn, SCHEMA, table)
        for col_name in sorted(set(a_cols) | set(d_cols)):
            if col_name not in a_cols:
                report.real(f"{table}.{col_name}: present in Django, MISSING from alembic reference")
                continue
            if col_name not in d_cols:
                report.real(f"{table}.{col_name}: present in alembic, MISSING from Django migrations")
                continue
            a_col, d_col = a_cols[col_name], d_cols[col_name]
            a_norm, d_norm = normalized_column(a_col), normalized_column(d_col)
            if a_norm != d_norm:
                report.real(
                    f"{table}.{col_name}: type/nullability/default differ — "
                    f"alembic={a_norm} django={d_norm} "
                    f"(raw defaults: alembic={a_col['column_default']!r} django={d_col['column_default']!r})"
                )
            else:
                # Still flag raw-default text differences that were normalized away, for the report's audit trail.
                if a_col["column_default"] != d_col["column_default"]:
                    report.expected(
                        f"{table}.{col_name}: default text differs but is semantically equivalent — "
                        f"alembic={a_col['column_default']!r} django={d_col['column_default']!r}"
                    )

        print(f"--- Table `{table}` : indexes ---")
        a_idx = fetch_indexes(a_conn, SCHEMA, table)
        d_idx = fetch_indexes(d_conn, SCHEMA, table)
        a_sig_to_names: dict[tuple, list[str]] = {}
        for name, ddl in a_idx.items():
            a_sig_to_names.setdefault(index_signature(ddl), []).append(name)
        d_sig_to_names: dict[tuple, list[str]] = {}
        for name, ddl in d_idx.items():
            d_sig_to_names.setdefault(index_signature(ddl), []).append(name)

        for sig in sorted(set(a_sig_to_names) - set(d_sig_to_names), key=str):
            report.real(f"{table}: index missing from Django migrations — signature {sig} (alembic name(s): {a_sig_to_names[sig]})")
        for sig in sorted(set(d_sig_to_names) - set(a_sig_to_names), key=str):
            report.real(f"{table}: index missing from alembic reference (unexpected extra in Django) — signature {sig} (django name(s): {d_sig_to_names[sig]})")
        for sig in sorted(set(a_sig_to_names) & set(d_sig_to_names), key=str):
            a_names, d_names = sorted(a_sig_to_names[sig]), sorted(d_sig_to_names[sig])
            if a_names != d_names:
                report.expected(f"{table}: index signature {sig} present both sides under different names — alembic={a_names} django={d_names}")

        print(f"--- Table `{table}` : constraints ---")
        a_con = fetch_constraints(a_conn, SCHEMA, table)
        d_con = fetch_constraints(d_conn, SCHEMA, table)
        a_sig_to_names = {}
        for name, row in a_con.items():
            a_sig_to_names.setdefault(constraint_signature(row), []).append(name)
        d_sig_to_names = {}
        for name, row in d_con.items():
            d_sig_to_names.setdefault(constraint_signature(row), []).append(name)

        def describe(sig: tuple) -> str:
            contype, cols, ref_schema, ref_table, ref_cols, confdeltype = sig
            kind = {"p": "PRIMARY KEY", "u": "UNIQUE", "f": "FOREIGN KEY", "c": "CHECK"}.get(contype, contype)
            desc = f"{kind}{list(cols)}"
            if contype == "f":
                desc += f" -> {ref_schema}.{ref_table}{list(ref_cols) if ref_cols else []} ON DELETE {CONFDELTYPE_LABEL.get(confdeltype, confdeltype)}"
            return desc

        for sig in sorted(set(a_sig_to_names) - set(d_sig_to_names), key=str):
            report.real(f"{table}: constraint missing from Django migrations — {describe(sig)} (alembic name(s): {a_sig_to_names[sig]})")
        for sig in sorted(set(d_sig_to_names) - set(a_sig_to_names), key=str):
            report.real(f"{table}: constraint missing from alembic reference (unexpected extra/different in Django) — {describe(sig)} (django name(s): {d_sig_to_names[sig]})")
        for sig in sorted(set(a_sig_to_names) & set(d_sig_to_names), key=str):
            a_names, d_names = sorted(a_sig_to_names[sig]), sorted(d_sig_to_names[sig])
            if a_names != d_names:
                report.expected(f"{table}: constraint {describe(sig)} present both sides under different names — alembic={a_names} django={d_names}")

    print("\n--- Enum types ---")
    a_enums = fetch_enums(a_conn, SCHEMA)
    d_enums = fetch_enums(d_conn, SCHEMA)
    for name in sorted(set(a_enums) | set(d_enums)):
        if name not in a_enums:
            report.real(f"enum `{name}` present in Django, MISSING from alembic reference")
            continue
        if name not in d_enums:
            report.real(f"enum `{name}` present in alembic, MISSING from Django migrations")
            continue
        if a_enums[name] != d_enums[name]:
            report.real(f"enum `{name}` labels/order differ — alembic={a_enums[name]} django={d_enums[name]}")
        else:
            report.info(f"enum `{name}` labels match, in order: {a_enums[name]}")


def main() -> int:
    # Windows consoles often default to a non-UTF-8 codepage (cp1252/cp437),
    # which mangles the em dashes used throughout this script's output.
    for stream in (sys.stdout, sys.stderr):
        if getattr(stream, "encoding", "").lower() != "utf-8":
            try:
                stream.reconfigure(encoding="utf-8")
            except (AttributeError, ValueError):
                pass

    a_conn = connect(ALEMBIC_REF_DB)
    d_conn = connect(DJANGO_REF_DB)
    report = Report()
    try:
        compare(a_conn, d_conn, report)
    finally:
        a_conn.close()
        d_conn.close()

    print("\n=== Verdict ===")
    print(f"Expected/normalized diffs: {len(report.expected_diffs)}")
    print(f"REAL diffs: {len(report.real_diffs)}")
    if report.real_diffs:
        print("\nFAIL — real schema differences found between alembic and Django migrations:")
        for msg in report.real_diffs:
            print(f"  - {msg}")
        return 1
    print(f"\nPASS — schema `{SCHEMA}` built by Django migrations is equivalent to the alembic reference "
          "(modulo documented expected diffs: identity vs serial, statement_timestamp() vs now(), "
          f"column ordinal order, and the `{ALEMBIC_VERSION_TABLE}` bookkeeping table).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
