# Generated by Django 5.2.7 on 2026-07-19 13:22

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=256)),
                ('first_name', models.CharField(blank=True, db_default='', default='', max_length=150)),
                ('last_name', models.CharField(blank=True, db_default='', default='', max_length=150)),
                ('patronymic', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('display_name', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('bio', models.TextField(blank=True, db_default='', default='')),
                ('phone', models.CharField(blank=True, db_default='', default='', max_length=30)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('settings', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_default='pending', db_index=True, default='pending', max_length=16)),
                ('is_staff', models.BooleanField(db_default=False, default=False)),
                ('is_superuser', models.BooleanField(db_default=False, default=False)),
                ('must_change_password', models.BooleanField(db_default=False, default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
