# Generated by Django 5.2.7 on 2026-07-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
