# Generated by Django 5.2.7 on 2026-07-18 12:29

from django.db import migrations, models

from apps.core.models import KNOWN_SERVICES


def seed_service_status(apps, schema_editor):
    """Засеять реестр: все известные сервисы включены, кроме conference
    (SFU/webtransport стек намеренно не в строю, Д10)."""
    ServiceStatus = apps.get_model("core", "ServiceStatus")
    for name in KNOWN_SERVICES:
        ServiceStatus.objects.update_or_create(
            app_label=name,
            defaults={"enabled": name != "conference"},
        )


def unseed_service_status(apps, schema_editor):
    """Обратная миграция: удаляем только засеянные записи."""
    ServiceStatus = apps.get_model("core", "ServiceStatus")
    ServiceStatus.objects.filter(app_label__in=KNOWN_SERVICES).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('message', models.CharField(default='Сервис в данный момент недоступен', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_service_status',
            },
        ),
        migrations.RunPython(seed_service_status, unseed_service_status),
    ]
