# Generated by Django 5.2.7 on 2026-08-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicestatus',
            options={'verbose_name': 'Состояние сервиса', 'verbose_name_plural': 'Состояния сервисов'},
        ),
    ]
