# Generated by Django 5.2.7 on 2026-07-19 06:32, hand-augmented (Task 1.1
# Step 4) to port the cms alembic chain (001_initial .. 004_news_taxonomy)
# in full: schema + enum creation up front, the four indexes Django's Index
# name-length check (models.E034, 30-char cap) refused to let the model
# declare, the news.status PG-enum column-type conversion, and the
# published/published_at sync trigger from 004_news_taxonomy.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # ── Schema + enum, before any CreateModel ──────────────────────
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS cms",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DO $$ BEGIN CREATE TYPE cms.news_status AS ENUM "
            "('draft','scheduled','published','archived'); "
            "EXCEPTION WHEN duplicate_object THEN NULL; END $$;",
            reverse_sql="DROP TYPE IF EXISTS cms.news_status",
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, default='')),
                ('handled', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('replied_by_id', models.IntegerField(blank=True, null=True)),
                ('reply_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms"."contact_requests',
                'managed': True,
            },
        ),
        # ix_cms_contact_requests_created_at / _handled / _replied_at are all
        # >30 chars — over Django's Index name cap (models.E034) — created
        # here via RunSQL instead of Meta.indexes (alembic 001_initial).
        migrations.RunSQL(
            "CREATE INDEX ix_cms_contact_requests_created_at ON cms.contact_requests (created_at);"
            "CREATE INDEX ix_cms_contact_requests_handled ON cms.contact_requests (handled);"
            "CREATE INDEX ix_cms_contact_requests_replied_at ON cms.contact_requests (replied_at);",
            reverse_sql=
            "DROP INDEX IF EXISTS cms.ix_cms_contact_requests_replied_at;"
            "DROP INDEX IF EXISTS cms.ix_cms_contact_requests_handled;"
            "DROP INDEX IF EXISTS cms.ix_cms_contact_requests_created_at;",
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms"."audit_log',
                'managed': True,
                'indexes': [models.Index(fields=['user_id'], name='ix_cms_audit_log_user_id'), models.Index(fields=['action'], name='ix_cms_audit_log_action'), models.Index(fields=['resource_id'], name='ix_cms_audit_log_resource_id'), models.Index(fields=['created_at'], name='ix_cms_audit_log_created_at')],
            },
        ),
        # ix_cms_audit_log_correlation_id is 31 chars — over the same cap.
        migrations.RunSQL(
            "CREATE INDEX ix_cms_audit_log_correlation_id ON cms.audit_log (correlation_id);",
            reverse_sql="DROP INDEX IF EXISTS cms.ix_cms_audit_log_correlation_id;",
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms"."categories',
                'managed': True,
                'indexes': [models.Index(fields=['slug'], name='ix_cms_categories_slug')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='uq_cms_categories_slug')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=320)),
                ('excerpt', models.CharField(blank=True, default='', max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_ref', models.ForeignKey(blank=True, db_column='category_id', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='cms.category')),
            ],
            options={
                'db_table': 'cms"."news',
                'managed': True,
            },
        ),
        # Real ON DELETE SET NULL at the DB level — Django's on_delete is
        # application-side only (db_constraint=False on the field above
        # skips its own NO-ACTION-only FK), so the actual constraint (named
        # to match alembic's fk_cms_news_category) is added here.
        migrations.RunSQL(
            "ALTER TABLE cms.news ADD CONSTRAINT fk_cms_news_category "
            "FOREIGN KEY (category_id) REFERENCES cms.categories (id) ON DELETE SET NULL;",
            reverse_sql="ALTER TABLE cms.news DROP CONSTRAINT IF EXISTS fk_cms_news_category;",
        ),
        # news.status is a Django CharField (task brief decision) but the
        # physical column must stay the cms.news_status PG enum, exactly as
        # alembic 004_news_taxonomy left it — convert right after creation.
        migrations.RunSQL(
            "ALTER TABLE cms.news ALTER COLUMN status DROP DEFAULT;"
            "ALTER TABLE cms.news ALTER COLUMN status TYPE cms.news_status USING status::cms.news_status;"
            "ALTER TABLE cms.news ALTER COLUMN status SET DEFAULT 'draft'::cms.news_status;",
            reverse_sql=
            "ALTER TABLE cms.news ALTER COLUMN status DROP DEFAULT;"
            "ALTER TABLE cms.news ALTER COLUMN status TYPE varchar(20) USING status::text;"
            "ALTER TABLE cms.news ALTER COLUMN status SET DEFAULT 'draft';",
        ),
        # Trigger keeps the legacy `published` boolean (+ published_at) mirror
        # in sync with `status`, ported verbatim from 004_news_taxonomy.
        migrations.RunSQL(
            "CREATE OR REPLACE FUNCTION cms._news_sync_published() RETURNS TRIGGER AS $$\n"
            "BEGIN\n"
            "    NEW.published := (NEW.status = 'published');\n"
            "    IF NEW.status = 'published' AND NEW.published_at IS NULL THEN\n"
            "        NEW.published_at := now();\n"
            "    ELSIF NEW.status <> 'published' THEN\n"
            "        NEW.published_at := NULL;\n"
            "    END IF;\n"
            "    RETURN NEW;\n"
            "END;\n"
            "$$ LANGUAGE plpgsql;\n"
            "DROP TRIGGER IF EXISTS news_sync_published ON cms.news;\n"
            "CREATE TRIGGER news_sync_published\n"
            "BEFORE INSERT OR UPDATE OF status ON cms.news\n"
            "FOR EACH ROW EXECUTE FUNCTION cms._news_sync_published();",
            reverse_sql=
            "DROP TRIGGER IF EXISTS news_sync_published ON cms.news;"
            "DROP FUNCTION IF EXISTS cms._news_sync_published();",
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, default='attachment', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('uploaded_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(db_column='news_id', db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cms.news')),
            ],
            options={
                'db_table': 'cms"."news_attachments',
                'managed': True,
            },
        ),
        # ix_cms_news_attachments_news_id is 31 chars — over the same cap.
        migrations.RunSQL(
            "CREATE INDEX ix_cms_news_attachments_news_id ON cms.news_attachments (news_id);",
            reverse_sql="DROP INDEX IF EXISTS cms.ix_cms_news_attachments_news_id;",
        ),
        # Real ON DELETE CASCADE — see the fk_cms_news_category comment above
        # for why db_constraint=False + explicit RunSQL is needed.
        migrations.RunSQL(
            "ALTER TABLE cms.news_attachments ADD CONSTRAINT fk_cms_news_attachments_news "
            "FOREIGN KEY (news_id) REFERENCES cms.news (id) ON DELETE CASCADE;",
            reverse_sql="ALTER TABLE cms.news_attachments DROP CONSTRAINT IF EXISTS fk_cms_news_attachments_news;",
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms"."tags',
                'managed': True,
                'indexes': [models.Index(fields=['slug'], name='ix_cms_tags_slug')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='uq_cms_tags_slug')],
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('pk', models.CompositePrimaryKey('news_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('news', models.ForeignKey(db_column='news_id', db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='cms.news')),
                ('tag', models.ForeignKey(db_column='tag_id', db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='cms.tag')),
            ],
            options={
                'db_table': 'cms"."news_tags',
                'managed': True,
            },
        ),
        # Real ON DELETE CASCADE for both join-table FKs — see the
        # fk_cms_news_category comment above for why this is RunSQL, not
        # Django's own (application-side-only) on_delete.
        migrations.RunSQL(
            "ALTER TABLE cms.news_tags ADD CONSTRAINT fk_cms_news_tags_news "
            "FOREIGN KEY (news_id) REFERENCES cms.news (id) ON DELETE CASCADE;"
            "ALTER TABLE cms.news_tags ADD CONSTRAINT fk_cms_news_tags_tag "
            "FOREIGN KEY (tag_id) REFERENCES cms.tags (id) ON DELETE CASCADE;",
            reverse_sql=
            "ALTER TABLE cms.news_tags DROP CONSTRAINT IF EXISTS fk_cms_news_tags_tag;"
            "ALTER TABLE cms.news_tags DROP CONSTRAINT IF EXISTS fk_cms_news_tags_news;",
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='news_set', through='cms.NewsTag', to='cms.tag'),
        ),
        migrations.AddIndex(
            model_name='newstag',
            index=models.Index(fields=['tag'], name='ix_cms_news_tags_tag_id'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category'], name='ix_cms_news_category'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['created_at'], name='ix_cms_news_created_at'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published'], name='ix_cms_news_published'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published_at'], name='ix_cms_news_published_at'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status'], name='ix_cms_news_status'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['scheduled_at'], name='ix_cms_news_scheduled_at'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category_ref'], name='ix_cms_news_category_id'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['author_id'], name='ix_cms_news_author_id'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('slug',), name='ix_cms_news_slug'),
        ),
    ]
