# Generated by Django 5.2.7 on 2026-07-19 10:48

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, db_default='', default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_default='', default='', max_length=150)),
                ('last_name', models.CharField(blank=True, db_default='', default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, db_default='', default='')),
                ('handled', models.BooleanField(db_default=False, default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('replied_by_id', models.IntegerField(blank=True, null=True)),
                ('reply_message', models.TextField(blank=True, db_default='', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=320, unique=True)),
                ('excerpt', models.CharField(blank=True, db_default='', default='', max_length=500)),
                ('summary', models.TextField(blank=True, db_default='', default='')),
                ('content', models.TextField(blank=True, db_default='', default='')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_default='draft', default='draft', max_length=20)),
                ('published', models.BooleanField(db_default=False, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('category_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='cms.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='news_set', to='cms.tag')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, db_default='attachment', default='attachment', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('uploaded_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cms.news')),
            ],
        ),
    ]
