# Generated by Django 5.2.7 on 2026-08-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_auditlog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('tag_ru', models.CharField(blank=True, default='', max_length=120)),
                ('tag_en', models.CharField(blank=True, default='', max_length=120)),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Блок главной страницы',
                'verbose_name_plural': 'Блоки главной страницы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('value', models.CharField(blank=True, default='', max_length=64)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('image', models.CharField(blank=True, default='', max_length=512)),
                ('link', models.CharField(blank=True, default='', max_length=512)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.homesection')),
            ],
            options={
                'verbose_name': 'Элемент блока',
                'verbose_name_plural': 'Элементы блоков',
                'ordering': ['order', 'id'],
            },
        ),
    ]
