# Generated by Django 5.2.7 on 2026-08-17 11:54

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_auditlog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(db_index=True, max_length=64)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('allow_guests', models.BooleanField(db_default=True, default=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(db_default=0, default=0)),
                ('uses', models.PositiveIntegerField(db_default=0, default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Приглашение в конференцию',
                'verbose_name_plural': 'Приглашения в конференцию',
                'ordering': ('-created_at',),
            },
        ),
    ]
