"""Первичное наполнение блоков главной страницы.

Значения сняты с текущих i18n-файлов (frontend/public/locales/{ru,en}), чтобы
после выката главная выглядела ровно так же, как до него: страница начинает
читать тексты из БД, но сами тексты те же. Без этого сида лендинг после
миграции стал бы пустым.

Идемпотентна: секции создаются через get_or_create по ``key``, элементы — только
для вновь созданных секций. Повторный прогон (или прогон на базе, где редактор
уже что-то поправил) ничего не перезаписывает.

Обратная миграция удаляет только эти девять ключей, а не всю таблицу.
"""
from django.db import migrations

SECTIONS = [{'key': 'hero', 'order': 10, 'tag_ru': 'Лидер рынка в Центральной Азии', 'tag_en': 'Market Leader in Central Asia', 'title_ru': 'Надёжные решения для лучшего будущего', 'title_en': 'Reliable Solutions for a Better Future', 'description_ru': 'Лидер рынка в Центральной Азии в строительстве проектов по использованию возобновляемых источников энергии', 'description_en': 'Market leader in Central Asia in the construction of renewable energy projects', 'items': [{'order': 10, 'title_ru': '', 'title_en': '', 'description_ru': 'HTQ принял участие в проектах строительства солнечных электростанций общей мощностью 160 МВт', 'description_en': 'HTQ participated in solar power plant construction projects with a total capacity of 160 MW', 'value': '160 МВт', 'icon': 'Zap', 'image': ''},
    {'order': 20, 'title_ru': '', 'title_en': '', 'description_ru': 'СЭС общей мощностью 90 МВт построены в Казахстане по полному циклу', 'description_en': '90 MW Solar Power Plants built in Kazakhstan on a full cycle basis', 'value': 'Полный цикл', 'icon': 'Layers', 'image': ''},
    {'order': 30, 'title_ru': '', 'title_en': '', 'description_ru': 'Разработали эффективную методику для успешного выполнения проектов', 'description_en': 'Developed an effective methodology for successful project execution', 'value': 'Собственная методика', 'icon': 'Compass', 'image': ''}]},
    {'key': 'directions', 'order': 20, 'tag_ru': 'Направления', 'tag_en': 'Directions', 'title_ru': 'Направления деятельности', 'title_en': 'Activity Directions', 'description_ru': '', 'description_en': '', 'items': [{'order': 10, 'title_ru': 'Земляные работы', 'title_en': 'Earthworks', 'description_ru': 'Подготовка площадки и земляные работы для солнечных электростанций', 'description_en': 'Site preparation and earthworks for solar power plants', 'value': '', 'icon': 'Mountain', 'image': ''},
    {'order': 20, 'title_ru': 'Общестроительные работы', 'title_en': 'General Construction', 'description_ru': 'Строительство инфраструктуры и зданий для энергетических объектов', 'description_en': 'Construction of infrastructure and buildings for energy facilities', 'value': '', 'icon': 'Building2', 'image': ''},
    {'order': 30, 'title_ru': 'Монтажные работы и сборка', 'title_en': 'Installation and Assembly', 'description_ru': 'Монтаж солнечных панелей и сопутствующего оборудования', 'description_en': 'Installation of solar panels and related equipment', 'value': '', 'icon': 'Wrench', 'image': ''},
    {'order': 40, 'title_ru': 'Электрические работы: Солнечный парк', 'title_en': 'Electrical Works: Solar Park', 'description_ru': 'Электромонтажные работы на стороне постоянного и переменного тока', 'description_en': 'Electrical installation works on DC and AC sides', 'value': '', 'icon': 'Sun', 'image': ''},
    {'order': 50, 'title_ru': 'Электрические работы: ПС и ВЛ', 'title_en': 'Electrical Works: SS and OHL', 'description_ru': 'Строительство подстанций и воздушных линий электропередач', 'description_en': 'Construction of substations and overhead power lines', 'value': '', 'icon': 'Zap', 'image': ''}]},
    {'key': 'invest', 'order': 30, 'tag_ru': 'Зелёные инвестиции', 'tag_en': 'Green Investment', 'title_ru': 'Инвестируйте в зелёные технологии', 'title_en': 'Invest in green technologies', 'description_ru': 'чтобы сохранить и улучшить мир, в котором мы живём', 'description_en': 'to preserve and enhance the world in which we live', 'items': []},
    {'key': 'projects', 'order': 40, 'tag_ru': 'Портфолио', 'tag_en': 'Portfolio', 'title_ru': 'Проекты', 'title_en': 'Projects', 'description_ru': 'Во всем, что мы делаем, наша цель — минимизировать риски для наших клиентов, максимизировать эффективность и прибыльность проектов и гарантировать их долгосрочный успех.', 'description_en': 'In everything we do, our goal is to minimize the risk for our customers, maximize project efficiency and profitability, and guarantee their long-term success.', 'items': []},
    {'key': 'services', 'order': 50, 'tag_ru': 'Что мы делаем', 'tag_en': 'What we do', 'title_ru': 'Наша роль', 'title_en': 'Our Role', 'description_ru': 'Hi-Tech Group — это опытная команда с десятилетним стажем реализации проектов возобновляемой энергетики в Центральной Азии.', 'description_en': 'Hi-Tech Group is a seasoned team with a decade of expertise in executing renewable energy projects across Central Asia.', 'items': [{'order': 10, 'title_ru': 'Услуги инженера заказчика', 'title_en': "Owner's Engineer Service", 'description_ru': 'Мы содействуем общению между клиентами, EPC-подрядчиками, субподрядчиками, банками, государственными органами и консультантами. Мы контролируем строительные работы на объекте для обеспечения качества, соблюдения местных законов, а также стандартов безопасности и охраны окружающей среды.', 'description_en': 'We facilitate communication among clients, EPC contractors, subcontractors, banks, governmental bodies, and consultancies. We monitor construction activities on-site to ensure quality, compliance with local laws, and adherence to safety and environmental standards.', 'value': '', 'icon': '', 'image': ''},
    {'order': 20, 'title_ru': 'Испытание на выдергивание (POT)', 'title_en': 'Pull Out Test (POT)', 'description_ru': 'Мы предлагаем услуги по испытаниям на выдергивание, адаптированные для солнечных фотоэлектрических станций. Свайные фундаменты проектируются так, чтобы выдерживать различные нагрузки, такие как осевые, боковые, моментные, подъемные и их комбинации.', 'description_en': 'We offer Pull Out Test services customized for solar PV plants. Pile foundations are designed to withstand a variety of loads such as axial, lateral, moment, uplift, and combinations thereof.', 'value': '', 'icon': '', 'image': ''},
    {'order': 30, 'title_ru': 'Строительные услуги', 'title_en': 'Construction Service', 'description_ru': 'Наши услуги включают ландшафтный дизайн, земляные работы, дорожное строительство, гражданские сооружения, сборочно-монтажные операции и электромонтажные работы, включая установки переменного тока.', 'description_en': 'Our services include landscaping, earthworks, road construction, civil structures, assembly and installation operations, and electrical works, including AC installations.', 'value': '', 'icon': '', 'image': ''},
    {'order': 40, 'title_ru': 'Ввод в эксплуатацию и подключение к сети', 'title_en': 'Commissioning and Grid Connection', 'description_ru': 'Мы направляем и курируем процесс подключения к сети, включая подготовку программ испытаний для АСКУЭ, координацию разрешений на опытно-промышленные испытания с операторами сетей.', 'description_en': 'We guide and oversee the grid connection process, including preparing testing programs for ASKUE, coordinating approvals for pilot industrial tests with grid operators.', 'value': '', 'icon': '', 'image': ''},
    {'order': 50, 'title_ru': 'Эксплуатация и техническое обслуживание', 'title_en': 'Operation and Maintenance', 'description_ru': 'Мы оцениваем эксплуатационные характеристики компонентов фотоэлектрических станций, обслуживаем их в соответствии с рекомендациями производителей, проводим испытания оборудования для обеспечения надежности.', 'description_en': "We evaluate the operational performance of PV plant components, maintain them according to manufacturers' guidelines, conduct hardware tests to ensure reliability.", 'value': '', 'icon': '', 'image': ''}]},
    {'key': 'stats', 'order': 60, 'tag_ru': 'Наше влияние', 'tag_en': 'Our Impact', 'title_ru': 'Решения в области возобновляемых источников энергии', 'title_en': 'Solutions in Renewable Energy', 'description_ru': '', 'description_en': '', 'items': [{'order': 10, 'title_ru': 'Лет опыта', 'title_en': 'Years of Experience', 'description_ru': '', 'description_en': '', 'value': '10+', 'icon': '', 'image': ''},
    {'order': 20, 'title_ru': 'Завершенных проектов', 'title_en': 'Completed Projects', 'description_ru': '', 'description_en': '', 'value': '15+', 'icon': '', 'image': ''},
    {'order': 30, 'title_ru': 'Мегаватт установлено', 'title_en': 'Megawatts Installed', 'description_ru': '', 'description_en': '', 'value': '722', 'icon': '', 'image': ''}]},
    {'key': 'mission', 'order': 70, 'tag_ru': 'Наша миссия', 'tag_en': 'Our Mission', 'title_ru': 'Комплексные решения в области ВИЭ', 'title_en': 'Comprehensive RE Solutions', 'description_ru': 'Миссия компании заключается в предоставлении комплексных решений в области возобновляемых источников энергии для достижения устойчивого развития наших клиентов.', 'description_en': "The company's mission is to provide comprehensive renewable energy solutions to achieve sustainable development for our clients.", 'items': [{'order': 10, 'title_ru': 'Комплексные решения', 'title_en': 'Comprehensive Solutions', 'description_ru': 'Полный цикл услуг от разработки до эксплуатации проектов ВИЭ', 'description_en': 'Full cycle of services from development to operation of RE projects', 'value': '', 'icon': 'Lightbulb', 'image': ''},
    {'order': 20, 'title_ru': 'Надёжность', 'title_en': 'Reliability', 'description_ru': 'Гарантия качества и соответствие международным стандартам', 'description_en': 'Quality assurance and compliance with international standards', 'value': '', 'icon': 'ShieldCheck', 'image': ''},
    {'order': 30, 'title_ru': 'Инновации', 'title_en': 'Innovation', 'description_ru': 'Применение передовых технологий и методик', 'description_en': 'Application of advanced technologies and methodologies', 'value': '', 'icon': 'Rocket', 'image': ''}]},
    {'key': 'about', 'order': 80, 'tag_ru': 'О нас', 'tag_en': 'About Us', 'title_ru': 'Мы предлагаем услуги энергетического консалтинга', 'title_en': 'We offer energy consulting services', 'description_ru': 'Здесь, в группе компаний Hi-Tech Group, мы искренне верим, что новые технологии и решения, новые «зеленые» проекты помогут сохранить и улучшить мир, в котором мы живем. Мы обладаем необходимыми знаниями и опытом, которые позволят нам предлагать нашим клиентам комплексные решения по разработке, реализации и управлению проектами в отрасли возобновляемой энергетики.', 'description_en': 'Here, in the Hi-Tech Group of companies, we sincerely believe that new technologies and solutions, new green projects will help preserve and enhance the world in which we live. We have the necessary knowledge and experience that will allow us to offer our customers comprehensive solutions for the development, implementation and project management in the renewable energy industry.', 'items': [{'order': 10, 'title_ru': 'Солнечная энергия', 'title_en': 'Solar Energy', 'description_ru': 'Экспертиза в разработке крупномасштабных солнечных электростанций', 'description_en': 'Expertise in large-scale solar power plant development', 'value': '', 'icon': 'Sun', 'image': ''},
    {'order': 20, 'title_ru': 'Зеленые решения', 'title_en': 'Green Solutions', 'description_ru': 'Устойчивые методы для чистого будущего', 'description_en': 'Sustainable practices for a cleaner future', 'value': '', 'icon': 'Leaf', 'image': ''},
    {'order': 30, 'title_ru': 'Энергоэффективность', 'title_en': 'Energy Efficiency', 'description_ru': 'Максимизация производительности при минимальном воздействии на окружающую среду', 'description_en': 'Maximizing output while minimizing environmental impact', 'value': '', 'icon': 'Gauge', 'image': ''}]},
    {'key': 'partners', 'order': 90, 'tag_ru': 'Партнеры', 'tag_en': 'Partners', 'title_ru': 'Нам доверяют отраслевые эксперты', 'title_en': 'Trusted by Industry Experts', 'description_ru': '', 'description_en': '', 'items': []}]


def seed(apps, schema_editor):
    Section = apps.get_model("cms", "HomeSection")
    Item = apps.get_model("cms", "HomeSectionItem")
    for data in SECTIONS:
        items = data.pop("items", [])
        section, created = Section.objects.get_or_create(key=data["key"], defaults=data)
        if not created:
            continue
        for it in items:
            Item.objects.create(section=section, **it)


def unseed(apps, schema_editor):
    Section = apps.get_model("cms", "HomeSection")
    Section.objects.filter(key__in=[s["key"] for s in SECTIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [("cms", "0005_homesection_homesectionitem")]

    operations = [migrations.RunPython(seed, unseed)]
