# Generated by Django 5.2.7 on 2026-08-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_seed_home_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homesection',
            name='layout',
            field=models.CharField(choices=[('features_grid', 'Сетка карточек (иконка, заголовок, текст)'), ('stats', 'Цифры (значение и подпись)'), ('cta', 'Призыв к действию (заголовок, текст, кнопка)'), ('text_media', 'Текст с картинкой')], default='features_grid', max_length=32),
        ),
    ]
