# Generated by Django 5.2.7 on 2026-08-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_merge_conference_invites_home_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceinvite',
            name='locale',
            field=models.CharField(blank=True, db_default='', default='', max_length=8),
        ),
    ]
