# Generated by Django 5.2.7 on 2026-07-22 05:00

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('user_id', models.IntegerField()),
                ('device_id', models.CharField(max_length=255)),
                ('public_identity_key', models.TextField()),
                ('signed_pre_key', models.TextField()),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('pk', models.CompositePrimaryKey('user_id', 'device_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_metadata_id', models.UUIDField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('images', 'Изображения'), ('audio', 'Аудио'), ('video', 'Видео'), ('archives', 'Архивы'), ('documents', 'Документы'), ('other', 'Другое')], db_default='other', default='other', max_length=40)),
                ('storage_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('public_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('thumbnail_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messenger.message')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messenger.room')),
            ],
        ),
    ]
