# Generated by Django 5.2.7 on 2026-08-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_messenger_periodic_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Запись аудита', 'verbose_name_plural': 'Журнал аудита'},
        ),
        migrations.AlterModelOptions(
            name='chatattachment',
            options={'verbose_name': 'Вложение чата', 'verbose_name_plural': 'Вложения чатов'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={'verbose_name': 'Участник комнаты', 'verbose_name_plural': 'Участники комнат'},
        ),
        migrations.AlterModelOptions(
            name='userkey',
            options={'verbose_name': 'Ключ шифрования', 'verbose_name_plural': 'Ключи шифрования'},
        ),
    ]
