# Generated by Django 5.2.7 on 2026-07-21 09:43

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('icon', models.CharField(blank=True, db_default='', default='', max_length=50)),
                ('color', models.CharField(db_default='#3b82f6', default='#3b82f6', max_length=20)),
                ('config_json', models.JSONField(blank=True, db_default={}, default=dict)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_default='active', default='active', max_length=16)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('current_version_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='RequestProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_default='active', default='active', max_length=20)),
                ('color', models.CharField(db_default='#3b82f6', default='#3b82f6', max_length=20)),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(db_default='KZT', default='KZT', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('department_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='RequestReferenceSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('columns_json', models.JSONField(blank=True, db_default=[], default=list)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('template_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('access_ids', models.JSONField(blank=True, db_default=[], default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='RequestInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('template_version_id', models.IntegerField()),
                ('initiator_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_default='draft', db_index=True, default='draft', max_length=20)),
                ('current_node_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('form_values_json', models.JSONField(blank=True, default=dict)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('requires_admin_attention', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='approvals.requestformtemplate')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='approvals.requestproject')),
            ],
        ),
        migrations.CreateModel(
            name='RequestActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=40)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='approvals.requestinstance')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(db_index=True)),
                ('kind', models.CharField(max_length=40)),
                ('channel', models.CharField(db_default='bot', default='bot', max_length=10)),
                ('dedup_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='approvals.requestinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('step_index', models.IntegerField(db_default=0, default=0)),
                ('approver_id', models.IntegerField(db_index=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('action', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request Changes'), ('delegate', 'Delegate'), ('auto_skip', 'Auto Skip')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, db_default='', default='')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_sent', models.IntegerField(db_default=0, default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.requestinstance')),
            ],
        ),
        migrations.AddField(
            model_name='requestformtemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='approvals.requestproject'),
        ),
        migrations.CreateModel(
            name='RequestProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], db_default='member', default='member', max_length=20)),
                ('granted_by', models.IntegerField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='approvals.requestproject')),
            ],
        ),
        migrations.CreateModel(
            name='RequestReferenceRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.JSONField(blank=True, db_default={}, default=dict)),
                ('instance_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='approvals.requestreferencesource')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatsDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('project_id', models.IntegerField()),
                ('template_id', models.IntegerField()),
                ('created', models.IntegerField(db_default=0, default=0)),
                ('approved', models.IntegerField(db_default=0, default=0)),
                ('rejected', models.IntegerField(db_default=0, default=0)),
                ('cancelled', models.IntegerField(db_default=0, default=0)),
                ('sum_approved_amount', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=18)),
                ('time_to_decision_seconds_sum', models.IntegerField(db_default=0, default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'project_id', 'template_id'), name='uq_request_stats_daily')],
            },
        ),
        migrations.CreateModel(
            name='RequestWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='approvals.requestinstance')),
            ],
        ),
        migrations.CreateModel(
            name='RequestFormTemplateVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('schema_json', models.JSONField()),
                ('workflow_json', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('published_by', models.IntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='approvals.requestformtemplate')),
            ],
            options={
                'ordering': ['version'],
                'constraints': [models.UniqueConstraint(fields=('template', 'version'), name='uq_request_form_template_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='requestformtemplate',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='uq_request_form_template_slug'),
        ),
        migrations.AddConstraint(
            model_name='requestprojectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user_id'), name='uq_request_project_member'),
        ),
        migrations.AddConstraint(
            model_name='requestwatcher',
            constraint=models.UniqueConstraint(fields=('request', 'user_id'), name='uq_request_watcher'),
        ),
    ]
