# Generated by Django 5.2.7 on 2026-08-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalaction',
            options={'verbose_name': 'Действие согласования', 'verbose_name_plural': 'Действия согласования'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Запись аудита', 'verbose_name_plural': 'Журнал аудита'},
        ),
        migrations.AlterModelOptions(
            name='notificationslog',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Журнал уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='requestactivity',
            options={'verbose_name': 'Событие заявки', 'verbose_name_plural': 'События заявок'},
        ),
        migrations.AlterModelOptions(
            name='requestformtemplate',
            options={'verbose_name': 'Шаблон формы', 'verbose_name_plural': 'Шаблоны форм'},
        ),
        migrations.AlterModelOptions(
            name='requestformtemplateversion',
            options={'ordering': ['version'], 'verbose_name': 'Версия шаблона формы', 'verbose_name_plural': 'Версии шаблонов форм'},
        ),
        migrations.AlterModelOptions(
            name='requestinstance',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='requestproject',
            options={'verbose_name': 'Проект заявок', 'verbose_name_plural': 'Проекты заявок'},
        ),
        migrations.AlterModelOptions(
            name='requestprojectmember',
            options={'verbose_name': 'Участник проекта', 'verbose_name_plural': 'Участники проекта'},
        ),
        migrations.AlterModelOptions(
            name='requestreferencerow',
            options={'verbose_name': 'Строка справочника', 'verbose_name_plural': 'Строки справочников'},
        ),
        migrations.AlterModelOptions(
            name='requestreferencesource',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='requeststatsdaily',
            options={'verbose_name': 'Статистика заявок за день', 'verbose_name_plural': 'Статистика заявок по дням'},
        ),
        migrations.AlterModelOptions(
            name='requestwatcher',
            options={'verbose_name': 'Наблюдатель заявки', 'verbose_name_plural': 'Наблюдатели заявок'},
        ),
    ]
