# Generated by Django 5.2.7 on 2026-09-16 07:09

from django.db import migrations, models


# ``status`` заявки → ``approval_state`` примеси signoff. «На рассмотрении»
# старого движка НЕ переносится в ``pending``: у таких заявок нет процесса
# signoff, и «на согласовании» без процесса было бы ложью. Их перезапускает
# команда ``migrate_workflows_to_signoff`` (решение: с первого этапа).
_BACKFILL = {
    "approved": "approved",
    "rejected": "rejected",
    "returned": "rework",
}


def backfill_approval_state(apps, schema_editor):
    RequestInstance = apps.get_model("approvals", "RequestInstance")
    for status, state in _BACKFILL.items():
        RequestInstance.objects.filter(status=status).update(approval_state=state)


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_approvalaction_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinstance',
            name='approval_state',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования'),
        ),
        migrations.RunPython(backfill_approval_state, migrations.RunPython.noop),
    ]
