import React, { useEffect, useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';

import api from '@/api/client';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';

// Backend contract — services/user/app/api/v1/admin.py.
// POST  /api/users/v1/admin/users/                 — create
// PATCH /api/users/v1/admin/users/{id}/            — update profile + flags
// POST  /api/users/v1/admin/users/{id}/set-password/ — admin reset
export type AdminUser = {
    id: number;
    username: string;
    email: string;
    first_name?: string;
    last_name?: string;
    patronymic?: string;
    display_name?: string;
    bio?: string;
    phone?: string;
    status: 'pending' | 'active' | 'suspended' | 'rejected' | string;
    is_staff: boolean;
    is_superuser: boolean;
    must_change_password?: boolean;
    date_joined?: string;
    last_login?: string | null;
};

type Mode = 'create' | 'edit';

type Props = {
    open: boolean;
    onOpenChange: (next: boolean) => void;
    mode: Mode;
    user?: AdminUser | null;
};

const STATUSES: AdminUser['status'][] = ['pending', 'active', 'suspended', 'rejected'];

const blank = (): FormState => ({
    username: '',
    email: '',
    password: '',
    first_name: '',
    last_name: '',
    patronymic: '',
    display_name: '',
    bio: '',
    phone: '',
    status: 'active',
    is_staff: false,
    is_superuser: false,
    must_change_password: true,
    create_mailbox: false,
    mailbox_local_part: '',
    mailbox_password: '',
});

type FormState = {
    username: string;
    email: string;
    password: string;
    first_name: string;
    last_name: string;
    patronymic: string;
    display_name: string;
    bio: string;
    phone: string;
    status: AdminUser['status'];
    is_staff: boolean;
    is_superuser: boolean;
    must_change_password: boolean;
    // Mailcow provisioning (CREATE mode only).
    create_mailbox: boolean;
    mailbox_local_part: string;
    mailbox_password: string;
};

// Mirror of services/email/app/services/mailbox_service.autogen_local_part.
// Lets the admin see the autogenerated address before submit.
const TRANSLIT: Record<string, string> = {
    а: 'a', б: 'b', в: 'v', г: 'g', д: 'd', е: 'e', ё: 'e',
    ж: 'zh', з: 'z', и: 'i', й: 'y', к: 'k', л: 'l', м: 'm',
    н: 'n', о: 'o', п: 'p', р: 'r', с: 's', т: 't', у: 'u',
    ф: 'f', х: 'h', ц: 'ts', ч: 'ch', ш: 'sh', щ: 'shch',
    ъ: '', ы: 'y', ь: '', э: 'e', ю: 'yu', я: 'ya',
};
const slug = (s: string) =>
    [...s.toLowerCase()].map((c) => TRANSLIT[c] ?? c).join('').replace(/[^a-z0-9]+/g, '');
const previewLocalPart = (firstName: string, lastName: string) => {
    const fn = slug(firstName);
    const ln = slug(lastName);
    if (fn && ln) return `${fn[0]}.${ln}`;
    return fn || ln || 'user';
};
// Strong-ish random password — 16 chars, mix of classes, no easily-confused
// punctuation. Same alphabet as the backend service.
const generatePassword = (length = 16) => {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_-+=';
    const arr = new Uint32Array(length);
    crypto.getRandomValues(arr);
    return Array.from(arr, (n) => alphabet[n % alphabet.length]).join('');
};

export const UserEditDialog: React.FC<Props> = ({ open, onOpenChange, mode, user }) => {
    const { t } = useTranslation();
    const queryClient = useQueryClient();
    const [form, setForm] = useState<FormState>(blank());
    const [resetPassword, setResetPassword] = useState('');

    // Reset form when (re-)opening or switching target user.
    useEffect(() => {
        if (!open) return;
        if (mode === 'edit' && user) {
            setForm({
                username: user.username,
                email: user.email,
                password: '',
                first_name: user.first_name || '',
                last_name: user.last_name || '',
                patronymic: user.patronymic || '',
                display_name: user.display_name || '',
                bio: user.bio || '',
                phone: user.phone || '',
                status: user.status,
                is_staff: user.is_staff,
                is_superuser: user.is_superuser,
                must_change_password: Boolean(user.must_change_password),
                // Mailbox fields are CREATE-only; in EDIT they're inert defaults.
                create_mailbox: false,
                mailbox_local_part: '',
                mailbox_password: '',
            });
        } else {
            setForm(blank());
        }
        setResetPassword('');
    }, [open, mode, user]);

    const set = <K extends keyof FormState>(key: K, value: FormState[K]) =>
        setForm((prev) => ({ ...prev, [key]: value }));

    const createMutation = useMutation({
        mutationFn: async (payload: FormState) => {
            const res = await api.post<AdminUser & {
                mailbox?: { id: number; address: string; status: string; generated_password?: string | null };
                mailbox_error?: string | null;
            }>('users/v1/admin/users/', payload);
            return res.data;
        },
        onSuccess: (created) => {
            queryClient.setQueryData<AdminUser[]>(['admin-users'], (prev) =>
                prev ? [created, ...prev] : [created],
            );
            toast.success(t('admin.users.created', 'Пользователь создан'));

            // Mailbox provisioning result — surface generated password ONCE,
            // and show errors loudly so the admin can retry from /admin/mailboxes.
            if (created.mailbox) {
                const pwd = created.mailbox.generated_password;
                if (pwd) {
                    toast.success(
                        `${t('admin.users.mailboxCreated', 'Ящик создан')}: ${created.mailbox.address}\n${t('admin.users.mailboxPasswordOnce', 'Пароль (показывается один раз)')}: ${pwd}`,
                        { duration: 30_000 },
                    );
                } else {
                    toast.success(`${t('admin.users.mailboxCreated', 'Ящик создан')}: ${created.mailbox.address}`);
                }
            }
            if (created.mailbox_error) {
                toast.error(
                    `${t('admin.users.mailboxError', 'Не удалось создать ящик')}: ${created.mailbox_error}`,
                    { duration: 15_000 },
                );
            }

            onOpenChange(false);
        },
        onError: (err: any) => {
            toast.error(err?.response?.data?.detail || t('admin.users.createError', 'Не удалось создать пользователя'));
        },
    });

    const updateMutation = useMutation({
        mutationFn: async (patch: Partial<FormState>) => {
            const id = user!.id;
            const res = await api.patch<AdminUser>(`users/v1/admin/users/${id}/`, patch);
            return res.data;
        },
        onSuccess: (updated) => {
            queryClient.setQueryData<AdminUser[]>(['admin-users'], (prev) =>
                prev?.map((u) => (u.id === updated.id ? { ...u, ...updated } : u)),
            );
            toast.success(t('admin.users.saved', 'Изменения сохранены'));
            onOpenChange(false);
        },
        onError: (err: any) => {
            toast.error(err?.response?.data?.detail || t('admin.users.saveError', 'Не удалось сохранить'));
        },
    });

    const setPasswordMutation = useMutation({
        mutationFn: async (newPassword: string) => {
            const id = user!.id;
            await api.post(`users/v1/admin/users/${id}/set-password/`, {
                new_password: newPassword,
                must_change_password: form.must_change_password,
            });
        },
        onSuccess: () => {
            toast.success(t('admin.users.passwordReset', 'Пароль сброшен'));
            setResetPassword('');
        },
        onError: (err: any) => {
            toast.error(err?.response?.data?.detail || t('admin.users.passwordResetError', 'Не удалось сбросить пароль'));
        },
    });

    const isPending = createMutation.isPending || updateMutation.isPending || setPasswordMutation.isPending;

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (mode === 'create') {
            if (!form.username || !form.email || !form.password) {
                toast.error(t('admin.users.requiredFields', 'Заполните username, email и пароль'));
                return;
            }
            if (form.password.length < 8) {
                toast.error(t('admin.users.passwordMin', 'Пароль минимум 8 символов'));
                return;
            }
            if (form.create_mailbox && form.mailbox_password && form.mailbox_password.length < 8) {
                toast.error(t('admin.users.mailboxPasswordMin', 'Пароль ящика минимум 8 символов'));
                return;
            }
            createMutation.mutate(form);
        } else {
            // PATCH: identity + profile + flags only. Strip create-mode fields.
            const { password, create_mailbox, mailbox_local_part, mailbox_password, ...patch } = form;
            void password; void create_mailbox; void mailbox_local_part; void mailbox_password;
            updateMutation.mutate(patch);
        }
    };

    const handleResetPassword = () => {
        if (resetPassword.length < 8) {
            toast.error(t('admin.users.passwordMin', 'Пароль минимум 8 символов'));
            return;
        }
        setPasswordMutation.mutate(resetPassword);
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle>
                        {mode === 'create'
                            ? t('admin.users.createTitle', 'Новый пользователь')
                            : t('admin.users.editTitle', 'Редактировать пользователя')}
                    </DialogTitle>
                    <DialogDescription>
                        {mode === 'create'
                            ? t('admin.users.createDescription', 'Создание учётной записи вручную, минуя самостоятельную регистрацию.')
                            : t('admin.users.editDescription', 'Изменение профиля, статуса и роли. Пароль сбрасывается отдельно.')}
                    </DialogDescription>
                </DialogHeader>

                <form onSubmit={handleSubmit} className="space-y-5">
                    {/* ── Identity ─────────────────────────────────────── */}
                    <section className="space-y-3">
                        <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                            {t('admin.users.sectionIdentity', 'Учётная запись')}
                        </h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                            <Field label={t('admin.users.username', 'Username')} required>
                                <Input
                                    value={form.username}
                                    onChange={(e) => set('username', e.target.value)}
                                    autoComplete="off"
                                    required
                                />
                            </Field>
                            <Field label={t('admin.users.email', 'Email')} required>
                                <Input
                                    type="email"
                                    value={form.email}
                                    onChange={(e) => set('email', e.target.value)}
                                    autoComplete="off"
                                    required
                                />
                            </Field>
                        </div>

                        {mode === 'create' && (
                            <Field
                                label={t('admin.users.password', 'Пароль')}
                                required
                                hint={t('admin.users.passwordHint', 'Минимум 8 символов. Пользователь может быть обязан сменить его при первом входе.')}
                            >
                                <Input
                                    type="password"
                                    value={form.password}
                                    onChange={(e) => set('password', e.target.value)}
                                    minLength={8}
                                    autoComplete="new-password"
                                    required
                                />
                            </Field>
                        )}
                    </section>

                    {/* ── Personal info ────────────────────────────────── */}
                    <section className="space-y-3">
                        <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                            {t('admin.users.sectionProfile', 'Профиль')}
                        </h3>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                            <Field label={t('profile.lastName', 'Фамилия')}>
                                <Input value={form.last_name} onChange={(e) => set('last_name', e.target.value)} />
                            </Field>
                            <Field label={t('profile.firstName', 'Имя')}>
                                <Input value={form.first_name} onChange={(e) => set('first_name', e.target.value)} />
                            </Field>
                            <Field label={t('profile.patronymic', 'Отчество')}>
                                <Input value={form.patronymic} onChange={(e) => set('patronymic', e.target.value)} />
                            </Field>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                            <Field label={t('profile.displayName', 'Отображаемое имя')}>
                                <Input value={form.display_name} onChange={(e) => set('display_name', e.target.value)} />
                            </Field>
                            <Field label={t('settingsPage.phone', 'Номер телефона')}>
                                <Input value={form.phone} onChange={(e) => set('phone', e.target.value)} />
                            </Field>
                        </div>
                        <Field label={t('profile.bio', 'О себе')}>
                            <Textarea
                                value={form.bio}
                                onChange={(e) => set('bio', e.target.value)}
                                className="min-h-[80px]"
                            />
                        </Field>
                    </section>

                    {/* ── Access & flags ───────────────────────────────── */}
                    <section className="space-y-3">
                        <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                            {t('admin.users.sectionAccess', 'Доступ')}
                        </h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                            <Field label={t('admin.users.statusLabel', 'Статус')}>
                                <Select
                                    value={form.status}
                                    onValueChange={(v) => set('status', v as AdminUser['status'])}
                                >
                                    <SelectTrigger>
                                        <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {STATUSES.map((s) => (
                                            <SelectItem key={s} value={s}>{s}</SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </Field>
                        </div>

                        <ToggleRow
                            label="is_staff"
                            description={t('admin.users.isStaffHint', 'Доступ к sqladmin и admin-панели.')}
                            checked={form.is_staff}
                            onCheckedChange={(v) => set('is_staff', v)}
                        />
                        <ToggleRow
                            label="is_superuser"
                            description={t('admin.users.isSuperuserHint', 'Полный административный доступ.')}
                            checked={form.is_superuser}
                            onCheckedChange={(v) => set('is_superuser', v)}
                        />
                        <ToggleRow
                            label={t('admin.users.mustChangePassword', 'Сменить пароль при входе')}
                            description={t('admin.users.mustChangePasswordHint', 'При следующем входе пользователь будет вынужден задать новый пароль.')}
                            checked={form.must_change_password}
                            onCheckedChange={(v) => set('must_change_password', v)}
                        />
                    </section>

                    {/* ── Mailcow mailbox provisioning (create mode only) ─ */}
                    {mode === 'create' && (
                        <>
                            <Separator />
                            <section className="space-y-3">
                                <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                                    {t('admin.users.sectionMailbox', 'Корпоративная почта')}
                                </h3>
                                <ToggleRow
                                    label={t('admin.users.createMailbox', 'Создать ящик на корпоративном домене')}
                                    description={t('admin.users.createMailboxHint', 'После создания пользователя email-service провизионирует ящик в Mailcow.')}
                                    checked={form.create_mailbox}
                                    onCheckedChange={(v) => set('create_mailbox', v)}
                                />
                                {form.create_mailbox && (
                                    <div className="space-y-3 rounded-md border bg-muted/30 p-3">
                                        <Field
                                            label={t('admin.users.mailboxLocalPart', 'Логин (до @домен)')}
                                            hint={
                                                form.mailbox_local_part
                                                    ? null
                                                    : `${t('admin.users.mailboxAutogenHint', 'Будет сгенерирован из ФИО')}: ${previewLocalPart(form.first_name, form.last_name)}`
                                            }
                                        >
                                            <Input
                                                value={form.mailbox_local_part}
                                                onChange={(e) => set('mailbox_local_part', e.target.value.toLowerCase())}
                                                placeholder={previewLocalPart(form.first_name, form.last_name)}
                                                autoComplete="off"
                                            />
                                        </Field>
                                        <Field
                                            label={t('admin.users.mailboxPassword', 'Пароль ящика')}
                                            hint={t('admin.users.mailboxPasswordHint', 'Оставьте пустым — сгенерируется случайный, пароль покажется один раз после создания.')}
                                        >
                                            <div className="flex gap-2">
                                                <Input
                                                    type="text"
                                                    value={form.mailbox_password}
                                                    onChange={(e) => set('mailbox_password', e.target.value)}
                                                    placeholder={t('admin.users.mailboxPasswordPlaceholder', 'пусто = автогенерация')}
                                                    autoComplete="off"
                                                    minLength={form.mailbox_password ? 8 : undefined}
                                                />
                                                <Button
                                                    type="button"
                                                    variant="secondary"
                                                    onClick={() => set('mailbox_password', generatePassword())}
                                                >
                                                    {t('admin.users.mailboxGenPassword', 'Сгенерировать')}
                                                </Button>
                                            </div>
                                        </Field>
                                    </div>
                                )}
                            </section>
                        </>
                    )}

                    {/* ── Password reset (edit mode only) ──────────────── */}
                    {mode === 'edit' && (
                        <>
                            <Separator />
                            <section className="space-y-3">
                                <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                                    {t('admin.users.sectionPasswordReset', 'Сброс пароля')}
                                </h3>
                                <p className="text-xs text-muted-foreground">
                                    {t('admin.users.passwordResetHint', 'Установите временный пароль. Пользователь сможет сменить его при входе, если включён флаг выше.')}
                                </p>
                                <div className="flex flex-col sm:flex-row gap-2">
                                    <Input
                                        type="password"
                                        placeholder={t('admin.users.newPasswordPlaceholder', 'Новый пароль (мин. 8 символов)')}
                                        value={resetPassword}
                                        onChange={(e) => setResetPassword(e.target.value)}
                                        autoComplete="new-password"
                                        minLength={8}
                                    />
                                    <Button
                                        type="button"
                                        variant="secondary"
                                        onClick={handleResetPassword}
                                        disabled={!resetPassword || setPasswordMutation.isPending}
                                    >
                                        {setPasswordMutation.isPending
                                            ? t('common.saving', 'Сохранение...')
                                            : t('admin.users.resetPasswordBtn', 'Сбросить пароль')}
                                    </Button>
                                </div>
                            </section>
                        </>
                    )}

                    <DialogFooter className="gap-2">
                        <Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={isPending}>
                            {t('profile.cancel', 'Отмена')}
                        </Button>
                        <Button type="submit" disabled={isPending}>
                            {isPending
                                ? t('common.saving', 'Сохранение...')
                                : mode === 'create'
                                    ? t('admin.users.createBtn', 'Создать')
                                    : t('profile.save', 'Сохранить')}
                        </Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    );
};

// ── Small layout helpers ────────────────────────────────────────────────────

const Field: React.FC<{
    label: React.ReactNode;
    required?: boolean;
    hint?: React.ReactNode;
    children: React.ReactNode;
}> = ({ label, required, hint, children }) => (
    <div className="space-y-1.5">
        <Label className="text-sm">
            {label}
            {required && <span className="text-destructive ml-0.5">*</span>}
        </Label>
        {children}
        {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
    </div>
);

const ToggleRow: React.FC<{
    label: React.ReactNode;
    description?: React.ReactNode;
    checked: boolean;
    onCheckedChange: (v: boolean) => void;
}> = ({ label, description, checked, onCheckedChange }) => (
    <div className="flex items-start justify-between gap-3 py-2">
        <div className="space-y-0.5">
            <Label className="text-sm">{label}</Label>
            {description && <p className="text-xs text-muted-foreground">{description}</p>}
        </div>
        <Switch checked={checked} onCheckedChange={onCheckedChange} />
    </div>
);

export default UserEditDialog;
