# Generated by Django 5.2.7 on 2026-07-21 21:54

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=50)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('encrypted_access_token', models.TextField()),
                ('encrypted_refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('type', models.CharField(choices=[('corporate', 'Корпоративный (Mailcow)'), ('personal', 'Личный (OAuth)')], max_length=16)),
                ('provider', models.CharField(choices=[('mailcow', 'Mailcow'), ('google', 'Google'), ('microsoft', 'Microsoft')], max_length=16)),
                ('address', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(db_default=False, default=False)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('mailbox_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('sync_state', models.JSONField(db_default={}, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('watch_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('oauth_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_account', to='mail.oauthtoken', unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'address'), name='uq_email_accounts_user_address'), models.CheckConstraint(condition=models.Q(('type__in', ['corporate', 'personal'])), name='ck_email_accounts_type'), models.CheckConstraint(condition=models.Q(('provider__in', ['mailcow', 'google', 'microsoft'])), name='ck_email_accounts_provider'), models.CheckConstraint(condition=models.Q(models.Q(('mailbox_id__isnull', False), ('oauth_token_id__isnull', True), ('type', 'corporate')), models.Q(('mailbox_id__isnull', True), ('oauth_token_id__isnull', False), ('type', 'personal')), _connector='OR'), name='ck_email_accounts_type_consistency')],
            },
        ),
    ]
