# Generated by Django 5.2.7 on 2026-07-21 22:31

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('folder', models.CharField(choices=[('inbox', 'Входящие'), ('sent', 'Отправленные'), ('drafts', 'Черновики'), ('trash', 'Корзина'), ('archive', 'Архив'), ('spam', 'Спам'), ('outbox', 'Исходящие')], default='inbox', max_length=50)),
                ('provider_folder', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=512)),
                ('snippet', models.CharField(blank=True, default='', max_length=255)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('sender_email', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('to_recipients', models.JSONField(default=list)),
                ('cc_recipients', models.JSONField(default=list)),
                ('bcc_recipients', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('dlp_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mail.emailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_metadata_id', models.UUIDField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.emailmessage')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_statuses', to='mail.emailmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['user_id', 'account', 'folder', '-date'], name='mail_emailm_user_id_fed2d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('account', 'message_id'), name='ux_email_messages_account_message'),
        ),
    ]
