# Generated by Django 5.2.7 on 2026-07-21 23:14

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_emailmessage_emailattachment_recipientstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionedMailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('local_part', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'В архиве'), ('deleted', 'Удалён'), ('error', 'Ошибка')], db_index=True, default='active', max_length=16)),
                ('quota_mb', models.IntegerField(default=1024)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('encrypted_smtp_app_password', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        # ck_email_accounts_type_consistency ссылается на mailbox_id — Postgres
        # молча дропает CHECK-констрейнт, когда сама колонка удаляется
        # (RemoveField ниже), а Django НЕ детектирует это как изменение
        # Meta.constraints (сам Q-объект текстуально не поменялся), поэтому
        # ничего не пересоздаёт автоматически. Явно снимаем/пересоздаём здесь
        # — иначе констрейнт молча исчезает из схемы (обнаружено прогоном
        # test_email_account_type_consistency_rejects_* на реальном Postgres).
        migrations.RemoveConstraint(
            model_name='emailaccount',
            name='ck_email_accounts_type_consistency',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='mailbox_id',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_account', to='mail.provisionedmailbox', unique=True),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('mailbox_id__isnull', False), ('oauth_token_id__isnull', True), ('type', 'corporate')),
                    models.Q(('mailbox_id__isnull', True), ('oauth_token_id__isnull', False), ('type', 'personal')),
                    _connector='OR',
                ),
                name='ck_email_accounts_type_consistency',
            ),
        ),
    ]
