# Generated by Django 5.2.7 on 2026-08-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_mail_periodic_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Запись аудита', 'verbose_name_plural': 'Журнал аудита'},
        ),
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'verbose_name': 'Почтовый аккаунт', 'verbose_name_plural': 'Почтовые аккаунты'},
        ),
        migrations.AlterModelOptions(
            name='emailattachment',
            options={'verbose_name': 'Вложение письма', 'verbose_name_plural': 'Вложения писем'},
        ),
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AlterModelOptions(
            name='oauthtoken',
            options={'verbose_name': 'OAuth-токен', 'verbose_name_plural': 'OAuth-токены'},
        ),
        migrations.AlterModelOptions(
            name='provisionedmailbox',
            options={'verbose_name': 'Выданный ящик', 'verbose_name_plural': 'Выданные ящики'},
        ),
        migrations.AlterModelOptions(
            name='recipientstatus',
            options={'verbose_name': 'Статус получателя', 'verbose_name_plural': 'Статусы получателей'},
        ),
    ]
