# Generated by Django 5.2.7 on 2026-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_auditlog_options_alter_emailaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailaccount',
            name='ck_email_accounts_provider',
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(choices=[('mailcow', 'Mailcow'), ('imap', 'IMAP/SMTP'), ('google', 'Google'), ('microsoft', 'Microsoft')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['mailcow', 'imap', 'google', 'microsoft'])), name='ck_email_accounts_provider'),
        ),
    ]
