# Generated by Django 5.2.7 on 2026-08-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_reconcile_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provisioner', models.CharField(blank=True, choices=[('', 'Из настроек окружения'), ('auto', 'Автоматически'), ('mailcow', 'Mailcow API'), ('imap', 'IMAP/SMTP'), ('none', 'Не подключён')], default='', max_length=16, verbose_name='Режим провижининга')),
                ('domain', models.CharField(blank=True, default='', max_length=255, verbose_name='Домен ящиков')),
                ('imap_host', models.CharField(blank=True, default='', max_length=255)),
                ('imap_port', models.IntegerField(blank=True, null=True)),
                ('imap_ssl', models.BooleanField(blank=True, null=True)),
                ('imap_starttls', models.BooleanField(blank=True, null=True)),
                ('imap_tls_server_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_ssl', models.BooleanField(blank=True, null=True)),
                ('smtp_starttls', models.BooleanField(blank=True, null=True)),
                ('mailcow_api_url', models.CharField(blank=True, default='', max_length=500)),
                ('encrypted_mailcow_api_key', models.TextField(blank=True, default='')),
                ('sync_folders', models.CharField(blank=True, default='', max_length=500)),
                ('sync_push_flags', models.BooleanField(blank=True, null=True)),
                ('allow_self_service', models.BooleanField(default=False, verbose_name='Самоподключение ящиков сотрудниками')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Настройки почтового сервера',
                'verbose_name_plural': 'Настройки почтового сервера',
            },
        ),
    ]
