# Generated by Django 5.2.7 on 2026-08-04 11:41

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_mail_server_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImapAccountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_ssl', models.BooleanField(default=True)),
                ('imap_starttls', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_ssl', models.BooleanField(default=False)),
                ('smtp_starttls', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'IMAP-реквизиты аккаунта',
                'verbose_name_plural': 'IMAP-реквизиты аккаунтов',
            },
        ),
        migrations.RemoveConstraint(
            model_name='emailaccount',
            name='ck_email_accounts_type_consistency',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to='mail.imapaccountsettings'),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mailbox_id__isnull', False), ('oauth_token_id__isnull', True), ('type', 'corporate')), models.Q(('imap_settings__isnull', True), ('mailbox_id__isnull', True), ('oauth_token_id__isnull', False), ('type', 'personal')), models.Q(('imap_settings__isnull', False), ('mailbox_id__isnull', True), ('oauth_token_id__isnull', True), ('type', 'personal')), _connector='OR'), name='ck_email_accounts_type_consistency'),
        ),
    ]
