# Generated by Django 5.2.7 on 2026-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_imap_account_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserverconfig',
            name='local_part_pattern',
            field=models.CharField(blank=True, choices=[('', 'Из настроек окружения'), ('first.last', 'sanzhar.inamzhanov'), ('f.last', 's.inamzhanov'), ('firstlast', 'sanzharinamzhanov'), ('first_last', 'sanzhar_inamzhanov'), ('flast', 'sinamzhanov'), ('last.first', 'inamzhanov.sanzhar'), ('first', 'sanzhar')], default='', max_length=16, verbose_name='Шаблон адреса'),
        ),
    ]
