# Generated by Django 5.2.7 on 2026-08-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_local_part_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='signature',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
    ]
