# Generated by Django 5.2.7 on 2026-09-26 19:27

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('node_key', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'verbose_name': 'Группа статей',
                'verbose_name_plural': 'Группы статей',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, default='', max_length=8)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='MrpValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('date_from', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'МРП',
                'verbose_name_plural': 'МРП',
                'ordering': ('date_from',),
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('code', models.CharField(max_length=16, unique=True)),
                ('short_name', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('country_code', models.CharField(max_length=2)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ставка НДС',
                'verbose_name_plural': 'Ставки НДС',
                'ordering': ('country_code', 'date_from'),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('ext_1c_ref', models.CharField(blank=True, default='', max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='refdata.article')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='refdata.articlegroup')),
            ],
            options={
                'verbose_name': 'Статья бюджета',
                'verbose_name_plural': 'Статьи бюджета',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('currency_code', models.CharField(max_length=3)),
                ('on_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(choices=[('nbrk', 'НБРК'), ('manual', 'Вручную')], max_length=8)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'constraints': [models.UniqueConstraint(fields=('currency_code', 'on_date'), name='uq_refdata_rate_day')],
            },
        ),
    ]
