# Generated by Django 5.2.7 on 2026-10-02 13:01

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0003_nbrk_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('date', models.DateField(unique=True)),
                ('day_type', models.CharField(db_default='working', default='working', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('working_days_since_epoch', models.IntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Производственный день',
                'verbose_name_plural': 'Производственные дни',
                'ordering': ('date',),
            },
        ),
    ]
