# Generated by Django 5.2.7 on 2026-07-21 07:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inventory_no', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_default=True, db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(db_default='#808080', default='#808080', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('day_type', models.CharField(db_default='working', default='working', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('working_days_since_epoch', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_default='active', default='active', max_length=20)),
                ('color', models.CharField(db_default='#3b82f6', default='#3b82f6', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('department_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='TaskSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('current_value', models.IntegerField(db_default=0, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(db_default='#6b7280', default='#6b7280', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_system', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('is_all_day', models.BooleanField(db_default=True, default=True)),
                ('event_type', models.CharField(db_default='personal', db_index=True, default='personal', max_length=20)),
                ('conference_room_id', models.CharField(blank=True, max_length=64, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('is_global', models.BooleanField(db_default=False, default=False)),
                ('department_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['personal', 'department', 'common', 'conference'])), name='ck_calendar_event_type'), models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='ck_calendar_event_range')],
            },
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField()),
                ('is_cancelled', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='tasks.calendarevent')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=20, unique=True)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('trivial', 'Trivial')], db_default='medium', default='medium', max_length=20)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'Todo'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_default='todo', db_index=True, default='todo', max_length=20)),
                ('progress_percent', models.SmallIntegerField(db_default=0, default=0)),
                ('reporter_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('assignee_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('supervisor_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('department_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_working_days', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.label')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasks.task')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.project')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasktype')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(db_index=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('verb', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('actor_avatar_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=32, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_by_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('rsvp_status', models.CharField(db_default='pending', default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tasks.calendarevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'user_id'), name='uq_calendar_event_participant'), models.CheckConstraint(condition=models.Q(('rsvp_status__in', ['pending', 'accepted', 'declined'])), name='ck_calendar_event_participant_status')],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('collaborator', 'Collaborator')], db_default='collaborator', default='collaborator', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='tasks.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'user_id'), name='uq_task_assignee')],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('allocation', models.IntegerField(db_default=100, default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.equipment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='tasks.task')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('employee_id__isnull', True), ('equipment__isnull', False)), models.Q(('employee_id__isnull', False), ('equipment__isnull', True)), _connector='OR'), name='ck_assignment_exactly_one_resource'), models.UniqueConstraint(fields=('task', 'employee_id', 'equipment'), name='uq_task_assignment')],
            },
        ),
        migrations.CreateModel(
            name='TaskDelegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('granted_by_id', models.IntegerField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='tasks.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'user_id'), name='uq_task_delegate')],
            },
        ),
        migrations.CreateModel(
            name='TaskDepartmentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(db_index=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='tasks.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'department_id'), name='uq_task_department_link')],
            },
        ),
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('blocks', 'Blocks'), ('is_blocked_by', 'Is Blocked By'), ('relates_to', 'Relates To'), ('duplicates', 'Duplicates')], max_length=20)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='tasks.task')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='tasks.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'link_type'), name='uq_task_link'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='ck_task_link_not_self')],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('due_date__isnull', True), ('start_date__lte', models.F('due_date')), _connector='OR'), name='ck_task_dates'),
        ),
        migrations.AddConstraint(
            model_name='taskwatcher',
            constraint=models.UniqueConstraint(fields=('task', 'user_id'), name='uq_task_watcher'),
        ),
    ]
