# Generated by Django 5.2.7 on 2026-07-29 09:12

"""Субподрядчики: организации, их представители, привлечения на объекты.

Только справочник — вход в систему для подрядчиков этой миграцией НЕ
включается. ``ContractorWorker.user_id`` заводится пустым и остаётся пустым:
ничто его не пишет, и ни одна ветка авторизации его не читает. Колонка
существует, чтобы следующая итерация (учётки + уровни как реальные права)
обошлась без миграции вовсе.

Всё аддитивно, поэтому выкат однофазный. Единственная операция, способная
упасть, — ``ck_equipment_contractor_owner``, и она стоит последней, чтобы
падать в одиночку. Упасть она на легаси-данных не может по построению:
``ownership`` приезжает с ``db_default='own'``, а условие ограничивает
только строки со значением ``contractor``.

``AddConstraint`` берёт ACCESS EXCLUSIVE и сканирует ``tasks_equipment``
целиком. Таблица справочника крошечная — это нормально; на ``tasks_task``
такой приём уже потребовал бы отдельного разговора.
"""

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_iin', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, db_default='', default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted'), ('archived', 'Archived')], db_default='active', db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='ContractorEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(blank=True, max_length=64, null=True)),
                ('scope', models.TextField(blank=True, db_default='', default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True, db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='ContractorWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('position_title', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], db_default='junior', db_index=True, default='junior', max_length=20)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('is_active', models.BooleanField(db_default=True, db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='ownership',
            field=models.CharField(choices=[('own', 'Собственная'), ('contractor', 'Подрядчика'), ('rented', 'Аренда')], db_default='own', db_index=True, default='own', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='tasks.contractor'),
        ),
        migrations.AddField(
            model_name='task',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.contractor'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ownership', 'contractor'), _negated=True), ('contractor__isnull', False), _connector='OR'), name='ck_equipment_contractor_owner'),
        ),
        migrations.AddField(
            model_name='contractorengagement',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='tasks.contractor'),
        ),
        migrations.AddField(
            model_name='contractorengagement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_engagements', to='tasks.project'),
        ),
        migrations.AddField(
            model_name='contractorengagement',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_engagements', to='tasks.site'),
        ),
        migrations.AddField(
            model_name='contractorworker',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='tasks.contractor'),
        ),
        migrations.AddField(
            model_name='task',
            name='contractor_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.contractorworker'),
        ),
        migrations.AddConstraint(
            model_name='contractorengagement',
            constraint=models.UniqueConstraint(fields=('contractor', 'project', 'site'), name='uq_contractor_engagement'),
        ),
        migrations.AddConstraint(
            model_name='contractorengagement',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', False), ('site__isnull', False), _connector='OR'), name='ck_engagement_target'),
        ),
        migrations.AddConstraint(
            model_name='contractorengagement',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='ck_engagement_dates'),
        ),
    ]
