# Generated by Django 5.2.7 on 2026-07-29 09:42

"""uq_contractor_engagement: NULLS NOT DISTINCT.

Констрейнт из 0005 не работал ровно в самом частом случае. В SQL два NULL
считаются РАЗНЫМИ, поэтому обычный UNIQUE(contractor, project, site)
пропускал сколько угодно строк вида (подрядчик, NULL, объект) — то есть
дубли привлечения на объект вне конкретного проекта. Поймано тестом
``test_engagement_is_unique_per_contractor_project_site``, который ожидал
отказа и получил 201.

Пересоздание констрейнта, данные не трогаются. Если в базе уже успели
появиться дубли, ``AddConstraint`` упадёт — тогда их надо сначала
схлопнуть; на локальной базе таких строк нет.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_contractors'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contractorengagement',
            name='uq_contractor_engagement',
        ),
        migrations.AddConstraint(
            model_name='contractorengagement',
            constraint=models.UniqueConstraint(fields=('contractor', 'project', 'site'), name='uq_contractor_engagement', nulls_distinct=False),
        ),
    ]
