# Generated by Django 5.2.7 on 2026-07-30 06:51

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_equipment_category_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('order', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('suspended', 'Suspended'), ('done', 'Done')], db_default='planned', db_index=True, default='planned', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tasks.site')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='site_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.siteblock'),
        ),
        migrations.CreateModel(
            name='SiteBlockVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='tasks.siteblock')),
                ('volume_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='block_volumes', to='tasks.workvolumetype')),
            ],
        ),
        migrations.CreateModel(
            name='TaskVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('completed_quantity', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='tasks.task')),
                ('volume_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_volumes', to='tasks.workvolumetype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='siteblock',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uq_site_block_name'),
        ),
        migrations.AddConstraint(
            model_name='siteblock',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='uq_site_block_code'),
        ),
        migrations.AddConstraint(
            model_name='siteblock',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='ck_site_block_dates'),
        ),
        migrations.AddConstraint(
            model_name='siteblockvolume',
            constraint=models.UniqueConstraint(fields=('block', 'volume_type'), name='uq_site_block_volume'),
        ),
        migrations.AddConstraint(
            model_name='siteblockvolume',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gte', 0)), name='ck_site_block_volume_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='taskvolume',
            constraint=models.UniqueConstraint(fields=('task', 'volume_type'), name='uq_task_volume'),
        ),
        migrations.AddConstraint(
            model_name='taskvolume',
            constraint=models.CheckConstraint(condition=models.Q(('completed_quantity__gte', 0), ('planned_quantity__gte', 0)), name='ck_task_volume_non_negative'),
        ),
    ]
