# Generated by Django 5.2.7 on 2026-07-30 07:08

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_site_blocks_and_volumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, db_default='', default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_default='active', db_index=True, default='active', max_length=20)),
                ('color', models.CharField(db_default='#8b5cf6', default='#8b5cf6', max_length=20)),
                ('order', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('planned_working_days', models.IntegerField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('department_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='contractorengagement',
            name='ck_engagement_target',
        ),
        migrations.RemoveConstraint(
            model_name='contractorengagement',
            name='uq_contractor_engagement',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='tasks.project'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roadmaps', to='tasks.site'),
        ),
        migrations.AddField(
            model_name='contractorengagement',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_engagements', to='tasks.roadmap'),
        ),
        migrations.AddField(
            model_name='task',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.roadmap'),
        ),
        migrations.AddConstraint(
            model_name='contractorengagement',
            constraint=models.UniqueConstraint(fields=('contractor', 'project', 'site', 'roadmap'), name='uq_contractor_engagement', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='contractorengagement',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', False), ('site__isnull', False), ('roadmap__isnull', False), _connector='OR'), name='ck_engagement_target'),
        ),
        migrations.AddConstraint(
            model_name='roadmap',
            constraint=models.UniqueConstraint(fields=('project', 'site', 'name'), name='uq_roadmap_name'),
        ),
        migrations.AddConstraint(
            model_name='roadmap',
            constraint=models.CheckConstraint(condition=models.Q(('planned_start_date__isnull', True), ('planned_end_date__isnull', True), ('planned_start_date__lte', models.F('planned_end_date')), _connector='OR'), name='ck_roadmap_planned_dates'),
        ),
    ]
