# Generated by Django 5.2.7 on 2026-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_roadmap_on_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_production_calendar',
            field=models.BooleanField(db_default=False, default=False, help_text='Считать сроки в рабочих днях (по производственному календарю), а не в календарных.'),
        ),
    ]
