# Generated by Django 5.2.7 on 2026-08-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_daily_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'verbose_name': 'Событие календаря', 'verbose_name_plural': 'События календаря'},
        ),
        migrations.AlterModelOptions(
            name='calendareventparticipant',
            options={'verbose_name': 'Участник события', 'verbose_name_plural': 'Участники событий'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Подрядчик', 'verbose_name_plural': 'Подрядчики'},
        ),
        migrations.AlterModelOptions(
            name='contractorengagement',
            options={'verbose_name': 'Привлечение подрядчика', 'verbose_name_plural': 'Привлечения подрядчиков'},
        ),
        migrations.AlterModelOptions(
            name='contractorworker',
            options={'verbose_name': 'Работник подрядчика', 'verbose_name_plural': 'Работники подрядчиков'},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': 'Ежедневный отчёт', 'verbose_name_plural': 'Ежедневные отчёты'},
        ),
        migrations.AlterModelOptions(
            name='dailyreportrevision',
            options={'ordering': ['revision_no'], 'verbose_name': 'Версия отчёта', 'verbose_name_plural': 'Версии отчётов'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Техника', 'verbose_name_plural': 'Техника'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name': 'Категория техники', 'verbose_name_plural': 'Категории техники'},
        ),
        migrations.AlterModelOptions(
            name='eventexception',
            options={'verbose_name': 'Исключение события', 'verbose_name_plural': 'Исключения событий'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='productionday',
            options={'verbose_name': 'Производственный день', 'verbose_name_plural': 'Производственные дни'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectsite',
            options={'verbose_name': 'Площадка проекта', 'verbose_name_plural': 'Площадки проектов'},
        ),
        migrations.AlterModelOptions(
            name='resourceallocation',
            options={'verbose_name': 'Выделение ресурса', 'verbose_name_plural': 'Выделение ресурсов'},
        ),
        migrations.AlterModelOptions(
            name='resourcerequirement',
            options={'verbose_name': 'Потребность в ресурсе', 'verbose_name_plural': 'Потребности в ресурсах'},
        ),
        migrations.AlterModelOptions(
            name='roadmap',
            options={'verbose_name': 'Дорожная карта', 'verbose_name_plural': 'Дорожные карты'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AlterModelOptions(
            name='siteblock',
            options={'verbose_name': 'Блок площадки', 'verbose_name_plural': 'Блоки площадок'},
        ),
        migrations.AlterModelOptions(
            name='siteblockvolume',
            options={'verbose_name': 'Объём по блоку', 'verbose_name_plural': 'Объёмы по блокам'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskactivity',
            options={'verbose_name': 'Событие задачи', 'verbose_name_plural': 'События задач'},
        ),
        migrations.AlterModelOptions(
            name='taskassignee',
            options={'verbose_name': 'Исполнитель задачи', 'verbose_name_plural': 'Исполнители задач'},
        ),
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'verbose_name': 'Вложение задачи', 'verbose_name_plural': 'Вложения задач'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'verbose_name': 'Комментарий к задаче', 'verbose_name_plural': 'Комментарии к задачам'},
        ),
        migrations.AlterModelOptions(
            name='taskdelegate',
            options={'verbose_name': 'Делегат задачи', 'verbose_name_plural': 'Делегаты задач'},
        ),
        migrations.AlterModelOptions(
            name='taskdepartmentlink',
            options={'verbose_name': 'Отдел задачи', 'verbose_name_plural': 'Отделы задач'},
        ),
        migrations.AlterModelOptions(
            name='tasklink',
            options={'verbose_name': 'Связь задач', 'verbose_name_plural': 'Связи задач'},
        ),
        migrations.AlterModelOptions(
            name='tasksequence',
            options={'verbose_name': 'Нумератор задач', 'verbose_name_plural': 'Нумераторы задач'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'Тип задачи', 'verbose_name_plural': 'Типы задач'},
        ),
        migrations.AlterModelOptions(
            name='taskvolume',
            options={'verbose_name': 'Объём работ', 'verbose_name_plural': 'Объёмы работ'},
        ),
        migrations.AlterModelOptions(
            name='taskwatcher',
            options={'verbose_name': 'Наблюдатель задачи', 'verbose_name_plural': 'Наблюдатели задач'},
        ),
        migrations.AlterModelOptions(
            name='workrole',
            options={'verbose_name': 'Рабочая роль', 'verbose_name_plural': 'Рабочие роли'},
        ),
        migrations.AlterModelOptions(
            name='workvolumetype',
            options={'verbose_name': 'Вид объёма работ', 'verbose_name_plural': 'Виды объёмов работ'},
        ),
    ]
