# Generated by Django 5.2.7 on 2026-08-14 06:56

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStaffReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('work_date', models.DateField(db_index=True)),
                ('comment', models.TextField(blank=True, db_default='', default='')),
                ('current_revision', models.PositiveSmallIntegerField(db_default=1, default=1)),
                ('is_deleted', models.BooleanField(db_default=False, db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_reports', to='tasks.project')),
                ('site_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_reports', to='tasks.siteblock')),
            ],
            options={
                'verbose_name': 'Отчёт по персоналу проекта',
                'verbose_name_plural': 'Отчёты по персоналу проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectStaffReportLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.PositiveSmallIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tasks.projectstaffreport')),
                ('work_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_report_lines', to='tasks.workrole')),
            ],
            options={
                'verbose_name': 'Строка отчёта по персоналу',
                'verbose_name_plural': 'Строки отчёта по персоналу',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStaffReportRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveSmallIntegerField()),
                ('work_date', models.DateField()),
                ('comment', models.TextField(blank=True, db_default='', default='')),
                ('total_headcount', models.PositiveIntegerField(db_default=0, default=0)),
                ('lines', models.JSONField(blank=True, db_default=[], default=list)),
                ('edited_by_id', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tasks.projectstaffreport')),
            ],
            options={
                'verbose_name': 'Версия отчёта по персоналу',
                'verbose_name_plural': 'Версии отчётов по персоналу',
                'ordering': ['revision_no'],
            },
        ),
        migrations.AddIndex(
            model_name='projectstaffreport',
            index=models.Index(fields=['project', 'work_date'], name='ix_staff_report_project_date'),
        ),
        migrations.AddIndex(
            model_name='projectstaffreport',
            index=models.Index(fields=['site_block', 'work_date'], name='ix_staff_report_block_date'),
        ),
        migrations.AddConstraint(
            model_name='projectstaffreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'site_block', 'work_date'), name='uq_staff_report_project_block_date'),
        ),
        migrations.AddConstraint(
            model_name='projectstaffreportline',
            constraint=models.UniqueConstraint(fields=('report', 'work_role'), name='uq_staff_report_line_role'),
        ),
        migrations.AddConstraint(
            model_name='projectstaffreportline',
            constraint=models.CheckConstraint(condition=models.Q(('headcount__gte', 0)), name='ck_staff_report_line_headcount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='projectstaffreportrevision',
            constraint=models.UniqueConstraint(fields=('report', 'revision_no'), name='uq_staff_report_revision'),
        ),
    ]
