# Generated by Django 5.2.7 on 2026-08-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_project_staff_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='contractorengagement',
            options={'verbose_name': 'Привлечение партнёра', 'verbose_name_plural': 'Привлечения партнёров'},
        ),
        migrations.AlterModelOptions(
            name='contractorworker',
            options={'verbose_name': 'Работник партнёра', 'verbose_name_plural': 'Работники партнёров'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ownership',
            field=models.CharField(choices=[('own', 'Собственная'), ('contractor', 'Партнёра'), ('rented', 'Аренда')], db_default='own', db_index=True, default='own', max_length=20),
        ),
    ]
