# Generated by Django 5.2.7 on 2026-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_contractor_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'conference'), models.Q(('conference_room_id', None), _negated=True)), fields=('conference_room_id',), name='uq_calendar_conference_room'),
        ),
    ]
