# Generated by Django 5.2.7 on 2026-09-23 06:07
"""Связь партнёра с контрагентом и привлечения — с договором «Договоров».

Только расширение (expand): две nullable-колонки и расширение varchar —
код предыдущей версии их не замечает, поэтому компании могут стоять по обе
стороны этой миграции (tenant-аппка, см. CLAUDE.md «expand/contract»).
Ни ``Contractor``, ни ``ContractorEngagement`` в ``holding.HOLDING_MODELS``
нет, так что смена ширины ``contract_no`` не упирается в представления.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_tasks_periodic_tasks_use_dispatchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='counterparty_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contractorengagement',
            name='agreement_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractorengagement',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
