# Generated by Django 5.2.7 on 2026-09-17 07:51

"""Читатели сводных представлений холдинга для домена tasks (блок H).

Четыре ``CreateModel`` с ``managed=False`` НЕ выполняют DDL: они лишь
записывают состояние миграций для ``HoldingProject``/``HoldingSite``/
``HoldingTask``/``HoldingDailyReport`` (apps/tasks/holding_models.py),
чтобы ``makemigrations --check`` оставался чист. Физические таблицы под
именами ``tasks_project``/``tasks_site``/``tasks_task``/``tasks_dailyreport``
в схеме ``holding`` создаёт (и пересобирает)
``apps.companies.services.holding_views``, а не эта миграция.

``base_manager_name = "objects"`` записан сразу, одной миграцией (в hr на
это ушла отдельная 0037): это отслеживаемая опция ``Meta``, без неё
``Model._base_manager`` обходил бы сторож контекста холдинга.

Expand-only: миграция ничего не меняет в схемах компаний, поэтому порядок
выкатки относительно ``migrate_companies`` безразличен.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_tasks_periodic_tasks_use_dispatchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=63)),
                ('work_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tasks_dailyreport',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HoldingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tasks_project',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HoldingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tasks_site',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HoldingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=63)),
                ('status', models.CharField(max_length=20)),
                ('due_date', models.DateField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tasks_task',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
