# Generated by Django 5.2.7 on 2026-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_merge_contractor_link_holding_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_ref',
            field=models.CharField(blank=True, db_default='', default='', max_length=36),
        ),
    ]
