# Generated by Django 5.2.7 on 2026-10-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_project_ref_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='bpp_counterparty_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=36),
        ),
        migrations.AddConstraint(
            model_name='contractor',
            constraint=models.UniqueConstraint(condition=models.Q(('bpp_counterparty_id', ''), _negated=True), fields=('bpp_counterparty_id',), name='uq_tasks_contractor_bpp_cp'),
        ),
    ]
