# Generated by Django 5.2.7 on 2026-08-27 09:21

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]([a-z0-9-]{0,30}[a-z0-9])?$', 'Только строчные латинские буквы, цифры и дефис; не начинается и не заканчивается дефисом; до 32 символов.')])),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('holding', 'Холдинг'), ('regional', 'Региональная'), ('service', 'Сервисная')], max_length=16)),
                ('country', models.CharField(blank=True, db_default='', default='', max_length=2)),
                ('status', models.CharField(choices=[('active', 'Действует'), ('archived', 'В архиве')], db_default='active', db_index=True, default='active', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='companies.company')),
                ('successor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to='companies.company')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('is_default', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
            ],
            options={
                'verbose_name': 'Членство в компании',
                'verbose_name_plural': 'Членство в компаниях',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'company'), name='uniq_membership')],
            },
        ),
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(db_default=True, default=True)),
                ('message', models.CharField(db_default='Модуль недоступен для этой компании', default='Модуль недоступен для этой компании', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='companies.company')),
            ],
            options={
                'verbose_name': 'Модуль компании',
                'verbose_name_plural': 'Модули компаний',
                'constraints': [models.UniqueConstraint(fields=('company', 'app_label'), name='uniq_company_module')],
            },
        ),
        migrations.CreateModel(
            name='CompanySchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=32)),
                ('applied_migration', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('target_migration', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, db_default='', default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_versions', to='companies.company')),
            ],
            options={
                'verbose_name': 'Версия схемы компании',
                'verbose_name_plural': 'Версии схем компаний',
                'constraints': [models.UniqueConstraint(fields=('company', 'app_label'), name='uniq_schema_version')],
            },
        ),
        migrations.CreateModel(
            name='CompanyServiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_services', to='companies.company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_services', to='companies.company')),
            ],
            options={
                'verbose_name': 'Связь по услугам',
                'verbose_name_plural': 'Связи по услугам',
                'constraints': [models.UniqueConstraint(fields=('provider', 'consumer'), name='uniq_service_link'), models.CheckConstraint(condition=models.Q(('provider', models.F('consumer')), _negated=True), name='service_link_not_self')],
            },
        ),
    ]
