# Generated by Django 5.2.7 on 2026-08-28 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^(?!www$)[a-z]([a-z0-9-]{0,30}[a-z0-9])?$', 'Только строчные латинские буквы, цифры и дефис; первый символ — буква; не заканчивается дефисом; до 32 символов; "www" зарезервирован.')]),
        ),
    ]
