# Generated by Django 5.2.7 on 2026-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kind',
            field=models.CharField(choices=[('holding', 'Холдинг'), ('construction', 'Строительная'), ('it', 'IT-компания'), ('service', 'Сервисная'), ('regional', 'Региональная (устар.)')], max_length=16),
        ),
    ]
