# Generated by Django 5.2.7 on 2026-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_external_holders',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
