# Generated by Django 5.2.7 on 2026-09-22 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_show_external_holders'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subdomain',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(?!www$)[a-z]([a-z0-9-]{0,30}[a-z0-9])?$', 'Только строчные латинские буквы, цифры и дефис; первый символ — буква; не заканчивается дефисом; до 32 символов; "www" зарезервирован.')]),
        ),
    ]
