# Generated by Django 5.2.7 on 2026-09-23 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_seed_company_subdomains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subdomain',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(?!www$)[a-z]([a-z0-9-]{0,30}[a-z0-9])?$', 'Только строчные латинские буквы, цифры и дефис; первый символ — буква; не заканчивается дефисом; до 32 символов; "www" зарезервирован.')], verbose_name='короткий адрес'),
        ),
    ]
