# Generated by Django 5.2.7 on 2026-07-19 18:52

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('original_filename', models.CharField(blank=True, db_default='', default='', max_length=512)),
                ('owner_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('size', models.BigIntegerField(db_default=0, default=0)),
                ('mime', models.CharField(blank=True, db_default='application/octet-stream', default='application/octet-stream', max_length=255)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], db_default='local', default='local', max_length=16)),
                ('is_public', models.BooleanField(db_default=False, default=False)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], db_default='other', db_index=True, default='other', max_length=16)),
                ('scope', models.CharField(choices=[('avatar', 'Avatar'), ('news', 'News'), ('chat', 'Chat'), ('hr_doc', 'Hr Doc'), ('hr_department', 'Hr Department'), ('task_attachment', 'Task Attachment'), ('generic', 'Generic')], db_default='generic', db_index=True, default='generic', max_length=32)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='FileVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('size', models.BigIntegerField(db_default=0, default=0)),
                ('mime', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media_files.filemetadata')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('file', 'variant'), name='unique_file_variant')],
            },
        ),
    ]
