"""Ядро модуля БЗО: счётчики номеров и журнал изменений.

Триггер создаётся в той схеме, где идёт миграция (``migrate_companies``
ставит ``search_path`` на ``co_<slug>``), поэтому у каждой компании свой.
``TRUNCATE`` (фикстуры тестов) строковые триггеры не вызывает.
"""

# Generated by Django 5.2.7 on 2026-09-26 18:54

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['object_type', 'object_id', 'created_at'], name='ix_bpp_audit_object')],
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('year', models.PositiveSmallIntegerField()),
                ('last', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счётчик номеров',
                'verbose_name_plural': 'Счётчики номеров',
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='uq_bpp_number_prefix_year')],
            },
        ),
        migrations.RunSQL(
            sql=[
                """
                CREATE OR REPLACE FUNCTION bpp_auditlog_immutable() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'bpp_auditlog: журнал изменений только для записи';
                END;
                $$ LANGUAGE plpgsql;
                """,
                """
                CREATE TRIGGER bpp_auditlog_no_change
                BEFORE UPDATE OR DELETE ON bpp_auditlog
                FOR EACH ROW EXECUTE FUNCTION bpp_auditlog_immutable();
                """,
            ],
            reverse_sql=[
                "DROP TRIGGER IF EXISTS bpp_auditlog_no_change ON bpp_auditlog;",
                "DROP FUNCTION IF EXISTS bpp_auditlog_immutable();",
            ],
        ),
    ]
