# Generated by Django 5.2.7 on 2026-09-26 19:16

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0001_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('owner_type', models.CharField(max_length=64)),
                ('owner_id', models.CharField(max_length=64)),
                ('file_type', models.CharField(max_length=32)),
                ('media_file_id', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=128)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('replaced', models.BooleanField(db_default=False, default=False)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='bpp.documentfile')),
            ],
            options={
                'verbose_name': 'Файл документа',
                'verbose_name_plural': 'Файлы документов',
            },
        ),
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downloads', to='bpp.documentfile')),
            ],
            options={
                'verbose_name': 'Скачивание файла',
                'verbose_name_plural': 'Журнал скачиваний',
            },
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['owner_type', 'owner_id', 'file_type'], name='ix_bpp_file_owner'),
        ),
    ]
