# Generated by Django 5.2.7 on 2026-09-27 10:01

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0002_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('project_id', models.UUIDField()),
                ('number', models.CharField(max_length=48)),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('closed', 'Закрыт')], default='draft', max_length=16)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status_comment', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
            },
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действующая'), ('archived', 'Архивная')], default='draft', max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bpp.budget')),
            ],
            options={
                'verbose_name': 'Версия бюджета',
                'verbose_name_plural': 'Версии бюджета',
                'ordering': ('version_no',),
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('article_id', models.UUIDField()),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bpp.budgetversion')),
            ],
            options={
                'verbose_name': 'Строка бюджета',
                'verbose_name_plural': 'Строки бюджета',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bpp.budgetversion'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('number', models.CharField(max_length=32)),
                ('author_id', models.IntegerField()),
                ('initiator_role', models.CharField(choices=[('sn', 'Снабженец'), ('pm', 'Руководитель проекта')], max_length=8)),
                ('project_id', models.UUIDField()),
                ('article_id', models.UUIDField(blank=True, null=True)),
                ('purchase_type', models.CharField(blank=True, choices=[('goods', 'ТМЦ'), ('works', 'Работы и услуги')], default='', max_length=8)),
                ('need_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На согласовании'), ('approved', 'Утверждена'), ('rework', 'На доработке'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], default='draft', max_length=16)),
                ('status_comment', models.TextField(blank=True, default='')),
                ('is_migrated', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'indexes': [models.Index(fields=['project_id', 'article_id', 'status'], name='ix_bpp_request_line'), models.Index(fields=['author_id', 'status'], name='ix_bpp_request_author')],
                'constraints': [models.UniqueConstraint(fields=('number',), name='uq_bpp_request_number')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('sys_number', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=500)),
                ('specs', models.TextField(blank=True, default='')),
                ('uom_id', models.UUIDField()),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('need_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('partially_closed', 'Частично закрыта'), ('closed', 'Закрыта'), ('annulled', 'Аннулирована')], default='open', max_length=20)),
                ('executor_id', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bpp.purchaserequest')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявок',
                'ordering': ('line_no',),
            },
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.UniqueConstraint(fields=('budget', 'version_no'), name='uq_bpp_budget_version_no'),
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('budget',), name='uq_bpp_budget_one_draft'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('version', 'article_id'), name='uq_bpp_budget_line_article'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('limit_amount__gte', 0)), name='ck_bpp_budget_line_limit'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('project_id',), name='uq_bpp_budget_project'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('number',), name='uq_bpp_budget_number'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('date_from__isnull', True), ('date_to__isnull', True), ('date_to__gte', models.F('date_from')), _connector='OR'), name='ck_bpp_budget_period'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestitem',
            index=models.Index(fields=['executor_id', 'status'], name='ix_bpp_request_item_exec'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.UniqueConstraint(fields=('sys_number',), name='uq_bpp_request_item_sys'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'line_no'), name='uq_bpp_request_item_line'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_bpp_request_item_qty'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='ck_bpp_request_item_price'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_bpp_request_item_amount'),
        ),
    ]
