# Generated by Django 5.2.7 on 2026-09-27 10:52

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0004_committed_check_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountableFundsRequest',
            fields=[
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('number', models.CharField(max_length=32)),
                ('project_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='KZT', max_length=3)),
                ('goal', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На согласовании'), ('awaiting_accounting', 'Ожидает выдачи бухгалтерией'), ('awaiting_report', 'Ожидает авансовый отчёт'), ('closed', 'Закрыта')], default='draft', max_length=24)),
                ('accountable_user_id', models.IntegerField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_by', models.IntegerField(blank=True, null=True)),
                ('is_migrated', models.BooleanField(db_default=False, default=False)),
            ],
            options={
                'verbose_name': 'Заявка на подотчётные средства',
                'verbose_name_plural': 'Заявки на подотчётные средства',
                'indexes': [models.Index(fields=['project_id', 'article_id', 'status'], name='ix_bpp_accountable_line'), models.Index(fields=['accountable_user_id', 'status'], name='ix_bpp_accountable_user')],
                'constraints': [models.UniqueConstraint(fields=('number',), name='uq_bpp_accountable_number'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_bpp_accountable_amount')],
            },
        ),
        migrations.CreateModel(
            name='AdvanceReport',
            fields=[
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('expense_name', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='bpp.accountablefundsrequest')),
            ],
            options={
                'verbose_name': 'Авансовый отчёт',
                'verbose_name_plural': 'Авансовые отчёты',
                'ordering': ('created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_bpp_advance_amount')],
            },
        ),
    ]
