# Generated by Django 5.2.7 on 2026-09-27 16:34

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0007_drop_document_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Готовится'), ('done', 'Готов'), ('error', 'Не собран')], db_default='queued', default='queued', max_length=16)),
                ('media_file_id', models.UUIDField(blank=True, null=True)),
                ('error', models.TextField(blank=True, db_default='', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Фоновая выгрузка',
                'verbose_name_plural': 'Фоновые выгрузки',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='ix_bpp_export_requester')],
            },
        ),
    ]
