# Generated by Django 5.2.7 on 2026-09-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0006_align_stage2_plan'),
        ('bpp', '0008_export_jobs'),
    ]

    operations = [
    ]
