# Generated by Django 5.2.7 on 2026-09-28 12:18

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0009_merge_0006_align_stage2_plan_0008_export_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('onec', '1С (1CClientBankExchange, .txt)'), ('xlsx', 'Excel (.xlsx)'), ('csv', 'CSV')], max_length=8)),
                ('encoding', models.CharField(db_default='cp1251', default='cp1251', max_length=32)),
                ('delimiter', models.CharField(blank=True, db_default=';', default=';', max_length=4)),
                ('date_format', models.CharField(db_default='ДД.ММ.ГГГГ', default='ДД.ММ.ГГГГ', max_length=32)),
                ('columns', models.JSONField(blank=True, default=dict)),
                ('amount_mode', models.CharField(choices=[('signed', 'Одна колонка суммы со знаком'), ('split', 'Колонки «Дебет» и «Кредит»')], db_default='signed', default='signed', max_length=8)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'verbose_name': 'Шаблон выписки',
                'verbose_name_plural': 'Шаблоны выписок',
                'ordering': ('name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='OrgBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('iban', models.CharField(max_length=34)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('bic', models.CharField(max_length=11)),
                ('currency', models.CharField(db_default='KZT', default='KZT', max_length=3)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='bpp.statementtemplate')),
            ],
            options={
                'verbose_name': 'Банковский счёт организации',
                'verbose_name_plural': 'Банковские счета организации',
                'ordering': ('-is_active', 'bank_name', 'iban'),
                'constraints': [models.UniqueConstraint(fields=('iban',), name='uq_bpp_org_account_iban')],
            },
        ),
    ]
