# Generated by Django 5.2.7 on 2026-09-28 13:00

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0009_merge_0006_align_stage2_plan_0008_export_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('number', models.CharField(max_length=32)),
                ('ext_number', models.CharField(blank=True, default='', max_length=50)),
                ('ext_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('project_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('agreement_type', models.CharField(blank=True, choices=[('works', 'Работы и услуги'), ('goods', 'ТМЦ')], default='', max_length=8)),
                ('is_open', models.BooleanField(db_default=False, default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency_code', models.CharField(default='KZT', max_length=3)),
                ('with_vat', models.BooleanField(db_default=True, default=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vat_source', models.CharField(blank=True, choices=[('refdata', 'Справочник'), ('default', 'По умолчанию (16%)'), ('manual', 'Вручную')], default='', max_length=8)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На согласовании'), ('active', 'Действует'), ('rework', 'На доработке'), ('rejected', 'Отклонён'), ('fulfilled', 'Исполнен'), ('terminated', 'Расторгнут'), ('replaced', 'Заменён альтернативой')], default='draft', max_length=16)),
                ('status_comment', models.TextField(blank=True, default='')),
                ('rework_comment', models.TextField(blank=True, default='')),
                ('author_id', models.IntegerField()),
                ('initiator_role', models.CharField(blank=True, default='', max_length=8)),
                ('alt_limit', models.PositiveSmallIntegerField(db_default=3, default=3)),
                ('counterparty_confirmed', models.BooleanField(db_default=False, default=False)),
                ('is_migrated', models.BooleanField(db_default=False, default=False)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='bpp.counterparty')),
                ('parent_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplements', to='bpp.agreement')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='AgreementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bpp.agreement')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_items', to='bpp.purchaserequestitem')),
            ],
            options={
                'verbose_name': 'Позиция договора',
                'verbose_name_plural': 'Позиции договора',
            },
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['project_id', 'article_id', 'status'], name='ix_bpp_agreement_line'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['author_id', 'status'], name='ix_bpp_agreement_author'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.UniqueConstraint(fields=('number',), name='uq_bpp_agreement_number'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['rejected', 'replaced', 'draft', 'rework']), _negated=True), fields=('counterparty', 'ext_number', 'ext_date'), name='uq_bpp_agreement_ext'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(('is_open', True), ('amount__isnull', False), _connector='OR'), name='ck_bpp_agreement_amount'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='ck_bpp_agreement_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('ext_date__isnull', True), ('valid_to__gte', models.F('ext_date')), _connector='OR'), name='ck_bpp_agreement_valid_to'),
        ),
        migrations.AddConstraint(
            model_name='agreementitem',
            constraint=models.UniqueConstraint(fields=('agreement', 'request_item'), name='uq_bpp_agreement_item'),
        ),
        migrations.AddConstraint(
            model_name='agreementitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_bpp_agreement_item_qty'),
        ),
    ]
