# Generated by Django 5.2.7 on 2026-09-28 13:49

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0010_agreements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('number', models.CharField(max_length=32)),
                ('basis', models.CharField(choices=[('no_contract', 'Без договора'), ('contract', 'По договору')], default='no_contract', max_length=16)),
                ('project_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('ext_number', models.CharField(blank=True, default='', max_length=50)),
                ('ext_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency_code', models.CharField(default='KZT', max_length=3)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rate_source', models.CharField(blank=True, choices=[('kzt', 'Тенге'), ('nbrk', 'Курс НБРК'), ('manual', 'Фактический курс')], default='', max_length=8)),
                ('amount_kzt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('with_vat', models.BooleanField(db_default=True, default=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vat_source', models.CharField(blank=True, default='', max_length=8)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('purchase_type', models.CharField(blank=True, default='', max_length=8)),
                ('is_advance', models.BooleanField(db_default=False, default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('under_review', 'На рассмотрении ФД'), ('returned', 'Возвращён на доработку'), ('not_payable', 'Не к оплате'), ('to_pay', 'К оплате'), ('partially_paid', 'Оплачено частично'), ('paid', 'Оплачено'), ('awaiting_docs', 'Ждёт закрывающих документов'), ('docs_provided', 'Документы предоставлены'), ('closed', 'Закрыт'), ('cancelled', 'Отменён'), ('replaced', 'Заменён альтернативой')], default='draft', max_length=16)),
                ('status_comment', models.TextField(blank=True, default='')),
                ('rework_comment', models.TextField(blank=True, default='')),
                ('fd_decided_at', models.DateTimeField(blank=True, null=True)),
                ('planned_pay_date', models.DateField(blank=True, null=True)),
                ('docs_required', models.JSONField(blank=True, default=dict)),
                ('docs_requested_at', models.DateTimeField(blank=True, null=True)),
                ('docs_comment', models.TextField(blank=True, default='')),
                ('recon_status', models.CharField(choices=[('no_data', 'Нет данных банка'), ('partial', 'Оплачен частично'), ('full', 'Оплачен полностью'), ('overpaid', 'Переплата')], db_default='no_data', default='no_data', max_length=10)),
                ('paid_bank_amount', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=18)),
                ('author_comment', models.TextField(blank=True, default='')),
                ('author_id', models.IntegerField()),
                ('initiator_role', models.CharField(blank=True, default='', max_length=8)),
                ('counterparty_confirmed', models.BooleanField(db_default=False, default=False)),
                ('is_migrated', models.BooleanField(db_default=False, default=False)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bpp.agreement')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bpp.counterparty')),
            ],
            options={
                'verbose_name': 'Счёт на оплату',
                'verbose_name_plural': 'Счета на оплату',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bpp.invoice')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='bpp.purchaserequestitem')),
            ],
            options={
                'verbose_name': 'Строка счёта',
                'verbose_name_plural': 'Строки счёта',
            },
        ),
        migrations.CreateModel(
            name='PaymentMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('pay_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('pp_number', models.CharField(blank=True, default='', max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('marked_by_id', models.IntegerField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_id', models.IntegerField(blank=True, null=True)),
                ('cancel_comment', models.TextField(blank=True, default='')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bpp.invoice')),
            ],
            options={
                'verbose_name': 'Отметка оплаты',
                'verbose_name_plural': 'Отметки оплаты',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['project_id', 'article_id', 'status'], name='ix_bpp_invoice_line'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['author_id', 'status'], name='ix_bpp_invoice_author'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='ix_bpp_invoice_queue'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('number',), name='uq_bpp_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'returned', 'cancelled', 'replaced', 'not_payable']), _negated=True), fields=('counterparty', 'ext_number', 'ext_date'), name='uq_bpp_invoice_ext'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_bpp_invoice_amount'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agreement__isnull', False), ('basis', 'contract')), models.Q(('agreement__isnull', True), ('basis', 'no_contract')), _connector='OR'), name='ck_bpp_invoice_basis'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'request_item'), name='uq_bpp_invoice_line'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_bpp_invoice_line_qty'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_bpp_invoice_line_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentmark',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_bpp_payment_amount'),
        ),
    ]
