# Generated by Django 5.2.7 on 2026-09-28 16:07

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0010_bank_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('format', models.CharField(choices=[('onec', '1С (1CClientBankExchange, .txt)'), ('xlsx', 'Excel (.xlsx)'), ('csv', 'CSV')], max_length=8)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('loaded', 'Загружена'), ('failed', 'Ошибка загрузки'), ('cancelled', 'Отменена')], db_default='processing', default='processing', max_length=16)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('rows_total', models.PositiveIntegerField(db_default=0, default=0)),
                ('rows_done', models.PositiveIntegerField(db_default=0, default=0)),
                ('debits', models.PositiveIntegerField(db_default=0, default=0)),
                ('duplicates', models.PositiveIntegerField(db_default=0, default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('failure', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.BinaryField(blank=True, default=b'')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='bpp.orgbankaccount')),
            ],
            options={
                'verbose_name': 'Загрузка выписки',
                'verbose_name_plural': 'Загрузки выписок',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('row_no', models.PositiveIntegerField()),
                ('doc_date', models.DateField()),
                ('doc_number', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(db_default='KZT', default='KZT', max_length=3)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=500)),
                ('recipient_bin', models.CharField(blank=True, default='', max_length=32)),
                ('recipient_iban', models.CharField(blank=True, default='', max_length=34)),
                ('purpose', models.TextField(blank=True, default='')),
                ('dedup_hash', models.CharField(max_length=64)),
                ('match_status', models.CharField(choices=[('unmatched', 'Не сопоставлена')], db_default='unmatched', default='unmatched', max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_lines', to='bpp.orgbankaccount')),
                ('bank_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='bpp.bankimport')),
            ],
            options={
                'verbose_name': 'Строка выписки',
                'verbose_name_plural': 'Строки выписок',
                'ordering': ('bank_import', 'row_no'),
            },
        ),
        migrations.AddIndex(
            model_name='bankimport',
            index=models.Index(fields=['account', 'period_from', 'period_to'], name='ix_bpp_bankimport_account'),
        ),
        migrations.AddIndex(
            model_name='bankimport',
            index=models.Index(fields=['status', 'created_at'], name='ix_bpp_bankimport_status'),
        ),
        migrations.AddConstraint(
            model_name='bankimport',
            constraint=models.CheckConstraint(condition=models.Q(('period_to__gte', models.F('period_from'))), name='ck_bpp_bankimport_period'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['bank_import', 'row_no'], name='ix_bpp_stmtline_import'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['account', 'doc_date'], name='ix_bpp_stmtline_account'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['match_status'], name='ix_bpp_stmtline_match'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('dedup_hash',), name='uq_bpp_statement_line_dedup'),
        ),
    ]
