# Generated by Django 5.2.7 on 2026-09-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0011_invoices'),
        ('bpp', '0012_bank_import_reaper_periodic_task'),
    ]

    operations = [
    ]
