# Generated by Django 5.2.7 on 2026-09-30 08:08

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0013_merge_stage3_a_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('source_type', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Связь переноса из «Договоров»',
                'verbose_name_plural': 'Связи переноса из «Договоров»',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='ix_bpp_migration_target')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'target_type'), name='uq_bpp_migration_source_target')],
            },
        ),
    ]
