# Generated by Django 5.2.7 on 2026-09-29 21:22

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0013_merge_stage3_a_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='excluded_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='excluded_comment',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='found_numbers',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='review_reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='bankimport',
            name='status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('loaded', 'Загружена'), ('reconciled', 'Сверена'), ('failed', 'Ошибка загрузки'), ('cancelled', 'Отменена')], db_default='processing', default='processing', max_length=16),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='match_status',
            field=models.CharField(choices=[('unmatched', 'Не сопоставлена'), ('matched', 'Сопоставлена'), ('needs_review', 'Требует проверки'), ('excluded', 'Исключена')], db_default='unmatched', default='unmatched', max_length=16),
        ),
        migrations.CreateModel(
            name='PaymentMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('manual', models.BooleanField(db_default=False, default=False)),
                ('state', models.CharField(choices=[('active', 'Действует'), ('review', 'На проверке'), ('cancelled', 'Отменено')], db_default='active', default='active', max_length=16)),
                ('review_reason', models.CharField(blank=True, db_default='', default='', max_length=32)),
                ('comment', models.TextField(blank=True, db_default='', default='')),
                ('confirmed_by_id', models.IntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by_id', models.IntegerField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='payment_matches', to='bpp.invoice')),
                ('line', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='bpp.bankstatementline')),
            ],
            options={
                'verbose_name': 'Сопоставление платежа',
                'verbose_name_plural': 'Сопоставления платежей',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['invoice', 'state'], name='ix_bpp_paymatch_invoice'), models.Index(fields=['line', 'state'], name='ix_bpp_paymatch_line')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'cancelled'), _negated=True), fields=('line', 'invoice'), name='uq_bpp_paymatch_line_invoice'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_bpp_paymatch_amount')],
            },
        ),
    ]
