# Generated by Django 5.2.7 on 2026-09-30 12:50

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0014_recon'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='alt_limit',
            field=models.PositiveSmallIntegerField(db_default=3, default=3),
        ),
        migrations.CreateModel(
            name='AlternativeOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('number', models.CharField(max_length=32)),
                ('source_type', models.CharField(choices=[('invoice', 'Счёт на оплату'), ('agreement', 'Договор')], max_length=16)),
                ('source_id', models.UUIDField()),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('article_id', models.UUIDField(blank=True, null=True)),
                ('author_id', models.IntegerField()),
                ('author_role', models.CharField(choices=[('sn', 'Снабженец'), ('pm', 'Руководитель проекта')], max_length=8)),
                ('own_document', models.BooleanField(db_default=False, default=False)),
                ('currency_code', models.CharField(db_default='KZT', default='KZT', max_length=3)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('amount', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=18)),
                ('amount_kzt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('with_vat', models.BooleanField(db_default=True, default=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vat_source', models.CharField(blank=True, choices=[('refdata', 'Справочник'), ('default', 'По умолчанию (16%)'), ('manual', 'Вручную')], db_default='', default='', max_length=8)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('source_amount_kzt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saving_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saving_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, choices=[('full_prepay', 'Полная предоплата'), ('partial_prepay', 'Частичная предоплата'), ('postpay', 'Постоплата')], db_default='', default='', max_length=16)),
                ('payment_terms_note', models.TextField(blank=True, db_default='', default='')),
                ('justification', models.TextField(blank=True, db_default='', default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('selected', 'Выбрано'), ('not_selected', 'Не выбрано'), ('withdrawn', 'Отозвано'), ('annulled', 'Аннулировано')], db_default='draft', default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by_id', models.IntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True, db_default='', default='')),
                ('result_type', models.CharField(blank=True, choices=[('invoice', 'Счёт на оплату'), ('agreement', 'Договор')], db_default='', default='', max_length=16)),
                ('result_id', models.UUIDField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True, db_default='', default='')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alternative_offers', to='bpp.counterparty')),
            ],
            options={
                'verbose_name': 'Альтернативное предложение',
                'verbose_name_plural': 'Альтернативные предложения',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlternativeOfferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('source_line_id', models.UUIDField()),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('source_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bpp.alternativeoffer')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternative_offer_lines', to='bpp.purchaserequestitem')),
            ],
            options={
                'verbose_name': 'Позиция альтернативного предложения',
                'verbose_name_plural': 'Позиции альтернативного предложения',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='KpiRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(db_default=1, default=1)),
                ('buyer_id', models.IntegerField()),
                ('buyer_role', models.CharField(choices=[('sn', 'Снабженец'), ('pm', 'Руководитель проекта')], max_length=8)),
                ('own_document', models.BooleanField(db_default=False, default=False)),
                ('project_id', models.UUIDField()),
                ('article_id', models.UUIDField()),
                ('source_type', models.CharField(choices=[('invoice', 'Счёт на оплату'), ('agreement', 'Договор')], max_length=16)),
                ('source_id', models.UUIDField()),
                ('source_number', models.CharField(max_length=32)),
                ('source_counterparty_id', models.UUIDField(blank=True, null=True)),
                ('source_amount_kzt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('result_type', models.CharField(choices=[('invoice', 'Счёт на оплату'), ('agreement', 'Договор')], max_length=16)),
                ('result_id', models.UUIDField()),
                ('result_number', models.CharField(blank=True, db_default='', default='', max_length=32)),
                ('result_amount_kzt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saving_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saving_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selected_at', models.DateTimeField()),
                ('selected_by_id', models.IntegerField()),
                ('status', models.CharField(choices=[('preliminary', 'Предварительный'), ('confirmed', 'Подтверждён'), ('annulled', 'Аннулирован')], db_default='preliminary', default='preliminary', max_length=16)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('annul_comment', models.TextField(blank=True, db_default='', default='')),
                ('annulled_by_id', models.IntegerField(blank=True, null=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kpi', to='bpp.alternativeoffer')),
            ],
            options={
                'verbose_name': 'Запись KPI снабжения',
                'verbose_name_plural': 'Записи KPI снабжения',
                'ordering': ('-selected_at',),
            },
        ),
        migrations.AddIndex(
            model_name='alternativeoffer',
            index=models.Index(fields=['source_type', 'source_id', 'status'], name='ix_bpp_altoffer_source'),
        ),
        migrations.AddIndex(
            model_name='alternativeoffer',
            index=models.Index(fields=['author_id', 'status'], name='ix_bpp_altoffer_author'),
        ),
        migrations.AddIndex(
            model_name='alternativeoffer',
            index=models.Index(fields=['project_id', 'article_id'], name='ix_bpp_altoffer_line'),
        ),
        migrations.AddConstraint(
            model_name='alternativeoffer',
            constraint=models.UniqueConstraint(fields=('number',), name='uq_bpp_altoffer_number'),
        ),
        migrations.AddConstraint(
            model_name='alternativeoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'selected'])), fields=('source_type', 'source_id', 'counterparty'), name='uq_bpp_altoffer_counterparty'),
        ),
        migrations.AddConstraint(
            model_name='alternativeofferline',
            constraint=models.UniqueConstraint(fields=('offer', 'source_line_id'), name='uq_bpp_altline_source'),
        ),
        migrations.AddConstraint(
            model_name='alternativeofferline',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gt', 0), _connector='OR'), name='ck_bpp_altline_price'),
        ),
        migrations.AddConstraint(
            model_name='alternativeofferline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_bpp_altline_qty'),
        ),
        migrations.AddIndex(
            model_name='kpirecord',
            index=models.Index(fields=['buyer_id', 'status'], name='ix_bpp_kpi_buyer'),
        ),
        migrations.AddIndex(
            model_name='kpirecord',
            index=models.Index(fields=['selected_at'], name='ix_bpp_kpi_selected'),
        ),
        migrations.AddIndex(
            model_name='kpirecord',
            index=models.Index(fields=['result_type', 'result_id'], name='ix_bpp_kpi_result'),
        ),
    ]
