# Generated by Django 5.2.7 on 2026-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0014_migration_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='uq_bpp_invoice_ext',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status__in', ['draft', 'returned', 'cancelled', 'replaced', 'not_payable']), _negated=True), models.Q(('ext_number', ''), _negated=True)), fields=('counterparty', 'ext_number', 'ext_date'), name='uq_bpp_invoice_ext'),
        ),
    ]
