# Generated by Django 5.2.7 on 2026-09-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0014_recon'),
        ('bpp', '0015_invoice_ext_unique_skip_blank'),
    ]

    operations = [
    ]
