# Generated by Django 5.2.7 on 2026-10-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0015_alternatives'),
        ('bpp', '0016_merge_stage4_a_b'),
    ]

    operations = [
    ]
