# Generated by Django 5.2.7 on 2026-10-02 20:06

"""Читатели сводных представлений холдинга для БЗО (A8.1, D-S7-8).

Пять ``CreateModel`` с ``managed=False`` DDL не выполняют: записывают состояние
для ``apps/bpp/holding_models.py``, чтобы ``makemigrations --check`` остался
чист. Представления ``holding.bpp_*`` собирает ``holding_views`` (после
``migrate_companies``). Expand-only: в схемах компаний ничего не меняется.
"""

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0018_ext_1c_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_slug', models.CharField(max_length=63)),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'bpp_agreement',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HoldingBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_slug', models.CharField(max_length=63)),
                ('status', models.CharField(max_length=16)),
                ('currency_code', models.CharField(max_length=3)),
                ('active_version_id', models.UUIDField(null=True)),
            ],
            options={
                'db_table': 'bpp_budget',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HoldingBudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_slug', models.CharField(max_length=63)),
                ('version_id', models.UUIDField()),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'bpp_budgetline',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HoldingBudgetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_slug', models.CharField(max_length=63)),
                ('budget_id', models.UUIDField()),
                ('state', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'bpp_budgetversion',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='HoldingInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_slug', models.CharField(max_length=63)),
                ('status', models.CharField(max_length=16)),
                ('amount_kzt', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'bpp_invoice',
                'abstract': False,
                'managed': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
