# Generated by Django 5.2.7 on 2026-07-28 06:14

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(blank=True, db_default='', default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_iin', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('vat', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('contacts', models.TextField(blank=True, db_default='', default='')),
                ('address', models.TextField(blank=True, db_default='', default='')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('blocked', 'Заблокирован')], db_default='active', default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparties', to='contracts.country')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Реестр контрактов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrators', to='contracts.country')),
            ],
            options={
                'verbose_name': 'Администратор бюджета',
                'verbose_name_plural': 'Администраторы бюджета',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expense_item', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, db_default='', default='', max_length=50)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'ordering': ('name', 'expense_item'),
                'constraints': [models.UniqueConstraint(fields=('name', 'expense_item'), name='uq_contracts_program_name_item')],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(db_default='KZT', default='KZT', max_length=3)),
                ('period_year', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], db_default='active', default='active', max_length=16)),
                ('note', models.TextField(blank=True, db_default='', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='contracts.administrator')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='contracts.program')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
                'ordering': ('-period_year', 'administrator_id', 'program_id'),
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('payment_type', models.CharField(choices=[('prepayment', 'Предоплата'), ('postpayment', 'Постоплата'), ('staged', 'Поэтапно')], db_default='postpayment', default='postpayment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(db_default='KZT', default='KZT', max_length=3)),
                ('file_id', models.CharField(blank=True, max_length=64, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На согласовании'), ('approved', 'Согласован'), ('signed', 'Подписан'), ('executed', 'Исполнен'), ('terminated', 'Расторгнут')], db_default='draft', default='draft', max_length=20)),
                ('created_by', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='contracts.budget')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='contracts.counterparty')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['budget', 'status'], name='ix_contracts_agr_budget_st')],
            },
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['name'], name='ix_contracts_cp_name'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('administrator', 'program', 'period_year'), name='uq_contracts_budget_admin_program_year'),
        ),
    ]
