# Generated by Django 5.2.7 on 2026-07-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_budget_container_budgetline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparty',
            options={'ordering': ('name',), 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Реестр контрагентов'},
        ),
    ]
