# Generated by Django 5.2.7 on 2026-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_counterparty_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='contact_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=200, verbose_name='Генеральный директор'),
        ),
    ]
