# Generated by Django 5.2.7 on 2026-07-31 09:23

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_approval_state_rework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('note', models.TextField(blank=True, db_default='', default='', verbose_name='Пояснение')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма счёта')),
                ('currency', models.CharField(db_default='KZT', default='KZT', max_length=3)),
                ('file_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Скан счёта на оплату')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На согласовании'), ('approved', 'Согласован'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], db_default='draft', default='draft', max_length=20)),
                ('created_by', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contracts.budgetline')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contracts.counterparty')),
            ],
            options={
                'verbose_name': 'Счёт на оплату',
                'verbose_name_plural': 'Счета на оплату',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['budget_line', 'status'], name='ix_contracts_inv_line_st')],
            },
        ),
    ]
