# Generated by Codex on 2026-08-07

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancePayment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True,
                                          serialize=False, verbose_name="ID")),
                ("approval_state", models.CharField(
                    choices=[("draft", "Черновик"), ("pending", "На согласовании"),
                             ("approved", "Согласовано"), ("rejected", "Отклонено"),
                             ("rework", "На доработке")],
                    db_default="draft", db_index=True, default="draft", max_length=16,
                    verbose_name="Состояние согласования")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18,
                                                verbose_name="Сумма предоплаты")),
                ("payment_order_file_id", models.CharField(blank=True, max_length=64,
                                                            null=True,
                                                            verbose_name="Файл платёжного поручения")),
                ("posting_number", models.CharField(blank=True, db_default="", default="",
                                                      max_length=100,
                                                      verbose_name="Номер проводки")),
                ("paid_by", models.IntegerField(blank=True, db_index=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True,
                                                     db_default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(auto_now=True,
                                                     db_default=django.db.models.functions.datetime.Now())),
                ("agreement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                 related_name="advance_payments",
                                                 to="contracts.agreement")),
            ],
            options={
                "verbose_name": "Предоплата на основании договора",
                "verbose_name_plural": "Предоплаты на основании договоров",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["agreement", "approval_state"],
                                           name="ix_ctr_adv_agr_state")],
            },
        ),
    ]
