# Generated by Codex on 2026-08-07

from django.db import migrations, models


def set_existing_statuses(apps, schema_editor):
    AdvancePayment = apps.get_model("contracts", "AdvancePayment")

    # Исторические записи могли уже иметь платёжное поручение: они завершены.
    AdvancePayment.objects.filter(payment_order_file_id__isnull=False).update(status="closed")
    AdvancePayment.objects.exclude(posting_number="").update(status="closed")
    # Из остальных только одобренные ждут оформления бухгалтерией.
    AdvancePayment.objects.filter(
        approval_state="approved", payment_order_file_id__isnull=True,
        posting_number="",
    ).update(status="awaiting_accounting")
    AdvancePayment.objects.filter(approval_state="pending").update(status="on_review")


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_advancepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancepayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("on_review", "На согласовании"),
                    ("awaiting_accounting", "Ожидает оформления бухгалтерией"),
                    ("closed", "Закрыт"),
                ],
                db_default="draft",
                default="draft",
                max_length=24,
            ),
        ),
        migrations.RunPython(set_existing_statuses, migrations.RunPython.noop),
    ]
