# Generated by Codex on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_advancepayment_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="advancepayment",
            constraint=models.UniqueConstraint(
                fields=("agreement",), name="uq_ctr_adv_payment_agreement",
            ),
        ),
    ]
