# Generated by Codex on 2026-08-07

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contracts", "0013_advancepayment_one_per_agreement")]

    operations = [
        migrations.CreateModel(
            name="ContractPayment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approval_state", models.CharField(choices=[("draft", "Черновик"), ("pending", "На согласовании"), ("approved", "Согласовано"), ("rejected", "Отклонено"), ("rework", "На доработке")], db_default="draft", db_index=True, default="draft", max_length=16, verbose_name="Состояние согласования")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Сумма оплаты")),
                ("invoice_file_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="Счёт")),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("on_review", "На согласовании"), ("awaiting_accounting", "Ожидает оформления бухгалтерией"), ("closed", "Закрыт")], db_default="draft", default="draft", max_length=24)),
                ("payment_order_file_id", models.CharField(blank=True, max_length=64, null=True, verbose_name="Файл платёжного поручения")),
                ("posting_number", models.CharField(blank=True, db_default="", default="", max_length=100, verbose_name="Номер проводки")),
                ("paid_by", models.IntegerField(blank=True, db_index=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.IntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ("administrator", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_payments", to="contracts.administrator")),
                ("agreement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contract_payments", to="contracts.agreement")),
            ],
            options={"ordering": ("-created_at",), "verbose_name": "Оплата по договору", "verbose_name_plural": "Оплаты по договорам", "indexes": [models.Index(fields=["agreement", "status"], name="ix_ctr_pay_agr_status"), models.Index(fields=["administrator", "approval_state"], name="ix_ctr_pay_adm_state")]},
        ),
    ]
