# Generated by Codex on 2026-08-10

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contracts", "0015_completionact")]

    operations = [
        migrations.CreateModel(
            name="AccountableFundsRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approval_state", models.CharField(choices=[("draft", "Черновик"), ("pending", "На согласовании"), ("approved", "Согласовано"), ("rejected", "Отклонено"), ("rework", "На доработке")], db_default="draft", db_index=True, default="draft", max_length=16, verbose_name="Состояние согласования")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Сумма")),
                ("goal", models.TextField(verbose_name="Цель")),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("on_review", "На согласовании"), ("awaiting_accounting", "Ожидает оплаты бухгалтерией"), ("awaiting_advance_report", "Ожидает авансовый отчёт")], db_default="draft", default="draft", max_length=32)),
                ("accounting_paid", models.BooleanField(db_default=False, default=False, verbose_name="Бухгалтер оплатил")),
                ("accounting_paid_by", models.IntegerField(blank=True, db_index=True, null=True)),
                ("accounting_paid_at", models.DateTimeField(blank=True, null=True)),
                ("accountable_user_id", models.IntegerField(db_index=True)),
                ("created_by", models.IntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ("administrator", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="accountable_funds_requests", to="contracts.administrator")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="accountable_funds_requests", to="contracts.program")),
            ],
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Заявка на подотчётные средства",
                "verbose_name_plural": "Заявки на подотчётные средства",
                "indexes": [models.Index(fields=["administrator", "approval_state"], name="ix_af_req_adm_state"), models.Index(fields=["accountable_user_id", "status"], name="ix_af_req_user_status")],
            },
        ),
    ]
