# Generated by Codex on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contracts", "0016_accountablefundsrequest")]

    operations = [
        migrations.AddField(
            model_name="accountablefundsrequest",
            name="budget_line",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name="accountable_funds_requests", to="contracts.budgetline"),
        ),
        migrations.AddIndex(
            model_name="accountablefundsrequest",
            index=models.Index(fields=["budget_line", "approval_state"], name="ix_af_req_line_state"),
        ),
    ]
