# Generated by Codex on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contracts", "0017_accountablefundsrequest_budget_line")]

    operations = [
        migrations.RemoveIndex(
            model_name="accountablefundsrequest",
            name="ix_af_req_adm_state",
        ),
        migrations.AlterField(
            model_name="accountablefundsrequest",
            name="administrator",
            field=models.ForeignKey(blank=True, editable=False, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name="+", to="contracts.administrator"),
        ),
        migrations.AlterField(
            model_name="accountablefundsrequest",
            name="program",
            field=models.ForeignKey(blank=True, editable=False, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name="+", to="contracts.program"),
        ),
    ]
