# Generated by Codex on 2026-08-11

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contracts", "0018_accountablefundsrequest_legacy_links")]

    operations = [
        migrations.AlterField(
            model_name="accountablefundsrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("on_review", "На согласовании"),
                    ("awaiting_accounting", "Ожидает оплаты бухгалтерией"),
                    ("awaiting_advance_report", "Ожидает авансовый отчёт"),
                    ("closed", "Закрыта"),
                ],
                db_default="draft", default="draft", max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AdvanceReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approval_state", models.CharField(
                    choices=[
                        ("draft", "Черновик"), ("pending", "На согласовании"),
                        ("approved", "Согласовано"), ("rejected", "Отклонено"),
                        ("rework", "На доработке"),
                    ],
                    db_default="draft", db_index=True, default="draft", max_length=16,
                    verbose_name="Состояние согласования",
                )),
                ("expense_name", models.CharField(max_length=500, verbose_name="Наименование затрат")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Сумма")),
                ("file_id", models.CharField(max_length=64, verbose_name="Файл авансового отчёта")),
                ("created_by", models.IntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ("accountable_funds_request", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="advance_reports", to="contracts.accountablefundsrequest",
                )),
            ],
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Авансовый отчёт",
                "verbose_name_plural": "Авансовые отчёты",
                "indexes": [models.Index(
                    fields=["accountable_funds_request", "approval_state"],
                    name="ix_adv_report_req_state",
                )],
            },
        ),
    ]
