# Generated by Django 5.2.7 on 2026-09-07 06:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_advance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='advance_amount_planned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Плановый аванс, сумма'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='advance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аванс, %'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='amount_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сумма без НДС'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='contract_type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('non_standard', 'Нетиповой'), ('framework', 'Рамочный')], db_default='standard', default='standard', max_length=30, verbose_name='Тип договора'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='direction',
            field=models.CharField(choices=[('expense', 'Расход'), ('income', 'Поступление')], db_default='expense', default='expense', max_length=20, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='has_advance',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Аванс предусмотрен'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='has_vat',
            field=models.BooleanField(db_default=True, default=True, verbose_name='Флаг НДС'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='kind',
            field=models.CharField(choices=[('works_services', 'РиУ (Работы и услуги)'), ('goods', 'Товары'), ('services', 'Услуги'), ('lease', 'Аренда'), ('other', 'Прочее')], db_default='works_services', default='works_services', max_length=30, verbose_name='Вид договора'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='manager_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=200, verbose_name='Менеджер / Куратор'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='manager_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID менеджера/куратора'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='retention_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сумма гарантийного удержания'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='retention_rate',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Гарантийное удержание, %'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='sed_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=100, verbose_name='№ СЭД / Регистрационный номер'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='subject',
            field=models.TextField(blank=True, db_default='', default='', verbose_name='Предмет договора'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='term_comment',
            field=models.CharField(blank=True, db_default='', default='', max_length=255, verbose_name='Комментарий к сроку исполнения'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сумма НДС'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='vat_rate',
            field=models.DecimalField(db_default=Decimal('12.00'), decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='Ставка НДС, %'),
        ),
    ]
