# Generated by Django 5.2.7 on 2026-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_agreement_advance_amount_planned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='project_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Проект в модуле задач'),
        ),
    ]
