# Generated by Django 5.2.7 on 2026-09-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_administrator_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='request_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Заявка на закуп'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='request_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Заявка на закуп'),
        ),
    ]
