# Generated by Django 5.2.7 on 2026-09-17 09:57

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_operations_import_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_state', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], db_default='draft', db_index=True, default='draft', max_length=16, verbose_name='Состояние согласования')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма по накладной')),
                ('waybill_file_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Накладная')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_review', 'На согласовании'), ('awaiting_accounting', 'Ожидает оформления бухгалтерией'), ('closed', 'Закрыт')], db_default='draft', default='draft', max_length=24)),
                ('payment_order_file_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Файл платёжного поручения')),
                ('posting_number', models.CharField(blank=True, db_default='', default='', max_length=100, verbose_name='Номер проводки')),
                ('paid_by', models.IntegerField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_invoices', to='contracts.administrator')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_invoices', to='contracts.agreement')),
            ],
            options={
                'verbose_name': 'Товарная накладная',
                'verbose_name_plural': 'Товарные накладные',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['agreement', 'status'], name='ix_gi_agr_status'), models.Index(fields=['administrator', 'approval_state'], name='ix_gi_adm_state')],
            },
        ),
    ]
