# Generated by Django 5.2.7 on 2026-09-23 07:56
"""«Рамочный» → «Открытый»: только подпись значения ``framework``.

SQL не порождает (choices в БД не живут), значение ``framework`` в данных
прежнее — поэтому безопасно для компаний по обе стороны миграции.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_merge_goods_invoice_and_request_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='contract_type',
            field=models.CharField(choices=[('standard', 'Стандартный'), ('non_standard', 'Нетиповой'), ('framework', 'Открытый')], db_default='standard', default='standard', max_length=30, verbose_name='Тип договора'),
        ),
    ]
