# Generated by Django 5.2.7 on 2026-09-23 08:34
"""Позиции договора и уникальность «контрагент + номер + дата» (ТЗ 9.2).

Только расширение (expand), компании могут стоять по обе стороны:

* ``contracts_agreementitem`` — новая таблица, прежний код её не знает;
* с ``number`` снимается глобальная уникальность, взамен — тройка
  ``uq_contracts_agr_cp_number_date``. Ограничение стало МЯГЧЕ (разные
  контрагенты могут иметь договор с одним номером), а на существующих данных
  тройка заведомо уникальна — номер был уникален сам по себе;
* ``signed_date``/``end_date`` — только подписи («Дата договора», «Срок
  действия по»), SQL нет.

Тип колонок не меняется, поэтому представления холдинга (там есть
``Agreement``) эту миграцию не блокируют.
"""

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_agreement_type_open_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('request_item_key', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, db_default='', default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Позиция договора',
                'verbose_name_plural': 'Позиции договора',
                'ordering': ('agreement', 'line_no'),
            },
        ),
        migrations.AlterField(
            model_name='agreement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия по'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.UniqueConstraint(fields=('counterparty', 'number', 'signed_date'), name='uq_contracts_agr_cp_number_date', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='agreementitem',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.agreement'),
        ),
        migrations.AddConstraint(
            model_name='agreementitem',
            constraint=models.UniqueConstraint(fields=('agreement', 'line_no'), name='uq_contracts_agr_item_line'),
        ),
        migrations.AddConstraint(
            model_name='agreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('request_item_key', ''), _negated=True), fields=('agreement', 'request_item_key'), name='uq_contracts_agr_item_request'),
        ),
        migrations.AddConstraint(
            model_name='agreementitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_contracts_agr_item_qty'),
        ),
        migrations.AddConstraint(
            model_name='agreementitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='ck_contracts_agr_item_amount'),
        ),
    ]
