# Generated by Django 5.2.7 on 2026-10-01 08:50

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_agreement_items_and_contract_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_by_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, db_default='', default='')),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Заморозка раздела «Договоры»',
                'verbose_name_plural': 'Заморозка раздела «Договоры»',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ck_ctr_freeze_singleton')],
            },
        ),
    ]
