# Generated by Django 5.2.7 on 2026-07-28 11:06

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=64, verbose_name='Тип объекта')),
                ('subject_id', models.IntegerField(verbose_name='Объект')),
                ('route_id', models.IntegerField(blank=True, null=True, verbose_name='Маршрут (справочно)')),
                ('state', models.CharField(choices=[('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('cancelled', 'Отозвано')], db_default='pending', db_index=True, default='pending', max_length=16)),
                ('initiator_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Инициатор')),
                ('current_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Процесс согласования',
                'verbose_name_plural': 'Процессы согласования',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='ix_signoff_proc_subject')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('subject_type', 'subject_id'), name='uq_signoff_one_pending_process_per_subject')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='signoff.approvalprocess')),
            ],
            options={
                'verbose_name': 'Событие согласования',
                'verbose_name_plural': 'Журнал согласования',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcessStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('quorum', models.CharField(choices=[('any', 'Достаточно одного'), ('all', 'Нужны все')], db_default='all', default='all', max_length=8)),
                ('state', models.CharField(choices=[('waiting', 'Ожидает очереди'), ('active', 'На рассмотрении'), ('approved', 'Согласован'), ('rejected', 'Отклонён'), ('skipped', 'Не потребовался')], db_default='waiting', default='waiting', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='signoff.approvalprocess')),
            ],
            options={
                'verbose_name': 'Этап процесса',
                'verbose_name_plural': 'Этапы процесса',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(db_index=True, max_length=64, verbose_name='Тип объекта')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Маршрут согласования',
                'verbose_name_plural': 'Маршруты согласования',
                'ordering': ('subject_type', '-is_active', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subject_type',), name='uq_signoff_active_route_per_subject')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRouteStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_default=1, default=1, help_text='Одинаковая очередь = этапы идут параллельно', verbose_name='Очередь')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('quorum', models.CharField(choices=[('any', 'Достаточно одного'), ('all', 'Нужны все')], db_default='all', default='all', max_length=8, verbose_name='Кворум')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='signoff.approvalroute')),
            ],
            options={
                'verbose_name': 'Этап маршрута',
                'verbose_name_plural': 'Этапы маршрута',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApprovalRouteStageApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='Пользователь')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='signoff.approvalroutestage')),
            ],
            options={
                'verbose_name': 'Согласующий',
                'verbose_name_plural': 'Согласующие',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Согласующий')),
                ('state', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('skipped', 'Не потребовалось')], db_default='pending', default='pending', max_length=16)),
                ('comment', models.TextField(blank=True, db_default='', default='')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='signoff.approvalprocessstage')),
            ],
            options={
                'verbose_name': 'Запрос на согласование',
                'verbose_name_plural': 'Запросы на согласование',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='approvalprocessstage',
            index=models.Index(fields=['process', 'order'], name='ix_signoff_stage_proc_order'),
        ),
        migrations.AddConstraint(
            model_name='approvalroutestageapprover',
            constraint=models.UniqueConstraint(fields=('stage', 'user_id'), name='uq_signoff_stage_approver'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['user_id', 'state'], name='ix_signoff_task_user_state'),
        ),
        migrations.AddConstraint(
            model_name='approvaltask',
            constraint=models.UniqueConstraint(fields=('stage', 'user_id'), name='uq_signoff_task_stage_user'),
        ),
    ]
