# Generated by Django 5.2.7 on 2026-09-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0008_alter_approvalroutestage_approver_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalroute',
            name='uq_signoff_active_route_per_subject',
        ),
        migrations.AddField(
            model_name='approvalprocess',
            name='scope',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=64, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='approvalprocessstage',
            name='approver_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='approvalprocessstage',
            name='user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='scope',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=64, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='approvalroutestage',
            name='approver_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=64, verbose_name='Ключ согласующих объекта'),
        ),
        migrations.AddField(
            model_name='approvalroutestage',
            name='user_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Согласующие поимённо'),
        ),
        migrations.AlterField(
            model_name='approvalprocessstage',
            name='approver_kind',
            field=models.CharField(choices=[('position', 'По должности'), ('initiator', 'Инициатор согласования'), ('users', 'Конкретные сотрудники'), ('subject', 'Назначает объект')], db_default='position', default='position', max_length=16),
        ),
        migrations.AlterField(
            model_name='approvalroutestage',
            name='approver_kind',
            field=models.CharField(choices=[('position', 'По должности'), ('initiator', 'Инициатор согласования'), ('users', 'Конкретные сотрудники'), ('subject', 'Назначает объект')], db_default='position', default='position', help_text='«Инициатор» — список согласующих не заполняется, решение принимает отправивший объект на согласование', max_length=16, verbose_name='Кто согласует'),
        ),
        migrations.AddConstraint(
            model_name='approvalroute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subject_type', 'scope'), name='uq_signoff_active_route_per_subject'),
        ),
    ]
