# Generated by Django 5.2.7 on 2026-09-26 17:32
"""ApprovalProcess.subject_id: целое → строка (мастер-план БЗО, D-05).

Postgres переписывает столбец с приведением ``USING subject_id::varchar``;
индекс ``ix_signoff_proc_subject`` и частичный уникальный индекс
перестраиваются сами. В схемах компаний — через ``manage.py
migrate_companies``: он снимает представления ``holding.*`` до прогона
(``ApprovalProcess`` входит в HOLDING_MODELS), иначе смена типа упёрлась бы
в зависящее от столбца представление.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0011_task_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalprocess',
            name='subject_id',
            field=models.CharField(max_length=64, verbose_name='Объект'),
        ),
    ]
