# Generated by Django 5.2.7 on 2026-09-26 18:12
"""Флаги маршрута и их снимок в процессе, «Нет исполнителя», время
активации этапа и предсогласованные группы (мастер-план БЗО: B1.2 / D-21,
D-22; ``activated_at`` и ``preapproved`` — B1.3 / D-26).

Только добавление столбцов со значениями по умолчанию — expand-шаг: все
флаги выключены, поведение существующих маршрутов не меняется. В схемы
компаний — ``manage.py migrate_companies``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0012_process_subject_id_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalprocess',
            name='preapproved',
            field=models.JSONField(blank=True, default=list, verbose_name='Предсогласовано'),
        ),
        migrations.AddField(
            model_name='approvalprocess',
            name='route_flags',
            field=models.JSONField(blank=True, default=dict, verbose_name='Флаги маршрута'),
        ),
        migrations.AddField(
            model_name='approvalprocessstage',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='escalation_position_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='forbid_self_approval',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='lazy_resolution',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='no_executor_notify_position_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='reject_comment_min',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='self_skip_notify_position_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='approvalprocessstage',
            name='state',
            field=models.CharField(choices=[('waiting', 'Ожидает очереди'), ('active', 'На рассмотрении'), ('approved', 'Согласован'), ('rejected', 'Отклонён'), ('rework', 'Возвращён на доработку'), ('skipped', 'Не потребовался'), ('no_executor', 'Нет исполнителя')], db_default='waiting', default='waiting', max_length=16),
        ),
    ]
