# Generated by Django 5.2.7 on 2026-09-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0014_retry_no_executor_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalprocessstage',
            name='votes_option',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='approvalroutestage',
            name='votes_option',
            field=models.BooleanField(db_default=False, default=False, help_text='При альтернативах согласующий этапа выбирает вариант', verbose_name='Выбирает вариант'),
        ),
    ]
