# Generated by Django 5.2.7 on 2026-09-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0015_stage_votes_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalroute',
            name='skip_unmatched_groups',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
