# Generated by Django 5.2.7 on 2026-10-03 11:08
"""Согласование между компаниями (мастер-план БЗО, B8.1).

Этап маршрута дочерней компании может стоять на должности вышестоящей
(директора — в штате холдинга): должность становится парой «компания +
должность» — ``ApprovalRouteStageRole.position_company``, снимок этапа
процесса ``role_refs``, задача ``position_company`` и ``also_positions`` (один
человек на двух должностях этапа — одна задача). Флаги маршрута: компания
должности эскалации, получатели уведомлений из вышестоящих компаний и
решение «прямо из холдинга» (``allow_direct_decisions``).

Только расширение (expand): все новые столбцы с умолчанием на уровне БД —
пустая компания значит «своя», как до B8.1, — поэтому код без B8.1 на новой
схеме работает как прежде. Уникальность должности на этапе расширяется на
компанию: сначала новое ограничение, потом снятие старого, чтобы ни на одном
шаге этап не остался без неё. Тенантная аппка — в схемы компаний идёт
``manage.py migrate_companies``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0016_route_skip_unmatched_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalroutestagerole',
            name='position_company',
            field=models.CharField(blank=True, db_default='', default='', help_text='Пусто — своя компания', max_length=32, verbose_name='Компания должности'),
        ),
        migrations.AddConstraint(
            model_name='approvalroutestagerole',
            constraint=models.UniqueConstraint(fields=('stage', 'position_company', 'position_id'), name='uq_signoff_stage_role_company'),
        ),
        migrations.RemoveConstraint(
            model_name='approvalroutestagerole',
            name='uq_signoff_stage_role',
        ),
        migrations.AddField(
            model_name='approvalprocessstage',
            name='role_refs',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='allow_direct_decisions',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='escalation_position_company',
            field=models.CharField(blank=True, db_default='', default='', max_length=32),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='no_executor_notify_foreign',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='self_skip_notify_foreign',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='also_positions',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='position_company',
            field=models.CharField(blank=True, db_default='', default='', max_length=32),
        ),
    ]
