# Generated by Django 5.2.7 on 2026-08-29 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_system', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PositionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(db_index=True, max_length=32)),
                ('position_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_links', to='access.role')),
            ],
            options={
                'verbose_name': 'Роль должности',
                'verbose_name_plural': 'Роли должностей',
                'indexes': [models.Index(fields=['company_slug', 'position_id'], name='access_posi_company_6107da_idx')],
                'constraints': [models.UniqueConstraint(fields=('company_slug', 'position_id', 'role'), name='uniq_position_role')],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(db_index=True, max_length=32)),
                ('user_id', models.IntegerField()),
                ('scope_kind', models.CharField(choices=[('company', 'Компания'), ('department', 'Отдел'), ('site', 'Объект')], max_length=16)),
                ('scope_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='access.role')),
            ],
            options={
                'verbose_name': 'Личное назначение роли',
                'verbose_name_plural': 'Личные назначения ролей',
                'indexes': [models.Index(fields=['company_slug', 'user_id'], name='access_role_company_bf1394_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope_id__isnull', True)), fields=('company_slug', 'user_id', 'role', 'scope_kind'), name='uniq_assignment_unscoped'), models.UniqueConstraint(condition=models.Q(('scope_id__isnull', False)), fields=('company_slug', 'user_id', 'role', 'scope_kind', 'scope_id'), name='uniq_assignment_scoped'), models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_kind', 'company')), models.Q(models.Q(('scope_kind', 'company'), _negated=True), ('scope_id__isnull', False)), _connector='OR'), name='assignment_scope_id_matches_kind')],
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=32)),
                ('level', models.CharField(choices=[('none', 'Нет доступа'), ('read', 'Чтение'), ('write', 'Запись'), ('admin', 'Администрирование')], max_length=8)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access.role')),
            ],
            options={
                'verbose_name': 'Право роли',
                'verbose_name_plural': 'Права ролей',
                'constraints': [models.UniqueConstraint(fields=('role', 'module'), name='uniq_role_module')],
            },
        ),
    ]
