# Generated by Django 5.2.7 on 2026-08-30 22:04

import django.db.models.deletion
from django.db import migrations, models


#: Прежние уровни → набор признаков глубины. Соответствие то же, что в
#: apps/access/depth.py::legacy_level, только в обратную сторону: read — это
#: чтение, write — ввод и правка, admin — вдобавок удаление.
_LEVEL_TO_FLAGS = {
    "none": (),
    "read": ("can_view",),
    "write": ("can_view", "can_create", "can_edit"),
    "admin": ("can_view", "can_create", "can_edit", "can_delete"),
}


def carry_over(apps, schema_editor):
    """Перенести права ролей из «модуль × уровень» в «узел × флаги».

    Модуль сам по себе — узел первого уровня реестра функций, поэтому перенос
    буквальный: имя модуля становится путём узла, уровень раскрывается в флаги.
    Наследование при этом работает сразу — право, выданное на модуль, действует
    на все его функции, ровно как и раньше.
    """
    Old = apps.get_model("access", "RoleModulePermission")
    New = apps.get_model("access", "RolePermission")

    New.objects.bulk_create([
        New(role_id=row.role_id, node=row.module,
            **{flag: True for flag in _LEVEL_TO_FLAGS.get(row.level, ())})
        for row in Old.objects.all()
    ])


def carry_back(apps, schema_editor):
    """Обратный перенос — по правилу legacy_level: удаление → admin и так далее."""
    Old = apps.get_model("access", "RoleModulePermission")
    New = apps.get_model("access", "RolePermission")

    rows = []
    for row in New.objects.all():
        if "." in row.node:
            # У прежней модели не было ничего мельче модуля: права на функции и
            # поля при откате теряются, и это неизбежно — представить их там
            # нечем.
            continue
        if row.can_delete:
            level = "admin"
        elif row.can_create or row.can_edit:
            level = "write"
        elif row.can_view:
            level = "read"
        else:
            continue
        rows.append(Old(role_id=row.role_id, module=row.node, level=level))
    Old.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_seed_platform_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=128)),
                ('can_view', models.BooleanField(db_default=False, default=False)),
                ('can_create', models.BooleanField(db_default=False, default=False)),
                ('can_edit', models.BooleanField(db_default=False, default=False)),
                ('can_delete', models.BooleanField(db_default=False, default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access.role')),
            ],
            options={
                'verbose_name': 'Глубина роли',
                'verbose_name_plural': 'Глубина ролей',
            },
        ),
        migrations.RunPython(carry_over, carry_back),
        migrations.DeleteModel(
            name='RoleModulePermission',
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['node'], name='access_role_node_53c85b_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'node'), name='uniq_role_node'),
        ),
    ]
