# Generated by Django 5.2.7 on 2026-09-17 19:05
"""Область роли должности — задача 1b блока I («Свернуть параллельный RBAC»).

Добавляет ``PositionRole.scope_kind`` (``company`` по умолчанию —
существующие выдачи не меняют смысла; ``department`` — резолвер подставляет
отдел ДЕРЖАТЕЛЯ, не должности; см. докстринг модели). Без этого поля перенос
кадровых уровней (задача 2 того же блока) молча расширил бы доступ junior и
middle со «своего отдела» до всей компании — ``_role_scopes`` до этой
миграции отдавала каждой должностной роли ``ScopeKind.COMPANY`` безусловно.

``apps.access`` живёт в схеме ``public`` (не входит в ``TENANT_APPS``), поэтому
это обычная общая миграция — идёт через ``migrate_shared``, а не через
``migrate_companies``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_seed_hr_level_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionrole',
            name='scope_kind',
            field=models.CharField(choices=[('company', 'Компания'), ('department', 'Отдел'), ('site', 'Объект')], db_default='company', default='company', max_length=16),
        ),
    ]
