# Generated by Django 5.2.7 on 2026-09-17 19:29
"""Сузить ``PositionRole.scope_kind`` до COMPANY/DEPARTMENT — раунд правок 1
ревью задачи 1b блока I.

``0006`` завела поле с полным ``ScopeKind.choices`` (три значения, включая
``site``). Ревью нашло дыру: ``PositionRoleAdmin`` (``apps/access/admin.py``)
не задаёт ``fields``/``fieldsets``, значит рендерит форму по ВСЕМ полям
модели — вместе с ``0006`` в ``/django-admin/`` появился выбор ``site``, хотя
резолвер (``apps/access/services/resolve.py::_position_role_ids``) не умеет
его вычислять (кадровая карточка держателя не несёт ``site_id``), а штатный
API (``assignment.set_position_roles``) ``scope_kind`` вообще не принимает —
админка была ЕДИНСТВЕННЫМ живым путём выставить недоступное резолверу
значение, и делала это молча.

Эта миграция сужает ``choices`` до ``PositionRole.POSITION_ROLE_SCOPE_KINDS``
(``company``/``department``) — админка и ORM-валидация (``full_clean``)
``site`` больше не предложат. Схему БД не меняет (``choices`` — только
Django-валидация, не ``CHECK`` в Postgres), только состояние поля в графе
миграций; строки, которые каким-то образом уже несут ``site`` в обход
``choices`` (прямой SQL, как и до этой миграции), резолвер теперь ГРОМКО
подсвечивает через ``fallback(..., expected=False)`` вместо тихого пропуска.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_positionrole_scope_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionrole',
            name='scope_kind',
            field=models.CharField(choices=[('company', 'Компания'), ('department', 'Отдел')], db_default='company', default='company', max_length=16),
        ),
    ]
