# Generated by Django 5.2.7 on 2026-09-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_hr_role_subnode_denies'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='company_slug',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True),
        ),
    ]
